// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_gemm_5_Pipeline_VITIS_LOOP_151_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_gemm2_out_din,
        s_gemm2_out_full_n,
        s_gemm2_out_write,
        s_gemm2_out_num_data_valid,
        s_gemm2_out_fifo_cap,
        w2_0_load,
        w2_2_load,
        w2_4_load,
        w2_6_load,
        w2_8_load,
        w2_10_load,
        w2_12_load,
        w2_14_load,
        w2_0_load_1,
        w2_2_load_1,
        w2_4_load_1,
        w2_6_load_1,
        w2_8_load_1,
        w2_10_load_1,
        w2_12_load_1,
        w2_14_load_1,
        w2_0_load_2,
        w2_2_load_2,
        w2_4_load_2,
        w2_6_load_2,
        w2_8_load_2,
        w2_10_load_2,
        w2_12_load_2,
        w2_14_load_2,
        w2_0_load_3,
        w2_2_load_3,
        w2_4_load_3,
        w2_6_load_3,
        w2_8_load_3,
        w2_10_load_3,
        w2_12_load_3,
        w2_14_load_3,
        w2_0_load_4,
        w2_2_load_4,
        w2_4_load_4,
        w2_6_load_4,
        w2_8_load_4,
        w2_10_load_4,
        w2_12_load_4,
        w2_14_load_4,
        w2_0_load_5,
        w2_2_load_5,
        w2_4_load_5,
        w2_6_load_5,
        w2_8_load_5,
        w2_10_load_5,
        w2_12_load_5,
        w2_14_load_5,
        w2_0_load_6,
        w2_2_load_6,
        w2_4_load_6,
        w2_6_load_6,
        w2_8_load_6,
        w2_10_load_6,
        w2_12_load_6,
        w2_14_load_6,
        w2_0_load_7,
        w2_2_load_7,
        w2_4_load_7,
        w2_6_load_7,
        w2_8_load_7,
        w2_10_load_7,
        w2_12_load_7,
        w2_14_load_7,
        w2_0_load_8,
        w2_2_load_8,
        w2_4_load_8,
        w2_6_load_8,
        w2_8_load_8,
        w2_10_load_8,
        w2_12_load_8,
        w2_14_load_8,
        w2_0_load_9,
        w2_2_load_9,
        w2_4_load_9,
        w2_6_load_9,
        w2_8_load_9,
        w2_10_load_9,
        w2_12_load_9,
        w2_14_load_9,
        w2_0_load_10,
        w2_2_load_10,
        w2_4_load_10,
        w2_6_load_10,
        w2_8_load_10,
        w2_10_load_10,
        w2_12_load_10,
        w2_14_load_10,
        w2_0_load_11,
        w2_2_load_11,
        w2_4_load_11,
        w2_6_load_11,
        w2_8_load_11,
        w2_10_load_11,
        w2_12_load_11,
        w2_14_load_11,
        w2_0_load_12,
        w2_2_load_12,
        w2_4_load_12,
        w2_6_load_12,
        w2_8_load_12,
        w2_10_load_12,
        w2_12_load_12,
        w2_14_load_12,
        w2_0_load_13,
        w2_2_load_13,
        w2_4_load_13,
        w2_6_load_13,
        w2_8_load_13,
        w2_10_load_13,
        w2_12_load_13,
        w2_14_load_13,
        w2_0_load_14,
        w2_2_load_14,
        w2_4_load_14,
        w2_6_load_14,
        w2_8_load_14,
        w2_10_load_14,
        w2_12_load_14,
        w2_14_load_14,
        w2_0_load_15,
        w2_2_load_15,
        w2_4_load_15,
        w2_6_load_15,
        w2_8_load_15,
        w2_10_load_15,
        w2_12_load_15,
        w2_14_load_15,
        sext_ln160_185,
        sext_ln160_184,
        sext_ln160_183,
        sext_ln160_182,
        sext_ln160_181,
        sext_ln160_180,
        sext_ln160_179,
        sext_ln160_178,
        sext_ln160_177,
        sext_ln160_176,
        sext_ln160_175,
        sext_ln160_174,
        sext_ln160_173,
        sext_ln160_172,
        sext_ln160,
        sext_ln160_171,
        w2_1_load,
        w2_3_load,
        w2_5_load,
        w2_7_load,
        w2_9_load,
        w2_11_load,
        w2_13_load,
        w2_15_load,
        w2_1_load_1,
        w2_3_load_1,
        w2_5_load_1,
        w2_7_load_1,
        w2_9_load_1,
        w2_11_load_1,
        w2_13_load_1,
        w2_15_load_1,
        w2_1_load_2,
        w2_3_load_2,
        w2_5_load_2,
        w2_7_load_2,
        w2_9_load_2,
        w2_11_load_2,
        w2_13_load_2,
        w2_15_load_2,
        w2_1_load_3,
        w2_3_load_3,
        w2_5_load_3,
        w2_7_load_3,
        w2_9_load_3,
        w2_11_load_3,
        w2_13_load_3,
        w2_15_load_3,
        w2_1_load_4,
        w2_3_load_4,
        w2_5_load_4,
        w2_7_load_4,
        w2_9_load_4,
        w2_11_load_4,
        w2_13_load_4,
        w2_15_load_4,
        w2_1_load_5,
        w2_3_load_5,
        w2_5_load_5,
        w2_7_load_5,
        w2_9_load_5,
        w2_11_load_5,
        w2_13_load_5,
        w2_15_load_5,
        w2_1_load_6,
        w2_3_load_6,
        w2_5_load_6,
        w2_7_load_6,
        w2_9_load_6,
        w2_11_load_6,
        w2_13_load_6,
        w2_15_load_6,
        w2_1_load_7,
        w2_3_load_7,
        w2_5_load_7,
        w2_7_load_7,
        w2_9_load_7,
        w2_11_load_7,
        w2_13_load_7,
        w2_15_load_7,
        w2_1_load_8,
        w2_3_load_8,
        w2_5_load_8,
        w2_7_load_8,
        w2_9_load_8,
        w2_11_load_8,
        w2_13_load_8,
        w2_15_load_8,
        w2_1_load_9,
        w2_3_load_9,
        w2_5_load_9,
        w2_7_load_9,
        w2_9_load_9,
        w2_11_load_9,
        w2_13_load_9,
        w2_15_load_9,
        w2_1_load_10,
        w2_3_load_10,
        w2_5_load_10,
        w2_7_load_10,
        w2_9_load_10,
        w2_11_load_10,
        w2_13_load_10,
        w2_15_load_10,
        w2_1_load_11,
        w2_3_load_11,
        w2_5_load_11,
        w2_7_load_11,
        w2_9_load_11,
        w2_11_load_11,
        w2_13_load_11,
        w2_15_load_11,
        w2_1_load_12,
        w2_3_load_12,
        w2_5_load_12,
        w2_7_load_12,
        w2_9_load_12,
        w2_11_load_12,
        w2_13_load_12,
        w2_15_load_12,
        w2_1_load_13,
        w2_3_load_13,
        w2_5_load_13,
        w2_7_load_13,
        w2_9_load_13,
        w2_11_load_13,
        w2_13_load_13,
        w2_15_load_13,
        w2_1_load_14,
        w2_3_load_14,
        w2_5_load_14,
        w2_7_load_14,
        w2_9_load_14,
        w2_11_load_14,
        w2_13_load_14,
        w2_15_load_14,
        w2_1_load_15,
        w2_3_load_15,
        w2_5_load_15,
        w2_7_load_15,
        w2_9_load_15,
        w2_11_load_15,
        w2_13_load_15,
        w2_15_load_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] s_gemm2_out_din;
input   s_gemm2_out_full_n;
output   s_gemm2_out_write;
input  [31:0] s_gemm2_out_num_data_valid;
input  [31:0] s_gemm2_out_fifo_cap;
input  [7:0] w2_0_load;
input  [7:0] w2_2_load;
input  [7:0] w2_4_load;
input  [7:0] w2_6_load;
input  [7:0] w2_8_load;
input  [7:0] w2_10_load;
input  [7:0] w2_12_load;
input  [7:0] w2_14_load;
input  [7:0] w2_0_load_1;
input  [7:0] w2_2_load_1;
input  [7:0] w2_4_load_1;
input  [7:0] w2_6_load_1;
input  [7:0] w2_8_load_1;
input  [7:0] w2_10_load_1;
input  [7:0] w2_12_load_1;
input  [7:0] w2_14_load_1;
input  [7:0] w2_0_load_2;
input  [7:0] w2_2_load_2;
input  [7:0] w2_4_load_2;
input  [7:0] w2_6_load_2;
input  [7:0] w2_8_load_2;
input  [7:0] w2_10_load_2;
input  [7:0] w2_12_load_2;
input  [7:0] w2_14_load_2;
input  [7:0] w2_0_load_3;
input  [7:0] w2_2_load_3;
input  [7:0] w2_4_load_3;
input  [7:0] w2_6_load_3;
input  [7:0] w2_8_load_3;
input  [7:0] w2_10_load_3;
input  [7:0] w2_12_load_3;
input  [7:0] w2_14_load_3;
input  [7:0] w2_0_load_4;
input  [7:0] w2_2_load_4;
input  [7:0] w2_4_load_4;
input  [7:0] w2_6_load_4;
input  [7:0] w2_8_load_4;
input  [7:0] w2_10_load_4;
input  [7:0] w2_12_load_4;
input  [7:0] w2_14_load_4;
input  [7:0] w2_0_load_5;
input  [7:0] w2_2_load_5;
input  [7:0] w2_4_load_5;
input  [7:0] w2_6_load_5;
input  [7:0] w2_8_load_5;
input  [7:0] w2_10_load_5;
input  [7:0] w2_12_load_5;
input  [7:0] w2_14_load_5;
input  [7:0] w2_0_load_6;
input  [7:0] w2_2_load_6;
input  [7:0] w2_4_load_6;
input  [7:0] w2_6_load_6;
input  [7:0] w2_8_load_6;
input  [7:0] w2_10_load_6;
input  [7:0] w2_12_load_6;
input  [7:0] w2_14_load_6;
input  [7:0] w2_0_load_7;
input  [7:0] w2_2_load_7;
input  [7:0] w2_4_load_7;
input  [7:0] w2_6_load_7;
input  [7:0] w2_8_load_7;
input  [7:0] w2_10_load_7;
input  [7:0] w2_12_load_7;
input  [7:0] w2_14_load_7;
input  [7:0] w2_0_load_8;
input  [7:0] w2_2_load_8;
input  [7:0] w2_4_load_8;
input  [7:0] w2_6_load_8;
input  [7:0] w2_8_load_8;
input  [7:0] w2_10_load_8;
input  [7:0] w2_12_load_8;
input  [7:0] w2_14_load_8;
input  [7:0] w2_0_load_9;
input  [7:0] w2_2_load_9;
input  [7:0] w2_4_load_9;
input  [7:0] w2_6_load_9;
input  [7:0] w2_8_load_9;
input  [7:0] w2_10_load_9;
input  [7:0] w2_12_load_9;
input  [7:0] w2_14_load_9;
input  [7:0] w2_0_load_10;
input  [7:0] w2_2_load_10;
input  [7:0] w2_4_load_10;
input  [7:0] w2_6_load_10;
input  [7:0] w2_8_load_10;
input  [7:0] w2_10_load_10;
input  [7:0] w2_12_load_10;
input  [7:0] w2_14_load_10;
input  [7:0] w2_0_load_11;
input  [7:0] w2_2_load_11;
input  [7:0] w2_4_load_11;
input  [7:0] w2_6_load_11;
input  [7:0] w2_8_load_11;
input  [7:0] w2_10_load_11;
input  [7:0] w2_12_load_11;
input  [7:0] w2_14_load_11;
input  [7:0] w2_0_load_12;
input  [7:0] w2_2_load_12;
input  [7:0] w2_4_load_12;
input  [7:0] w2_6_load_12;
input  [7:0] w2_8_load_12;
input  [7:0] w2_10_load_12;
input  [7:0] w2_12_load_12;
input  [7:0] w2_14_load_12;
input  [7:0] w2_0_load_13;
input  [7:0] w2_2_load_13;
input  [7:0] w2_4_load_13;
input  [7:0] w2_6_load_13;
input  [7:0] w2_8_load_13;
input  [7:0] w2_10_load_13;
input  [7:0] w2_12_load_13;
input  [7:0] w2_14_load_13;
input  [7:0] w2_0_load_14;
input  [7:0] w2_2_load_14;
input  [7:0] w2_4_load_14;
input  [7:0] w2_6_load_14;
input  [7:0] w2_8_load_14;
input  [7:0] w2_10_load_14;
input  [7:0] w2_12_load_14;
input  [7:0] w2_14_load_14;
input  [7:0] w2_0_load_15;
input  [7:0] w2_2_load_15;
input  [7:0] w2_4_load_15;
input  [7:0] w2_6_load_15;
input  [7:0] w2_8_load_15;
input  [7:0] w2_10_load_15;
input  [7:0] w2_12_load_15;
input  [7:0] w2_14_load_15;
input  [7:0] sext_ln160_185;
input  [7:0] sext_ln160_184;
input  [7:0] sext_ln160_183;
input  [7:0] sext_ln160_182;
input  [7:0] sext_ln160_181;
input  [7:0] sext_ln160_180;
input  [7:0] sext_ln160_179;
input  [7:0] sext_ln160_178;
input  [7:0] sext_ln160_177;
input  [7:0] sext_ln160_176;
input  [7:0] sext_ln160_175;
input  [7:0] sext_ln160_174;
input  [7:0] sext_ln160_173;
input  [7:0] sext_ln160_172;
input  [7:0] sext_ln160;
input  [7:0] sext_ln160_171;
input  [7:0] w2_1_load;
input  [7:0] w2_3_load;
input  [7:0] w2_5_load;
input  [7:0] w2_7_load;
input  [7:0] w2_9_load;
input  [7:0] w2_11_load;
input  [7:0] w2_13_load;
input  [7:0] w2_15_load;
input  [7:0] w2_1_load_1;
input  [7:0] w2_3_load_1;
input  [7:0] w2_5_load_1;
input  [7:0] w2_7_load_1;
input  [7:0] w2_9_load_1;
input  [7:0] w2_11_load_1;
input  [7:0] w2_13_load_1;
input  [7:0] w2_15_load_1;
input  [7:0] w2_1_load_2;
input  [7:0] w2_3_load_2;
input  [7:0] w2_5_load_2;
input  [7:0] w2_7_load_2;
input  [7:0] w2_9_load_2;
input  [7:0] w2_11_load_2;
input  [7:0] w2_13_load_2;
input  [7:0] w2_15_load_2;
input  [7:0] w2_1_load_3;
input  [7:0] w2_3_load_3;
input  [7:0] w2_5_load_3;
input  [7:0] w2_7_load_3;
input  [7:0] w2_9_load_3;
input  [7:0] w2_11_load_3;
input  [7:0] w2_13_load_3;
input  [7:0] w2_15_load_3;
input  [7:0] w2_1_load_4;
input  [7:0] w2_3_load_4;
input  [7:0] w2_5_load_4;
input  [7:0] w2_7_load_4;
input  [7:0] w2_9_load_4;
input  [7:0] w2_11_load_4;
input  [7:0] w2_13_load_4;
input  [7:0] w2_15_load_4;
input  [7:0] w2_1_load_5;
input  [7:0] w2_3_load_5;
input  [7:0] w2_5_load_5;
input  [7:0] w2_7_load_5;
input  [7:0] w2_9_load_5;
input  [7:0] w2_11_load_5;
input  [7:0] w2_13_load_5;
input  [7:0] w2_15_load_5;
input  [7:0] w2_1_load_6;
input  [7:0] w2_3_load_6;
input  [7:0] w2_5_load_6;
input  [7:0] w2_7_load_6;
input  [7:0] w2_9_load_6;
input  [7:0] w2_11_load_6;
input  [7:0] w2_13_load_6;
input  [7:0] w2_15_load_6;
input  [7:0] w2_1_load_7;
input  [7:0] w2_3_load_7;
input  [7:0] w2_5_load_7;
input  [7:0] w2_7_load_7;
input  [7:0] w2_9_load_7;
input  [7:0] w2_11_load_7;
input  [7:0] w2_13_load_7;
input  [7:0] w2_15_load_7;
input  [7:0] w2_1_load_8;
input  [7:0] w2_3_load_8;
input  [7:0] w2_5_load_8;
input  [7:0] w2_7_load_8;
input  [7:0] w2_9_load_8;
input  [7:0] w2_11_load_8;
input  [7:0] w2_13_load_8;
input  [7:0] w2_15_load_8;
input  [7:0] w2_1_load_9;
input  [7:0] w2_3_load_9;
input  [7:0] w2_5_load_9;
input  [7:0] w2_7_load_9;
input  [7:0] w2_9_load_9;
input  [7:0] w2_11_load_9;
input  [7:0] w2_13_load_9;
input  [7:0] w2_15_load_9;
input  [7:0] w2_1_load_10;
input  [7:0] w2_3_load_10;
input  [7:0] w2_5_load_10;
input  [7:0] w2_7_load_10;
input  [7:0] w2_9_load_10;
input  [7:0] w2_11_load_10;
input  [7:0] w2_13_load_10;
input  [7:0] w2_15_load_10;
input  [7:0] w2_1_load_11;
input  [7:0] w2_3_load_11;
input  [7:0] w2_5_load_11;
input  [7:0] w2_7_load_11;
input  [7:0] w2_9_load_11;
input  [7:0] w2_11_load_11;
input  [7:0] w2_13_load_11;
input  [7:0] w2_15_load_11;
input  [7:0] w2_1_load_12;
input  [7:0] w2_3_load_12;
input  [7:0] w2_5_load_12;
input  [7:0] w2_7_load_12;
input  [7:0] w2_9_load_12;
input  [7:0] w2_11_load_12;
input  [7:0] w2_13_load_12;
input  [7:0] w2_15_load_12;
input  [7:0] w2_1_load_13;
input  [7:0] w2_3_load_13;
input  [7:0] w2_5_load_13;
input  [7:0] w2_7_load_13;
input  [7:0] w2_9_load_13;
input  [7:0] w2_11_load_13;
input  [7:0] w2_13_load_13;
input  [7:0] w2_15_load_13;
input  [7:0] w2_1_load_14;
input  [7:0] w2_3_load_14;
input  [7:0] w2_5_load_14;
input  [7:0] w2_7_load_14;
input  [7:0] w2_9_load_14;
input  [7:0] w2_11_load_14;
input  [7:0] w2_13_load_14;
input  [7:0] w2_15_load_14;
input  [7:0] w2_1_load_15;
input  [7:0] w2_3_load_15;
input  [7:0] w2_5_load_15;
input  [7:0] w2_7_load_15;
input  [7:0] w2_9_load_15;
input  [7:0] w2_11_load_15;
input  [7:0] w2_13_load_15;
input  [7:0] w2_15_load_15;

reg ap_idle;
reg s_gemm2_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln151_fu_2333_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_gemm2_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
wire  signed [15:0] sext_ln160_171_cast_fu_2261_p1;
reg  signed [15:0] sext_ln160_171_cast_reg_5042;
wire  signed [15:0] sext_ln160_cast_fu_2265_p1;
reg  signed [15:0] sext_ln160_cast_reg_5048;
wire  signed [15:0] sext_ln160_172_cast_fu_2269_p1;
wire  signed [15:0] sext_ln160_173_cast_fu_2273_p1;
reg  signed [15:0] sext_ln160_173_cast_reg_5060;
wire  signed [15:0] sext_ln160_174_cast_fu_2277_p1;
reg  signed [15:0] sext_ln160_174_cast_reg_5066;
wire  signed [15:0] sext_ln160_175_cast_fu_2281_p1;
reg  signed [15:0] sext_ln160_175_cast_reg_5072;
wire  signed [15:0] sext_ln160_176_cast_fu_2285_p1;
wire  signed [15:0] sext_ln160_177_cast_fu_2289_p1;
reg  signed [15:0] sext_ln160_177_cast_reg_5084;
wire  signed [15:0] sext_ln160_178_cast_fu_2293_p1;
reg  signed [15:0] sext_ln160_178_cast_reg_5090;
wire  signed [15:0] sext_ln160_179_cast_fu_2297_p1;
reg  signed [15:0] sext_ln160_179_cast_reg_5096;
wire  signed [15:0] sext_ln160_180_cast_fu_2301_p1;
reg  signed [15:0] sext_ln160_180_cast_reg_5102;
wire  signed [15:0] sext_ln160_181_cast_fu_2305_p1;
reg  signed [15:0] sext_ln160_181_cast_reg_5108;
wire  signed [15:0] sext_ln160_182_cast_fu_2309_p1;
reg  signed [15:0] sext_ln160_182_cast_reg_5114;
wire  signed [15:0] sext_ln160_183_cast_fu_2313_p1;
reg  signed [15:0] sext_ln160_183_cast_reg_5120;
wire  signed [15:0] sext_ln160_184_cast_fu_2317_p1;
wire  signed [15:0] sext_ln160_185_cast_fu_2321_p1;
reg  signed [15:0] sext_ln160_185_cast_reg_5132;
wire   [2:0] trunc_ln151_fu_2345_p1;
reg   [2:0] trunc_ln151_reg_5142;
reg   [2:0] trunc_ln151_reg_5142_pp0_iter1_reg;
reg   [2:0] trunc_ln151_reg_5142_pp0_iter2_reg;
reg   [2:0] trunc_ln151_reg_5142_pp0_iter3_reg;
reg   [2:0] trunc_ln151_reg_5142_pp0_iter4_reg;
wire  signed [16:0] grp_fu_3835_p3;
wire  signed [16:0] grp_fu_3827_p3;
wire  signed [16:0] grp_fu_3819_p3;
wire  signed [16:0] grp_fu_3859_p3;
wire  signed [16:0] grp_fu_3851_p3;
wire  signed [16:0] grp_fu_3843_p3;
wire  signed [16:0] grp_fu_3883_p3;
reg  signed [16:0] add_ln160_62_reg_5352;
wire   [17:0] add_ln160_70_fu_3504_p2;
reg   [17:0] add_ln160_70_reg_5357;
reg   [17:0] add_ln160_70_reg_5357_pp0_iter5_reg;
wire  signed [16:0] grp_fu_3914_p3;
reg  signed [16:0] add_ln160_77_reg_5372;
wire   [17:0] add_ln160_85_fu_3554_p2;
reg   [17:0] add_ln160_85_reg_5377;
reg   [17:0] add_ln160_85_reg_5377_pp0_iter5_reg;
wire   [0:0] icmp_ln164_fu_3746_p2;
reg   [0:0] icmp_ln164_reg_5412;
wire   [7:0] trunc_ln165_fu_3752_p1;
reg   [7:0] trunc_ln165_reg_5417;
wire   [0:0] icmp_ln164_3_fu_3788_p2;
reg   [0:0] icmp_ln164_3_reg_5422;
wire   [7:0] trunc_ln165_4_fu_3794_p1;
reg   [7:0] trunc_ln165_4_reg_5427;
reg   [3:0] j_fu_618;
wire   [3:0] add_ln151_fu_2339_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_4;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] tmp_61_fu_2349_p17;
wire  signed [7:0] tmp_61_fu_2349_p19;
wire   [7:0] tmp_65_fu_2393_p17;
wire  signed [7:0] tmp_65_fu_2393_p19;
wire   [7:0] tmp_73_fu_2437_p17;
wire  signed [7:0] tmp_73_fu_2437_p19;
wire   [7:0] tmp_77_fu_2481_p17;
wire  signed [7:0] tmp_77_fu_2481_p19;
wire   [7:0] tmp_81_fu_2525_p17;
wire  signed [7:0] tmp_81_fu_2525_p19;
wire   [7:0] tmp_89_fu_2569_p17;
wire  signed [7:0] tmp_89_fu_2569_p19;
wire   [7:0] tmp_s_fu_2618_p17;
wire  signed [7:0] tmp_s_fu_2618_p19;
wire   [7:0] tmp_63_fu_2653_p17;
wire  signed [7:0] tmp_63_fu_2653_p19;
wire   [7:0] tmp_70_fu_2688_p17;
wire  signed [7:0] tmp_70_fu_2688_p19;
wire   [7:0] tmp_71_fu_2723_p17;
wire  signed [7:0] tmp_71_fu_2723_p19;
wire   [7:0] tmp_76_fu_2758_p17;
wire  signed [7:0] tmp_76_fu_2758_p19;
wire   [7:0] tmp_79_fu_2793_p17;
wire  signed [7:0] tmp_79_fu_2793_p19;
wire   [7:0] tmp_86_fu_2828_p17;
wire  signed [7:0] tmp_86_fu_2828_p19;
wire   [7:0] tmp_87_fu_2863_p17;
wire  signed [7:0] tmp_87_fu_2863_p19;
wire   [7:0] tmp_fu_2898_p17;
wire  signed [7:0] tmp_fu_2898_p19;
wire   [7:0] tmp_62_fu_2933_p17;
wire  signed [7:0] tmp_62_fu_2933_p19;
wire   [7:0] tmp_64_fu_2968_p17;
wire  signed [7:0] tmp_64_fu_2968_p19;
wire   [7:0] tmp_72_fu_3003_p17;
wire  signed [7:0] tmp_72_fu_3003_p19;
wire  signed [7:0] mul_ln160_64_fu_3038_p1;
wire  signed [15:0] mul_ln160_64_fu_3038_p2;
wire  signed [7:0] mul_ln160_72_fu_3047_p1;
wire  signed [15:0] mul_ln160_72_fu_3047_p2;
wire  signed [7:0] mul_ln160_76_fu_3056_p1;
wire  signed [15:0] mul_ln160_76_fu_3056_p2;
wire   [7:0] tmp_75_fu_3065_p17;
wire  signed [7:0] tmp_75_fu_3065_p19;
wire   [7:0] tmp_78_fu_3100_p17;
wire  signed [7:0] tmp_78_fu_3100_p19;
wire   [7:0] tmp_80_fu_3135_p17;
wire  signed [7:0] tmp_80_fu_3135_p19;
wire   [7:0] tmp_88_fu_3170_p17;
wire  signed [7:0] tmp_88_fu_3170_p19;
wire  signed [7:0] mul_ln160_80_fu_3205_p1;
wire  signed [15:0] mul_ln160_80_fu_3205_p2;
wire  signed [7:0] mul_ln160_88_fu_3214_p1;
wire  signed [15:0] mul_ln160_88_fu_3214_p2;
wire  signed [7:0] mul_ln160_92_fu_3223_p1;
wire  signed [15:0] mul_ln160_92_fu_3223_p2;
wire   [7:0] tmp_66_fu_3232_p17;
wire  signed [7:0] tmp_66_fu_3232_p19;
wire   [7:0] tmp_68_fu_3267_p17;
wire  signed [7:0] tmp_68_fu_3267_p19;
wire   [7:0] tmp_69_fu_3302_p17;
wire  signed [7:0] tmp_69_fu_3302_p19;
wire  signed [7:0] mul_ln160_67_fu_3337_p1;
wire  signed [15:0] mul_ln160_67_fu_3337_p2;
wire   [7:0] tmp_82_fu_3346_p17;
wire  signed [7:0] tmp_82_fu_3346_p19;
wire   [7:0] tmp_84_fu_3381_p17;
wire  signed [7:0] tmp_84_fu_3381_p19;
wire   [7:0] tmp_85_fu_3416_p17;
wire  signed [7:0] tmp_85_fu_3416_p19;
wire  signed [7:0] mul_ln160_83_fu_3451_p1;
wire  signed [15:0] mul_ln160_83_fu_3451_p2;
wire   [7:0] tmp_74_fu_3460_p17;
wire  signed [7:0] tmp_74_fu_3460_p19;
wire  signed [16:0] grp_fu_3890_p3;
wire  signed [16:0] grp_fu_3875_p3;
wire  signed [16:0] grp_fu_3867_p3;
wire  signed [17:0] sext_ln160_241_fu_3501_p1;
wire  signed [17:0] sext_ln160_240_fu_3498_p1;
wire   [7:0] tmp_90_fu_3510_p17;
wire  signed [7:0] tmp_90_fu_3510_p19;
wire  signed [16:0] grp_fu_3921_p3;
wire  signed [16:0] grp_fu_3906_p3;
wire  signed [16:0] grp_fu_3898_p3;
wire  signed [17:0] sext_ln160_264_fu_3551_p1;
wire  signed [17:0] sext_ln160_263_fu_3548_p1;
wire   [7:0] tmp_67_fu_3560_p17;
wire  signed [7:0] tmp_67_fu_3560_p19;
wire  signed [7:0] mul_ln160_69_fu_3595_p1;
wire  signed [15:0] mul_ln160_69_fu_3595_p2;
wire  signed [17:0] sext_ln160_238_fu_3604_p1;
wire  signed [17:0] grp_fu_3929_p3;
(* use_dsp = "no" *) wire  signed [17:0] add_ln160_63_fu_3607_p2;
wire   [7:0] tmp_83_fu_3616_p17;
wire  signed [7:0] tmp_83_fu_3616_p19;
wire  signed [7:0] mul_ln160_85_fu_3651_p1;
wire  signed [15:0] mul_ln160_85_fu_3651_p2;
wire  signed [17:0] sext_ln160_261_fu_3660_p1;
wire  signed [17:0] grp_fu_3937_p3;
(* use_dsp = "no" *) wire  signed [17:0] add_ln160_78_fu_3663_p2;
wire  signed [16:0] grp_fu_3945_p3;
wire  signed [18:0] sext_ln160_239_fu_3672_p1;
wire  signed [18:0] grp_fu_3953_p3;
wire  signed [18:0] sext_ln160_242_fu_3680_p1;
(* use_dsp = "no" *) wire   [18:0] add_ln160_66_fu_3675_p2;
wire  signed [18:0] add_ln160_71_fu_3683_p2;
wire  signed [16:0] grp_fu_3961_p3;
wire  signed [18:0] sext_ln160_262_fu_3693_p1;
wire  signed [18:0] grp_fu_3969_p3;
wire  signed [18:0] sext_ln160_265_fu_3701_p1;
(* use_dsp = "no" *) wire   [18:0] add_ln160_81_fu_3696_p2;
wire  signed [18:0] add_ln160_86_fu_3704_p2;
wire  signed [19:0] grp_fu_3977_p3;
wire   [4:0] tmp_91_fu_3723_p4;
wire   [0:0] icmp_ln163_fu_3732_p2;
wire   [11:0] requant_fu_3714_p4;
wire   [11:0] requant_10_fu_3738_p3;
wire  signed [19:0] grp_fu_3986_p3;
wire   [4:0] tmp_92_fu_3765_p4;
wire   [0:0] icmp_ln163_4_fu_3774_p2;
wire   [11:0] requant_8_fu_3756_p4;
wire   [11:0] requant_11_fu_3780_p3;
wire   [7:0] elems_22_fu_3804_p3;
wire   [7:0] elems_fu_3798_p3;
wire  signed [7:0] grp_fu_3819_p1;
wire  signed [7:0] grp_fu_3827_p1;
wire  signed [7:0] grp_fu_3835_p1;
wire  signed [7:0] grp_fu_3843_p1;
wire  signed [7:0] grp_fu_3851_p1;
wire  signed [7:0] grp_fu_3859_p1;
wire  signed [7:0] grp_fu_3867_p1;
wire  signed [7:0] grp_fu_3875_p1;
wire  signed [7:0] grp_fu_3883_p1;
wire  signed [7:0] grp_fu_3890_p1;
wire  signed [7:0] grp_fu_3898_p1;
wire  signed [7:0] grp_fu_3906_p1;
wire  signed [7:0] grp_fu_3914_p1;
wire  signed [7:0] grp_fu_3921_p1;
wire  signed [7:0] grp_fu_3929_p1;
wire  signed [7:0] grp_fu_3937_p1;
wire  signed [7:0] grp_fu_3945_p1;
wire  signed [7:0] grp_fu_3953_p1;
wire  signed [7:0] grp_fu_3961_p1;
wire  signed [7:0] grp_fu_3969_p1;
wire  signed [7:0] grp_fu_3977_p1;
wire  signed [7:0] grp_fu_3986_p1;
reg    grp_fu_3819_ce;
reg    grp_fu_3827_ce;
reg    grp_fu_3835_ce;
reg    grp_fu_3843_ce;
reg    grp_fu_3851_ce;
reg    grp_fu_3859_ce;
reg    grp_fu_3867_ce;
reg    grp_fu_3875_ce;
reg    grp_fu_3883_ce;
reg    grp_fu_3890_ce;
reg    grp_fu_3898_ce;
reg    grp_fu_3906_ce;
reg    grp_fu_3914_ce;
reg    grp_fu_3921_ce;
reg    grp_fu_3929_ce;
reg    grp_fu_3937_ce;
reg    grp_fu_3945_ce;
reg    grp_fu_3953_ce;
reg    grp_fu_3961_ce;
reg    grp_fu_3969_ce;
reg    grp_fu_3977_ce;
reg    grp_fu_3986_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] tmp_61_fu_2349_p1;
wire   [2:0] tmp_61_fu_2349_p3;
wire   [2:0] tmp_61_fu_2349_p5;
wire   [2:0] tmp_61_fu_2349_p7;
wire  signed [2:0] tmp_61_fu_2349_p9;
wire  signed [2:0] tmp_61_fu_2349_p11;
wire  signed [2:0] tmp_61_fu_2349_p13;
wire  signed [2:0] tmp_61_fu_2349_p15;
wire   [2:0] tmp_65_fu_2393_p1;
wire   [2:0] tmp_65_fu_2393_p3;
wire   [2:0] tmp_65_fu_2393_p5;
wire   [2:0] tmp_65_fu_2393_p7;
wire  signed [2:0] tmp_65_fu_2393_p9;
wire  signed [2:0] tmp_65_fu_2393_p11;
wire  signed [2:0] tmp_65_fu_2393_p13;
wire  signed [2:0] tmp_65_fu_2393_p15;
wire   [2:0] tmp_73_fu_2437_p1;
wire   [2:0] tmp_73_fu_2437_p3;
wire   [2:0] tmp_73_fu_2437_p5;
wire   [2:0] tmp_73_fu_2437_p7;
wire  signed [2:0] tmp_73_fu_2437_p9;
wire  signed [2:0] tmp_73_fu_2437_p11;
wire  signed [2:0] tmp_73_fu_2437_p13;
wire  signed [2:0] tmp_73_fu_2437_p15;
wire   [2:0] tmp_77_fu_2481_p1;
wire   [2:0] tmp_77_fu_2481_p3;
wire   [2:0] tmp_77_fu_2481_p5;
wire   [2:0] tmp_77_fu_2481_p7;
wire  signed [2:0] tmp_77_fu_2481_p9;
wire  signed [2:0] tmp_77_fu_2481_p11;
wire  signed [2:0] tmp_77_fu_2481_p13;
wire  signed [2:0] tmp_77_fu_2481_p15;
wire   [2:0] tmp_81_fu_2525_p1;
wire   [2:0] tmp_81_fu_2525_p3;
wire   [2:0] tmp_81_fu_2525_p5;
wire   [2:0] tmp_81_fu_2525_p7;
wire  signed [2:0] tmp_81_fu_2525_p9;
wire  signed [2:0] tmp_81_fu_2525_p11;
wire  signed [2:0] tmp_81_fu_2525_p13;
wire  signed [2:0] tmp_81_fu_2525_p15;
wire   [2:0] tmp_89_fu_2569_p1;
wire   [2:0] tmp_89_fu_2569_p3;
wire   [2:0] tmp_89_fu_2569_p5;
wire   [2:0] tmp_89_fu_2569_p7;
wire  signed [2:0] tmp_89_fu_2569_p9;
wire  signed [2:0] tmp_89_fu_2569_p11;
wire  signed [2:0] tmp_89_fu_2569_p13;
wire  signed [2:0] tmp_89_fu_2569_p15;
wire   [2:0] tmp_s_fu_2618_p1;
wire   [2:0] tmp_s_fu_2618_p3;
wire   [2:0] tmp_s_fu_2618_p5;
wire   [2:0] tmp_s_fu_2618_p7;
wire  signed [2:0] tmp_s_fu_2618_p9;
wire  signed [2:0] tmp_s_fu_2618_p11;
wire  signed [2:0] tmp_s_fu_2618_p13;
wire  signed [2:0] tmp_s_fu_2618_p15;
wire   [2:0] tmp_63_fu_2653_p1;
wire   [2:0] tmp_63_fu_2653_p3;
wire   [2:0] tmp_63_fu_2653_p5;
wire   [2:0] tmp_63_fu_2653_p7;
wire  signed [2:0] tmp_63_fu_2653_p9;
wire  signed [2:0] tmp_63_fu_2653_p11;
wire  signed [2:0] tmp_63_fu_2653_p13;
wire  signed [2:0] tmp_63_fu_2653_p15;
wire   [2:0] tmp_70_fu_2688_p1;
wire   [2:0] tmp_70_fu_2688_p3;
wire   [2:0] tmp_70_fu_2688_p5;
wire   [2:0] tmp_70_fu_2688_p7;
wire  signed [2:0] tmp_70_fu_2688_p9;
wire  signed [2:0] tmp_70_fu_2688_p11;
wire  signed [2:0] tmp_70_fu_2688_p13;
wire  signed [2:0] tmp_70_fu_2688_p15;
wire   [2:0] tmp_71_fu_2723_p1;
wire   [2:0] tmp_71_fu_2723_p3;
wire   [2:0] tmp_71_fu_2723_p5;
wire   [2:0] tmp_71_fu_2723_p7;
wire  signed [2:0] tmp_71_fu_2723_p9;
wire  signed [2:0] tmp_71_fu_2723_p11;
wire  signed [2:0] tmp_71_fu_2723_p13;
wire  signed [2:0] tmp_71_fu_2723_p15;
wire   [2:0] tmp_76_fu_2758_p1;
wire   [2:0] tmp_76_fu_2758_p3;
wire   [2:0] tmp_76_fu_2758_p5;
wire   [2:0] tmp_76_fu_2758_p7;
wire  signed [2:0] tmp_76_fu_2758_p9;
wire  signed [2:0] tmp_76_fu_2758_p11;
wire  signed [2:0] tmp_76_fu_2758_p13;
wire  signed [2:0] tmp_76_fu_2758_p15;
wire   [2:0] tmp_79_fu_2793_p1;
wire   [2:0] tmp_79_fu_2793_p3;
wire   [2:0] tmp_79_fu_2793_p5;
wire   [2:0] tmp_79_fu_2793_p7;
wire  signed [2:0] tmp_79_fu_2793_p9;
wire  signed [2:0] tmp_79_fu_2793_p11;
wire  signed [2:0] tmp_79_fu_2793_p13;
wire  signed [2:0] tmp_79_fu_2793_p15;
wire   [2:0] tmp_86_fu_2828_p1;
wire   [2:0] tmp_86_fu_2828_p3;
wire   [2:0] tmp_86_fu_2828_p5;
wire   [2:0] tmp_86_fu_2828_p7;
wire  signed [2:0] tmp_86_fu_2828_p9;
wire  signed [2:0] tmp_86_fu_2828_p11;
wire  signed [2:0] tmp_86_fu_2828_p13;
wire  signed [2:0] tmp_86_fu_2828_p15;
wire   [2:0] tmp_87_fu_2863_p1;
wire   [2:0] tmp_87_fu_2863_p3;
wire   [2:0] tmp_87_fu_2863_p5;
wire   [2:0] tmp_87_fu_2863_p7;
wire  signed [2:0] tmp_87_fu_2863_p9;
wire  signed [2:0] tmp_87_fu_2863_p11;
wire  signed [2:0] tmp_87_fu_2863_p13;
wire  signed [2:0] tmp_87_fu_2863_p15;
wire   [2:0] tmp_fu_2898_p1;
wire   [2:0] tmp_fu_2898_p3;
wire   [2:0] tmp_fu_2898_p5;
wire   [2:0] tmp_fu_2898_p7;
wire  signed [2:0] tmp_fu_2898_p9;
wire  signed [2:0] tmp_fu_2898_p11;
wire  signed [2:0] tmp_fu_2898_p13;
wire  signed [2:0] tmp_fu_2898_p15;
wire   [2:0] tmp_62_fu_2933_p1;
wire   [2:0] tmp_62_fu_2933_p3;
wire   [2:0] tmp_62_fu_2933_p5;
wire   [2:0] tmp_62_fu_2933_p7;
wire  signed [2:0] tmp_62_fu_2933_p9;
wire  signed [2:0] tmp_62_fu_2933_p11;
wire  signed [2:0] tmp_62_fu_2933_p13;
wire  signed [2:0] tmp_62_fu_2933_p15;
wire   [2:0] tmp_64_fu_2968_p1;
wire   [2:0] tmp_64_fu_2968_p3;
wire   [2:0] tmp_64_fu_2968_p5;
wire   [2:0] tmp_64_fu_2968_p7;
wire  signed [2:0] tmp_64_fu_2968_p9;
wire  signed [2:0] tmp_64_fu_2968_p11;
wire  signed [2:0] tmp_64_fu_2968_p13;
wire  signed [2:0] tmp_64_fu_2968_p15;
wire   [2:0] tmp_72_fu_3003_p1;
wire   [2:0] tmp_72_fu_3003_p3;
wire   [2:0] tmp_72_fu_3003_p5;
wire   [2:0] tmp_72_fu_3003_p7;
wire  signed [2:0] tmp_72_fu_3003_p9;
wire  signed [2:0] tmp_72_fu_3003_p11;
wire  signed [2:0] tmp_72_fu_3003_p13;
wire  signed [2:0] tmp_72_fu_3003_p15;
wire   [2:0] tmp_75_fu_3065_p1;
wire   [2:0] tmp_75_fu_3065_p3;
wire   [2:0] tmp_75_fu_3065_p5;
wire   [2:0] tmp_75_fu_3065_p7;
wire  signed [2:0] tmp_75_fu_3065_p9;
wire  signed [2:0] tmp_75_fu_3065_p11;
wire  signed [2:0] tmp_75_fu_3065_p13;
wire  signed [2:0] tmp_75_fu_3065_p15;
wire   [2:0] tmp_78_fu_3100_p1;
wire   [2:0] tmp_78_fu_3100_p3;
wire   [2:0] tmp_78_fu_3100_p5;
wire   [2:0] tmp_78_fu_3100_p7;
wire  signed [2:0] tmp_78_fu_3100_p9;
wire  signed [2:0] tmp_78_fu_3100_p11;
wire  signed [2:0] tmp_78_fu_3100_p13;
wire  signed [2:0] tmp_78_fu_3100_p15;
wire   [2:0] tmp_80_fu_3135_p1;
wire   [2:0] tmp_80_fu_3135_p3;
wire   [2:0] tmp_80_fu_3135_p5;
wire   [2:0] tmp_80_fu_3135_p7;
wire  signed [2:0] tmp_80_fu_3135_p9;
wire  signed [2:0] tmp_80_fu_3135_p11;
wire  signed [2:0] tmp_80_fu_3135_p13;
wire  signed [2:0] tmp_80_fu_3135_p15;
wire   [2:0] tmp_88_fu_3170_p1;
wire   [2:0] tmp_88_fu_3170_p3;
wire   [2:0] tmp_88_fu_3170_p5;
wire   [2:0] tmp_88_fu_3170_p7;
wire  signed [2:0] tmp_88_fu_3170_p9;
wire  signed [2:0] tmp_88_fu_3170_p11;
wire  signed [2:0] tmp_88_fu_3170_p13;
wire  signed [2:0] tmp_88_fu_3170_p15;
wire   [2:0] tmp_66_fu_3232_p1;
wire   [2:0] tmp_66_fu_3232_p3;
wire   [2:0] tmp_66_fu_3232_p5;
wire   [2:0] tmp_66_fu_3232_p7;
wire  signed [2:0] tmp_66_fu_3232_p9;
wire  signed [2:0] tmp_66_fu_3232_p11;
wire  signed [2:0] tmp_66_fu_3232_p13;
wire  signed [2:0] tmp_66_fu_3232_p15;
wire   [2:0] tmp_68_fu_3267_p1;
wire   [2:0] tmp_68_fu_3267_p3;
wire   [2:0] tmp_68_fu_3267_p5;
wire   [2:0] tmp_68_fu_3267_p7;
wire  signed [2:0] tmp_68_fu_3267_p9;
wire  signed [2:0] tmp_68_fu_3267_p11;
wire  signed [2:0] tmp_68_fu_3267_p13;
wire  signed [2:0] tmp_68_fu_3267_p15;
wire   [2:0] tmp_69_fu_3302_p1;
wire   [2:0] tmp_69_fu_3302_p3;
wire   [2:0] tmp_69_fu_3302_p5;
wire   [2:0] tmp_69_fu_3302_p7;
wire  signed [2:0] tmp_69_fu_3302_p9;
wire  signed [2:0] tmp_69_fu_3302_p11;
wire  signed [2:0] tmp_69_fu_3302_p13;
wire  signed [2:0] tmp_69_fu_3302_p15;
wire   [2:0] tmp_82_fu_3346_p1;
wire   [2:0] tmp_82_fu_3346_p3;
wire   [2:0] tmp_82_fu_3346_p5;
wire   [2:0] tmp_82_fu_3346_p7;
wire  signed [2:0] tmp_82_fu_3346_p9;
wire  signed [2:0] tmp_82_fu_3346_p11;
wire  signed [2:0] tmp_82_fu_3346_p13;
wire  signed [2:0] tmp_82_fu_3346_p15;
wire   [2:0] tmp_84_fu_3381_p1;
wire   [2:0] tmp_84_fu_3381_p3;
wire   [2:0] tmp_84_fu_3381_p5;
wire   [2:0] tmp_84_fu_3381_p7;
wire  signed [2:0] tmp_84_fu_3381_p9;
wire  signed [2:0] tmp_84_fu_3381_p11;
wire  signed [2:0] tmp_84_fu_3381_p13;
wire  signed [2:0] tmp_84_fu_3381_p15;
wire   [2:0] tmp_85_fu_3416_p1;
wire   [2:0] tmp_85_fu_3416_p3;
wire   [2:0] tmp_85_fu_3416_p5;
wire   [2:0] tmp_85_fu_3416_p7;
wire  signed [2:0] tmp_85_fu_3416_p9;
wire  signed [2:0] tmp_85_fu_3416_p11;
wire  signed [2:0] tmp_85_fu_3416_p13;
wire  signed [2:0] tmp_85_fu_3416_p15;
wire   [2:0] tmp_74_fu_3460_p1;
wire   [2:0] tmp_74_fu_3460_p3;
wire   [2:0] tmp_74_fu_3460_p5;
wire   [2:0] tmp_74_fu_3460_p7;
wire  signed [2:0] tmp_74_fu_3460_p9;
wire  signed [2:0] tmp_74_fu_3460_p11;
wire  signed [2:0] tmp_74_fu_3460_p13;
wire  signed [2:0] tmp_74_fu_3460_p15;
wire   [2:0] tmp_90_fu_3510_p1;
wire   [2:0] tmp_90_fu_3510_p3;
wire   [2:0] tmp_90_fu_3510_p5;
wire   [2:0] tmp_90_fu_3510_p7;
wire  signed [2:0] tmp_90_fu_3510_p9;
wire  signed [2:0] tmp_90_fu_3510_p11;
wire  signed [2:0] tmp_90_fu_3510_p13;
wire  signed [2:0] tmp_90_fu_3510_p15;
wire   [2:0] tmp_67_fu_3560_p1;
wire   [2:0] tmp_67_fu_3560_p3;
wire   [2:0] tmp_67_fu_3560_p5;
wire   [2:0] tmp_67_fu_3560_p7;
wire  signed [2:0] tmp_67_fu_3560_p9;
wire  signed [2:0] tmp_67_fu_3560_p11;
wire  signed [2:0] tmp_67_fu_3560_p13;
wire  signed [2:0] tmp_67_fu_3560_p15;
wire   [2:0] tmp_83_fu_3616_p1;
wire   [2:0] tmp_83_fu_3616_p3;
wire   [2:0] tmp_83_fu_3616_p5;
wire   [2:0] tmp_83_fu_3616_p7;
wire  signed [2:0] tmp_83_fu_3616_p9;
wire  signed [2:0] tmp_83_fu_3616_p11;
wire  signed [2:0] tmp_83_fu_3616_p13;
wire  signed [2:0] tmp_83_fu_3616_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 j_fu_618 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U473(
    .din0(w2_0_load_2),
    .din1(w2_2_load_2),
    .din2(w2_4_load_2),
    .din3(w2_6_load_2),
    .din4(w2_8_load_2),
    .din5(w2_10_load_2),
    .din6(w2_12_load_2),
    .din7(w2_14_load_2),
    .def(tmp_61_fu_2349_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_61_fu_2349_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U474(
    .din0(w2_0_load_6),
    .din1(w2_2_load_6),
    .din2(w2_4_load_6),
    .din3(w2_6_load_6),
    .din4(w2_8_load_6),
    .din5(w2_10_load_6),
    .din6(w2_12_load_6),
    .din7(w2_14_load_6),
    .def(tmp_65_fu_2393_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_65_fu_2393_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U475(
    .din0(w2_0_load_14),
    .din1(w2_2_load_14),
    .din2(w2_4_load_14),
    .din3(w2_6_load_14),
    .din4(w2_8_load_14),
    .din5(w2_10_load_14),
    .din6(w2_12_load_14),
    .din7(w2_14_load_14),
    .def(tmp_73_fu_2437_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_73_fu_2437_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U476(
    .din0(w2_1_load_2),
    .din1(w2_3_load_2),
    .din2(w2_5_load_2),
    .din3(w2_7_load_2),
    .din4(w2_9_load_2),
    .din5(w2_11_load_2),
    .din6(w2_13_load_2),
    .din7(w2_15_load_2),
    .def(tmp_77_fu_2481_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_77_fu_2481_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U477(
    .din0(w2_1_load_6),
    .din1(w2_3_load_6),
    .din2(w2_5_load_6),
    .din3(w2_7_load_6),
    .din4(w2_9_load_6),
    .din5(w2_11_load_6),
    .din6(w2_13_load_6),
    .din7(w2_15_load_6),
    .def(tmp_81_fu_2525_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_81_fu_2525_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U478(
    .din0(w2_1_load_14),
    .din1(w2_3_load_14),
    .din2(w2_5_load_14),
    .din3(w2_7_load_14),
    .din4(w2_9_load_14),
    .din5(w2_11_load_14),
    .din6(w2_13_load_14),
    .din7(w2_15_load_14),
    .def(tmp_89_fu_2569_p17),
    .sel(trunc_ln151_fu_2345_p1),
    .dout(tmp_89_fu_2569_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U479(
    .din0(w2_0_load_1),
    .din1(w2_2_load_1),
    .din2(w2_4_load_1),
    .din3(w2_6_load_1),
    .din4(w2_8_load_1),
    .din5(w2_10_load_1),
    .din6(w2_12_load_1),
    .din7(w2_14_load_1),
    .def(tmp_s_fu_2618_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_s_fu_2618_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U480(
    .din0(w2_0_load_4),
    .din1(w2_2_load_4),
    .din2(w2_4_load_4),
    .din3(w2_6_load_4),
    .din4(w2_8_load_4),
    .din5(w2_10_load_4),
    .din6(w2_12_load_4),
    .din7(w2_14_load_4),
    .def(tmp_63_fu_2653_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_63_fu_2653_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U481(
    .din0(w2_0_load_11),
    .din1(w2_2_load_11),
    .din2(w2_4_load_11),
    .din3(w2_6_load_11),
    .din4(w2_8_load_11),
    .din5(w2_10_load_11),
    .din6(w2_12_load_11),
    .din7(w2_14_load_11),
    .def(tmp_70_fu_2688_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_70_fu_2688_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U482(
    .din0(w2_0_load_12),
    .din1(w2_2_load_12),
    .din2(w2_4_load_12),
    .din3(w2_6_load_12),
    .din4(w2_8_load_12),
    .din5(w2_10_load_12),
    .din6(w2_12_load_12),
    .din7(w2_14_load_12),
    .def(tmp_71_fu_2723_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_71_fu_2723_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U483(
    .din0(w2_1_load_1),
    .din1(w2_3_load_1),
    .din2(w2_5_load_1),
    .din3(w2_7_load_1),
    .din4(w2_9_load_1),
    .din5(w2_11_load_1),
    .din6(w2_13_load_1),
    .din7(w2_15_load_1),
    .def(tmp_76_fu_2758_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_76_fu_2758_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U484(
    .din0(w2_1_load_4),
    .din1(w2_3_load_4),
    .din2(w2_5_load_4),
    .din3(w2_7_load_4),
    .din4(w2_9_load_4),
    .din5(w2_11_load_4),
    .din6(w2_13_load_4),
    .din7(w2_15_load_4),
    .def(tmp_79_fu_2793_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_79_fu_2793_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U485(
    .din0(w2_1_load_11),
    .din1(w2_3_load_11),
    .din2(w2_5_load_11),
    .din3(w2_7_load_11),
    .din4(w2_9_load_11),
    .din5(w2_11_load_11),
    .din6(w2_13_load_11),
    .din7(w2_15_load_11),
    .def(tmp_86_fu_2828_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_86_fu_2828_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U486(
    .din0(w2_1_load_12),
    .din1(w2_3_load_12),
    .din2(w2_5_load_12),
    .din3(w2_7_load_12),
    .din4(w2_9_load_12),
    .din5(w2_11_load_12),
    .din6(w2_13_load_12),
    .din7(w2_15_load_12),
    .def(tmp_87_fu_2863_p17),
    .sel(trunc_ln151_reg_5142),
    .dout(tmp_87_fu_2863_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U487(
    .din0(w2_0_load),
    .din1(w2_2_load),
    .din2(w2_4_load),
    .din3(w2_6_load),
    .din4(w2_8_load),
    .din5(w2_10_load),
    .din6(w2_12_load),
    .din7(w2_14_load),
    .def(tmp_fu_2898_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_fu_2898_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U488(
    .din0(w2_0_load_3),
    .din1(w2_2_load_3),
    .din2(w2_4_load_3),
    .din3(w2_6_load_3),
    .din4(w2_8_load_3),
    .din5(w2_10_load_3),
    .din6(w2_12_load_3),
    .din7(w2_14_load_3),
    .def(tmp_62_fu_2933_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_62_fu_2933_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U489(
    .din0(w2_0_load_5),
    .din1(w2_2_load_5),
    .din2(w2_4_load_5),
    .din3(w2_6_load_5),
    .din4(w2_8_load_5),
    .din5(w2_10_load_5),
    .din6(w2_12_load_5),
    .din7(w2_14_load_5),
    .def(tmp_64_fu_2968_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_64_fu_2968_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U490(
    .din0(w2_0_load_13),
    .din1(w2_2_load_13),
    .din2(w2_4_load_13),
    .din3(w2_6_load_13),
    .din4(w2_8_load_13),
    .din5(w2_10_load_13),
    .din6(w2_12_load_13),
    .din7(w2_14_load_13),
    .def(tmp_72_fu_3003_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_72_fu_3003_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U491(
    .din0(tmp_72_fu_3003_p19),
    .din1(mul_ln160_64_fu_3038_p1),
    .dout(mul_ln160_64_fu_3038_p2)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U492(
    .din0(tmp_64_fu_2968_p19),
    .din1(mul_ln160_72_fu_3047_p1),
    .dout(mul_ln160_72_fu_3047_p2)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U493(
    .din0(tmp_fu_2898_p19),
    .din1(mul_ln160_76_fu_3056_p1),
    .dout(mul_ln160_76_fu_3056_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U494(
    .din0(w2_1_load),
    .din1(w2_3_load),
    .din2(w2_5_load),
    .din3(w2_7_load),
    .din4(w2_9_load),
    .din5(w2_11_load),
    .din6(w2_13_load),
    .din7(w2_15_load),
    .def(tmp_75_fu_3065_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_75_fu_3065_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U495(
    .din0(w2_1_load_3),
    .din1(w2_3_load_3),
    .din2(w2_5_load_3),
    .din3(w2_7_load_3),
    .din4(w2_9_load_3),
    .din5(w2_11_load_3),
    .din6(w2_13_load_3),
    .din7(w2_15_load_3),
    .def(tmp_78_fu_3100_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_78_fu_3100_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U496(
    .din0(w2_1_load_5),
    .din1(w2_3_load_5),
    .din2(w2_5_load_5),
    .din3(w2_7_load_5),
    .din4(w2_9_load_5),
    .din5(w2_11_load_5),
    .din6(w2_13_load_5),
    .din7(w2_15_load_5),
    .def(tmp_80_fu_3135_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_80_fu_3135_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U497(
    .din0(w2_1_load_13),
    .din1(w2_3_load_13),
    .din2(w2_5_load_13),
    .din3(w2_7_load_13),
    .din4(w2_9_load_13),
    .din5(w2_11_load_13),
    .din6(w2_13_load_13),
    .din7(w2_15_load_13),
    .def(tmp_88_fu_3170_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter1_reg),
    .dout(tmp_88_fu_3170_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U498(
    .din0(tmp_88_fu_3170_p19),
    .din1(mul_ln160_80_fu_3205_p1),
    .dout(mul_ln160_80_fu_3205_p2)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U499(
    .din0(tmp_80_fu_3135_p19),
    .din1(mul_ln160_88_fu_3214_p1),
    .dout(mul_ln160_88_fu_3214_p2)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U500(
    .din0(tmp_75_fu_3065_p19),
    .din1(mul_ln160_92_fu_3223_p1),
    .dout(mul_ln160_92_fu_3223_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U501(
    .din0(w2_0_load_7),
    .din1(w2_2_load_7),
    .din2(w2_4_load_7),
    .din3(w2_6_load_7),
    .din4(w2_8_load_7),
    .din5(w2_10_load_7),
    .din6(w2_12_load_7),
    .din7(w2_14_load_7),
    .def(tmp_66_fu_3232_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_66_fu_3232_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U502(
    .din0(w2_0_load_9),
    .din1(w2_2_load_9),
    .din2(w2_4_load_9),
    .din3(w2_6_load_9),
    .din4(w2_8_load_9),
    .din5(w2_10_load_9),
    .din6(w2_12_load_9),
    .din7(w2_14_load_9),
    .def(tmp_68_fu_3267_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_68_fu_3267_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U503(
    .din0(w2_0_load_10),
    .din1(w2_2_load_10),
    .din2(w2_4_load_10),
    .din3(w2_6_load_10),
    .din4(w2_8_load_10),
    .din5(w2_10_load_10),
    .din6(w2_12_load_10),
    .din7(w2_14_load_10),
    .def(tmp_69_fu_3302_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_69_fu_3302_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U504(
    .din0(tmp_69_fu_3302_p19),
    .din1(mul_ln160_67_fu_3337_p1),
    .dout(mul_ln160_67_fu_3337_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U505(
    .din0(w2_1_load_7),
    .din1(w2_3_load_7),
    .din2(w2_5_load_7),
    .din3(w2_7_load_7),
    .din4(w2_9_load_7),
    .din5(w2_11_load_7),
    .din6(w2_13_load_7),
    .din7(w2_15_load_7),
    .def(tmp_82_fu_3346_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_82_fu_3346_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U506(
    .din0(w2_1_load_9),
    .din1(w2_3_load_9),
    .din2(w2_5_load_9),
    .din3(w2_7_load_9),
    .din4(w2_9_load_9),
    .din5(w2_11_load_9),
    .din6(w2_13_load_9),
    .din7(w2_15_load_9),
    .def(tmp_84_fu_3381_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_84_fu_3381_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U507(
    .din0(w2_1_load_10),
    .din1(w2_3_load_10),
    .din2(w2_5_load_10),
    .din3(w2_7_load_10),
    .din4(w2_9_load_10),
    .din5(w2_11_load_10),
    .din6(w2_13_load_10),
    .din7(w2_15_load_10),
    .def(tmp_85_fu_3416_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter2_reg),
    .dout(tmp_85_fu_3416_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U508(
    .din0(tmp_85_fu_3416_p19),
    .din1(mul_ln160_83_fu_3451_p1),
    .dout(mul_ln160_83_fu_3451_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U509(
    .din0(w2_0_load_15),
    .din1(w2_2_load_15),
    .din2(w2_4_load_15),
    .din3(w2_6_load_15),
    .din4(w2_8_load_15),
    .din5(w2_10_load_15),
    .din6(w2_12_load_15),
    .din7(w2_14_load_15),
    .def(tmp_74_fu_3460_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter3_reg),
    .dout(tmp_74_fu_3460_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U510(
    .din0(w2_1_load_15),
    .din1(w2_3_load_15),
    .din2(w2_5_load_15),
    .din3(w2_7_load_15),
    .din4(w2_9_load_15),
    .din5(w2_11_load_15),
    .din6(w2_13_load_15),
    .din7(w2_15_load_15),
    .def(tmp_90_fu_3510_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter3_reg),
    .dout(tmp_90_fu_3510_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U511(
    .din0(w2_0_load_8),
    .din1(w2_2_load_8),
    .din2(w2_4_load_8),
    .din3(w2_6_load_8),
    .din4(w2_8_load_8),
    .din5(w2_10_load_8),
    .din6(w2_12_load_8),
    .din7(w2_14_load_8),
    .def(tmp_67_fu_3560_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter4_reg),
    .dout(tmp_67_fu_3560_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U512(
    .din0(tmp_67_fu_3560_p19),
    .din1(mul_ln160_69_fu_3595_p1),
    .dout(mul_ln160_69_fu_3595_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U513(
    .din0(w2_1_load_8),
    .din1(w2_3_load_8),
    .din2(w2_5_load_8),
    .din3(w2_7_load_8),
    .din4(w2_9_load_8),
    .din5(w2_11_load_8),
    .din6(w2_13_load_8),
    .din7(w2_15_load_8),
    .def(tmp_83_fu_3616_p17),
    .sel(trunc_ln151_reg_5142_pp0_iter4_reg),
    .dout(tmp_83_fu_3616_p19)
);

transformer_top_mul_8s_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_1_1_U514(
    .din0(tmp_83_fu_3616_p19),
    .din1(mul_ln160_85_fu_3651_p1),
    .dout(mul_ln160_85_fu_3651_p2)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U515(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_73_fu_2437_p19),
    .din1(grp_fu_3819_p1),
    .din2(mul_ln160_64_fu_3038_p2),
    .ce(grp_fu_3819_ce),
    .dout(grp_fu_3819_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U516(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_65_fu_2393_p19),
    .din1(grp_fu_3827_p1),
    .din2(mul_ln160_72_fu_3047_p2),
    .ce(grp_fu_3827_ce),
    .dout(grp_fu_3827_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U517(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_61_fu_2349_p19),
    .din1(grp_fu_3835_p1),
    .din2(mul_ln160_76_fu_3056_p2),
    .ce(grp_fu_3835_ce),
    .dout(grp_fu_3835_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U518(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_89_fu_2569_p19),
    .din1(grp_fu_3843_p1),
    .din2(mul_ln160_80_fu_3205_p2),
    .ce(grp_fu_3843_ce),
    .dout(grp_fu_3843_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U519(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_81_fu_2525_p19),
    .din1(grp_fu_3851_p1),
    .din2(mul_ln160_88_fu_3214_p2),
    .ce(grp_fu_3851_ce),
    .dout(grp_fu_3851_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U520(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_77_fu_2481_p19),
    .din1(grp_fu_3859_p1),
    .din2(mul_ln160_92_fu_3223_p2),
    .ce(grp_fu_3859_ce),
    .dout(grp_fu_3859_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U521(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_71_fu_2723_p19),
    .din1(grp_fu_3867_p1),
    .din2(grp_fu_3819_p3),
    .ce(grp_fu_3867_ce),
    .dout(grp_fu_3867_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U522(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_70_fu_2688_p19),
    .din1(grp_fu_3875_p1),
    .din2(mul_ln160_67_fu_3337_p2),
    .ce(grp_fu_3875_ce),
    .dout(grp_fu_3875_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U523(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_63_fu_2653_p19),
    .din1(grp_fu_3883_p1),
    .din2(grp_fu_3827_p3),
    .ce(grp_fu_3883_ce),
    .dout(grp_fu_3883_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U524(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_fu_2618_p19),
    .din1(grp_fu_3890_p1),
    .din2(grp_fu_3835_p3),
    .ce(grp_fu_3890_ce),
    .dout(grp_fu_3890_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U525(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_87_fu_2863_p19),
    .din1(grp_fu_3898_p1),
    .din2(grp_fu_3843_p3),
    .ce(grp_fu_3898_ce),
    .dout(grp_fu_3898_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U526(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_86_fu_2828_p19),
    .din1(grp_fu_3906_p1),
    .din2(mul_ln160_83_fu_3451_p2),
    .ce(grp_fu_3906_ce),
    .dout(grp_fu_3906_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U527(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_79_fu_2793_p19),
    .din1(grp_fu_3914_p1),
    .din2(grp_fu_3851_p3),
    .ce(grp_fu_3914_ce),
    .dout(grp_fu_3914_p3)
);

transformer_top_mac_muladd_8s_8s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_17s_17_4_1_U528(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_76_fu_2758_p19),
    .din1(grp_fu_3921_p1),
    .din2(grp_fu_3859_p3),
    .ce(grp_fu_3921_ce),
    .dout(grp_fu_3921_p3)
);

transformer_top_mac_muladd_8s_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_17s_18_4_1_U529(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_62_fu_2933_p19),
    .din1(grp_fu_3929_p1),
    .din2(grp_fu_3890_p3),
    .ce(grp_fu_3929_ce),
    .dout(grp_fu_3929_p3)
);

transformer_top_mac_muladd_8s_8s_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_8s_17s_18_4_1_U530(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_78_fu_3100_p19),
    .din1(grp_fu_3937_p1),
    .din2(grp_fu_3921_p3),
    .ce(grp_fu_3937_ce),
    .dout(grp_fu_3937_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U531(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_68_fu_3267_p19),
    .din1(grp_fu_3945_p1),
    .din2(mul_ln160_69_fu_3595_p2),
    .ce(grp_fu_3945_ce),
    .dout(grp_fu_3945_p3)
);

transformer_top_mac_muladd_8s_8s_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_8s_8s_18s_19_4_1_U532(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_66_fu_3232_p19),
    .din1(grp_fu_3953_p1),
    .din2(add_ln160_63_fu_3607_p2),
    .ce(grp_fu_3953_ce),
    .dout(grp_fu_3953_p3)
);

transformer_top_mac_muladd_8s_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_8s_16s_17_4_1_U533(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_84_fu_3381_p19),
    .din1(grp_fu_3961_p1),
    .din2(mul_ln160_85_fu_3651_p2),
    .ce(grp_fu_3961_ce),
    .dout(grp_fu_3961_p3)
);

transformer_top_mac_muladd_8s_8s_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_8s_8s_18s_19_4_1_U534(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_82_fu_3346_p19),
    .din1(grp_fu_3969_p1),
    .din2(add_ln160_78_fu_3663_p2),
    .ce(grp_fu_3969_ce),
    .dout(grp_fu_3969_p3)
);

transformer_top_mac_muladd_8s_8s_19s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_8s_8s_19s_20_4_1_U535(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_74_fu_3460_p19),
    .din1(grp_fu_3977_p1),
    .din2(add_ln160_71_fu_3683_p2),
    .ce(grp_fu_3977_ce),
    .dout(grp_fu_3977_p3)
);

transformer_top_mac_muladd_8s_8s_19s_20_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 20 ))
mac_muladd_8s_8s_19s_20_4_1_U536(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_90_fu_3510_p19),
    .din1(grp_fu_3986_p1),
    .din2(add_ln160_86_fu_3704_p2),
    .ce(grp_fu_3986_ce),
    .dout(grp_fu_3986_p3)
);

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln151_fu_2333_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_618 <= add_ln151_fu_2339_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_618 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln160_62_reg_5352 <= grp_fu_3883_p3;
        add_ln160_77_reg_5372 <= grp_fu_3914_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln160_70_reg_5357 <= add_ln160_70_fu_3504_p2;
        add_ln160_70_reg_5357_pp0_iter5_reg <= add_ln160_70_reg_5357;
        add_ln160_85_reg_5377 <= add_ln160_85_fu_3554_p2;
        add_ln160_85_reg_5377_pp0_iter5_reg <= add_ln160_85_reg_5377;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln164_3_reg_5422 <= icmp_ln164_3_fu_3788_p2;
        icmp_ln164_reg_5412 <= icmp_ln164_fu_3746_p2;
        trunc_ln151_reg_5142_pp0_iter2_reg <= trunc_ln151_reg_5142_pp0_iter1_reg;
        trunc_ln151_reg_5142_pp0_iter3_reg <= trunc_ln151_reg_5142_pp0_iter2_reg;
        trunc_ln151_reg_5142_pp0_iter4_reg <= trunc_ln151_reg_5142_pp0_iter3_reg;
        trunc_ln165_4_reg_5427 <= trunc_ln165_4_fu_3794_p1;
        trunc_ln165_reg_5417 <= trunc_ln165_fu_3752_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        sext_ln160_171_cast_reg_5042 <= sext_ln160_171_cast_fu_2261_p1;
        sext_ln160_173_cast_reg_5060 <= sext_ln160_173_cast_fu_2273_p1;
        sext_ln160_174_cast_reg_5066 <= sext_ln160_174_cast_fu_2277_p1;
        sext_ln160_175_cast_reg_5072 <= sext_ln160_175_cast_fu_2281_p1;
        sext_ln160_177_cast_reg_5084 <= sext_ln160_177_cast_fu_2289_p1;
        sext_ln160_178_cast_reg_5090 <= sext_ln160_178_cast_fu_2293_p1;
        sext_ln160_179_cast_reg_5096 <= sext_ln160_179_cast_fu_2297_p1;
        sext_ln160_180_cast_reg_5102 <= sext_ln160_180_cast_fu_2301_p1;
        sext_ln160_181_cast_reg_5108 <= sext_ln160_181_cast_fu_2305_p1;
        sext_ln160_182_cast_reg_5114 <= sext_ln160_182_cast_fu_2309_p1;
        sext_ln160_183_cast_reg_5120 <= sext_ln160_183_cast_fu_2313_p1;
        sext_ln160_185_cast_reg_5132 <= sext_ln160_185_cast_fu_2321_p1;
        sext_ln160_cast_reg_5048 <= sext_ln160_cast_fu_2265_p1;
        trunc_ln151_reg_5142 <= trunc_ln151_fu_2345_p1;
        trunc_ln151_reg_5142_pp0_iter1_reg <= trunc_ln151_reg_5142;
    end
end

always @ (*) begin
    if (((icmp_ln151_fu_2333_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_4 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_4 = j_fu_618;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3819_ce = 1'b1;
    end else begin
        grp_fu_3819_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3827_ce = 1'b1;
    end else begin
        grp_fu_3827_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3835_ce = 1'b1;
    end else begin
        grp_fu_3835_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3843_ce = 1'b1;
    end else begin
        grp_fu_3843_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3851_ce = 1'b1;
    end else begin
        grp_fu_3851_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3859_ce = 1'b1;
    end else begin
        grp_fu_3859_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3867_ce = 1'b1;
    end else begin
        grp_fu_3867_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3875_ce = 1'b1;
    end else begin
        grp_fu_3875_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3883_ce = 1'b1;
    end else begin
        grp_fu_3883_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3890_ce = 1'b1;
    end else begin
        grp_fu_3890_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3898_ce = 1'b1;
    end else begin
        grp_fu_3898_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3906_ce = 1'b1;
    end else begin
        grp_fu_3906_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3914_ce = 1'b1;
    end else begin
        grp_fu_3914_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3921_ce = 1'b1;
    end else begin
        grp_fu_3921_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3929_ce = 1'b1;
    end else begin
        grp_fu_3929_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3937_ce = 1'b1;
    end else begin
        grp_fu_3937_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3945_ce = 1'b1;
    end else begin
        grp_fu_3945_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3953_ce = 1'b1;
    end else begin
        grp_fu_3953_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3961_ce = 1'b1;
    end else begin
        grp_fu_3961_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3969_ce = 1'b1;
    end else begin
        grp_fu_3969_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3977_ce = 1'b1;
    end else begin
        grp_fu_3977_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_fu_3986_ce = 1'b1;
    end else begin
        grp_fu_3986_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        s_gemm2_out_blk_n = s_gemm2_out_full_n;
    end else begin
        s_gemm2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        s_gemm2_out_write = 1'b1;
    end else begin
        s_gemm2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln151_fu_2339_p2 = (ap_sig_allocacmp_j_4 + 4'd1);

assign add_ln160_63_fu_3607_p2 = ($signed(sext_ln160_238_fu_3604_p1) + $signed(grp_fu_3929_p3));

assign add_ln160_66_fu_3675_p2 = ($signed(sext_ln160_239_fu_3672_p1) + $signed(grp_fu_3953_p3));

assign add_ln160_70_fu_3504_p2 = ($signed(sext_ln160_241_fu_3501_p1) + $signed(sext_ln160_240_fu_3498_p1));

assign add_ln160_71_fu_3683_p2 = ($signed(sext_ln160_242_fu_3680_p1) + $signed(add_ln160_66_fu_3675_p2));

assign add_ln160_78_fu_3663_p2 = ($signed(sext_ln160_261_fu_3660_p1) + $signed(grp_fu_3937_p3));

assign add_ln160_81_fu_3696_p2 = ($signed(sext_ln160_262_fu_3693_p1) + $signed(grp_fu_3969_p3));

assign add_ln160_85_fu_3554_p2 = ($signed(sext_ln160_264_fu_3551_p1) + $signed(sext_ln160_263_fu_3548_p1));

assign add_ln160_86_fu_3704_p2 = ($signed(sext_ln160_265_fu_3701_p1) + $signed(add_ln160_81_fu_3696_p2));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((s_gemm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((s_gemm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((s_gemm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((s_gemm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign elems_22_fu_3804_p3 = ((icmp_ln164_3_reg_5422[0:0] == 1'b1) ? 8'd128 : trunc_ln165_4_reg_5427);

assign elems_fu_3798_p3 = ((icmp_ln164_reg_5412[0:0] == 1'b1) ? 8'd128 : trunc_ln165_reg_5417);

assign grp_fu_3819_p1 = sext_ln160_184_cast_fu_2317_p1;

assign grp_fu_3827_p1 = sext_ln160_176_cast_fu_2285_p1;

assign grp_fu_3835_p1 = sext_ln160_172_cast_fu_2269_p1;

assign grp_fu_3843_p1 = sext_ln160_184_cast_fu_2317_p1;

assign grp_fu_3851_p1 = sext_ln160_176_cast_fu_2285_p1;

assign grp_fu_3859_p1 = sext_ln160_172_cast_fu_2269_p1;

assign grp_fu_3867_p1 = sext_ln160_182_cast_reg_5114;

assign grp_fu_3875_p1 = sext_ln160_181_cast_reg_5108;

assign grp_fu_3883_p1 = sext_ln160_174_cast_reg_5066;

assign grp_fu_3890_p1 = sext_ln160_171_cast_reg_5042;

assign grp_fu_3898_p1 = sext_ln160_182_cast_reg_5114;

assign grp_fu_3906_p1 = sext_ln160_181_cast_reg_5108;

assign grp_fu_3914_p1 = sext_ln160_174_cast_reg_5066;

assign grp_fu_3921_p1 = sext_ln160_171_cast_reg_5042;

assign grp_fu_3929_p1 = sext_ln160_173_cast_reg_5060;

assign grp_fu_3937_p1 = sext_ln160_173_cast_reg_5060;

assign grp_fu_3945_p1 = sext_ln160_179_cast_reg_5096;

assign grp_fu_3953_p1 = sext_ln160_177_cast_reg_5084;

assign grp_fu_3961_p1 = sext_ln160_179_cast_reg_5096;

assign grp_fu_3969_p1 = sext_ln160_177_cast_reg_5084;

assign grp_fu_3977_p1 = sext_ln160_185_cast_reg_5132;

assign grp_fu_3986_p1 = sext_ln160_185_cast_reg_5132;

assign icmp_ln151_fu_2333_p2 = ((ap_sig_allocacmp_j_4 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln163_4_fu_3774_p2 = (($signed(tmp_92_fu_3765_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln163_fu_3732_p2 = (($signed(tmp_91_fu_3723_p4) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln164_3_fu_3788_p2 = (($signed(requant_11_fu_3780_p3) < $signed(12'd3968)) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_3746_p2 = (($signed(requant_10_fu_3738_p3) < $signed(12'd3968)) ? 1'b1 : 1'b0);

assign mul_ln160_64_fu_3038_p1 = sext_ln160_183_cast_reg_5120;

assign mul_ln160_67_fu_3337_p1 = sext_ln160_180_cast_reg_5102;

assign mul_ln160_69_fu_3595_p1 = sext_ln160_178_cast_reg_5090;

assign mul_ln160_72_fu_3047_p1 = sext_ln160_175_cast_reg_5072;

assign mul_ln160_76_fu_3056_p1 = sext_ln160_cast_reg_5048;

assign mul_ln160_80_fu_3205_p1 = sext_ln160_183_cast_reg_5120;

assign mul_ln160_83_fu_3451_p1 = sext_ln160_180_cast_reg_5102;

assign mul_ln160_85_fu_3651_p1 = sext_ln160_178_cast_reg_5090;

assign mul_ln160_88_fu_3214_p1 = sext_ln160_175_cast_reg_5072;

assign mul_ln160_92_fu_3223_p1 = sext_ln160_cast_reg_5048;

assign requant_10_fu_3738_p3 = ((icmp_ln163_fu_3732_p2[0:0] == 1'b1) ? 12'd127 : requant_fu_3714_p4);

assign requant_11_fu_3780_p3 = ((icmp_ln163_4_fu_3774_p2[0:0] == 1'b1) ? 12'd127 : requant_8_fu_3756_p4);

assign requant_8_fu_3756_p4 = {{grp_fu_3986_p3[19:8]}};

assign requant_fu_3714_p4 = {{grp_fu_3977_p3[19:8]}};

assign s_gemm2_out_din = {{elems_22_fu_3804_p3}, {elems_fu_3798_p3}};

assign sext_ln160_171_cast_fu_2261_p1 = $signed(sext_ln160_171);

assign sext_ln160_172_cast_fu_2269_p1 = $signed(sext_ln160_172);

assign sext_ln160_173_cast_fu_2273_p1 = $signed(sext_ln160_173);

assign sext_ln160_174_cast_fu_2277_p1 = $signed(sext_ln160_174);

assign sext_ln160_175_cast_fu_2281_p1 = $signed(sext_ln160_175);

assign sext_ln160_176_cast_fu_2285_p1 = $signed(sext_ln160_176);

assign sext_ln160_177_cast_fu_2289_p1 = $signed(sext_ln160_177);

assign sext_ln160_178_cast_fu_2293_p1 = $signed(sext_ln160_178);

assign sext_ln160_179_cast_fu_2297_p1 = $signed(sext_ln160_179);

assign sext_ln160_180_cast_fu_2301_p1 = $signed(sext_ln160_180);

assign sext_ln160_181_cast_fu_2305_p1 = $signed(sext_ln160_181);

assign sext_ln160_182_cast_fu_2309_p1 = $signed(sext_ln160_182);

assign sext_ln160_183_cast_fu_2313_p1 = $signed(sext_ln160_183);

assign sext_ln160_184_cast_fu_2317_p1 = $signed(sext_ln160_184);

assign sext_ln160_185_cast_fu_2321_p1 = $signed(sext_ln160_185);

assign sext_ln160_238_fu_3604_p1 = add_ln160_62_reg_5352;

assign sext_ln160_239_fu_3672_p1 = grp_fu_3945_p3;

assign sext_ln160_240_fu_3498_p1 = grp_fu_3875_p3;

assign sext_ln160_241_fu_3501_p1 = grp_fu_3867_p3;

assign sext_ln160_242_fu_3680_p1 = $signed(add_ln160_70_reg_5357_pp0_iter5_reg);

assign sext_ln160_261_fu_3660_p1 = add_ln160_77_reg_5372;

assign sext_ln160_262_fu_3693_p1 = grp_fu_3961_p3;

assign sext_ln160_263_fu_3548_p1 = grp_fu_3906_p3;

assign sext_ln160_264_fu_3551_p1 = grp_fu_3898_p3;

assign sext_ln160_265_fu_3701_p1 = $signed(add_ln160_85_reg_5377_pp0_iter5_reg);

assign sext_ln160_cast_fu_2265_p1 = $signed(sext_ln160);

assign tmp_61_fu_2349_p17 = 'bx;

assign tmp_62_fu_2933_p17 = 'bx;

assign tmp_63_fu_2653_p17 = 'bx;

assign tmp_64_fu_2968_p17 = 'bx;

assign tmp_65_fu_2393_p17 = 'bx;

assign tmp_66_fu_3232_p17 = 'bx;

assign tmp_67_fu_3560_p17 = 'bx;

assign tmp_68_fu_3267_p17 = 'bx;

assign tmp_69_fu_3302_p17 = 'bx;

assign tmp_70_fu_2688_p17 = 'bx;

assign tmp_71_fu_2723_p17 = 'bx;

assign tmp_72_fu_3003_p17 = 'bx;

assign tmp_73_fu_2437_p17 = 'bx;

assign tmp_74_fu_3460_p17 = 'bx;

assign tmp_75_fu_3065_p17 = 'bx;

assign tmp_76_fu_2758_p17 = 'bx;

assign tmp_77_fu_2481_p17 = 'bx;

assign tmp_78_fu_3100_p17 = 'bx;

assign tmp_79_fu_2793_p17 = 'bx;

assign tmp_80_fu_3135_p17 = 'bx;

assign tmp_81_fu_2525_p17 = 'bx;

assign tmp_82_fu_3346_p17 = 'bx;

assign tmp_83_fu_3616_p17 = 'bx;

assign tmp_84_fu_3381_p17 = 'bx;

assign tmp_85_fu_3416_p17 = 'bx;

assign tmp_86_fu_2828_p17 = 'bx;

assign tmp_87_fu_2863_p17 = 'bx;

assign tmp_88_fu_3170_p17 = 'bx;

assign tmp_89_fu_2569_p17 = 'bx;

assign tmp_90_fu_3510_p17 = 'bx;

assign tmp_91_fu_3723_p4 = {{grp_fu_3977_p3[19:15]}};

assign tmp_92_fu_3765_p4 = {{grp_fu_3986_p3[19:15]}};

assign tmp_fu_2898_p17 = 'bx;

assign tmp_s_fu_2618_p17 = 'bx;

assign trunc_ln151_fu_2345_p1 = ap_sig_allocacmp_j_4[2:0];

assign trunc_ln165_4_fu_3794_p1 = requant_11_fu_3780_p3[7:0];

assign trunc_ln165_fu_3752_p1 = requant_10_fu_3738_p3[7:0];

endmodule //transformer_top_gemm_5_Pipeline_VITIS_LOOP_151_3
