// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_stateful_norm_Pipeline_VITIS_LOOP_109_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_norm2_out_din,
        s_norm2_out_full_n,
        s_norm2_out_write,
        s_norm2_out_num_data_valid,
        s_norm2_out_fifo_cap,
        buf_reload,
        buf_36_reload,
        buf_38_reload,
        buf_40_reload,
        buf_42_reload,
        buf_44_reload,
        buf_46_reload,
        buf_48_reload,
        sext_ln100,
        buf_35_reload,
        buf_37_reload,
        buf_39_reload,
        buf_41_reload,
        buf_43_reload,
        buf_45_reload,
        buf_47_reload,
        buf_49_reload
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] s_norm2_out_din;
input   s_norm2_out_full_n;
output   s_norm2_out_write;
input  [31:0] s_norm2_out_num_data_valid;
input  [31:0] s_norm2_out_fifo_cap;
input  [7:0] buf_reload;
input  [7:0] buf_36_reload;
input  [7:0] buf_38_reload;
input  [7:0] buf_40_reload;
input  [7:0] buf_42_reload;
input  [7:0] buf_44_reload;
input  [7:0] buf_46_reload;
input  [7:0] buf_48_reload;
input  [7:0] sext_ln100;
input  [7:0] buf_35_reload;
input  [7:0] buf_37_reload;
input  [7:0] buf_39_reload;
input  [7:0] buf_41_reload;
input  [7:0] buf_43_reload;
input  [7:0] buf_45_reload;
input  [7:0] buf_47_reload;
input  [7:0] buf_49_reload;

reg ap_idle;
reg s_norm2_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_221_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_norm2_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [6:0] tmp_reg_387;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] tmp_2_reg_392;
reg   [3:0] i_3_fu_96;
wire   [3:0] add_ln109_fu_227_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] x_fu_237_p17;
wire   [2:0] trunc_ln109_fu_233_p1;
wire   [7:0] x_fu_237_p19;
wire  signed [8:0] sext_ln115_fu_277_p1;
wire  signed [8:0] sext_ln100_cast_fu_209_p1;
wire   [8:0] diff_fu_281_p2;
wire   [7:0] x_2_fu_297_p17;
wire   [7:0] x_2_fu_297_p19;
wire  signed [8:0] sext_ln115_1_fu_337_p1;
wire   [8:0] diff_60_fu_341_p2;
wire  signed [7:0] elems_fu_362_p1;
wire   [14:0] tmp_3_fu_365_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] x_fu_237_p1;
wire   [2:0] x_fu_237_p3;
wire   [2:0] x_fu_237_p5;
wire   [2:0] x_fu_237_p7;
wire  signed [2:0] x_fu_237_p9;
wire  signed [2:0] x_fu_237_p11;
wire  signed [2:0] x_fu_237_p13;
wire  signed [2:0] x_fu_237_p15;
wire   [2:0] x_2_fu_297_p1;
wire   [2:0] x_2_fu_297_p3;
wire   [2:0] x_2_fu_297_p5;
wire   [2:0] x_2_fu_297_p7;
wire  signed [2:0] x_2_fu_297_p9;
wire  signed [2:0] x_2_fu_297_p11;
wire  signed [2:0] x_2_fu_297_p13;
wire  signed [2:0] x_2_fu_297_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_3_fu_96 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U840(
    .din0(buf_reload),
    .din1(buf_36_reload),
    .din2(buf_38_reload),
    .din3(buf_40_reload),
    .din4(buf_42_reload),
    .din5(buf_44_reload),
    .din6(buf_46_reload),
    .din7(buf_48_reload),
    .def(x_fu_237_p17),
    .sel(trunc_ln109_fu_233_p1),
    .dout(x_fu_237_p19)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 8 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_17_3_8_1_1_U841(
    .din0(buf_35_reload),
    .din1(buf_37_reload),
    .din2(buf_39_reload),
    .din3(buf_41_reload),
    .din4(buf_43_reload),
    .din5(buf_45_reload),
    .din6(buf_47_reload),
    .din7(buf_49_reload),
    .def(x_2_fu_297_p17),
    .sel(trunc_ln109_fu_233_p1),
    .dout(x_2_fu_297_p19)
);

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_221_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_3_fu_96 <= add_ln109_fu_227_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_3_fu_96 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_reg_392 <= {{diff_60_fu_341_p2[8:2]}};
        tmp_reg_387 <= {{diff_fu_281_p2[8:2]}};
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_221_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_3_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_norm2_out_blk_n = s_norm2_out_full_n;
    end else begin
        s_norm2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_norm2_out_write = 1'b1;
    end else begin
        s_norm2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_227_p2 = (ap_sig_allocacmp_i + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((s_norm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((s_norm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((s_norm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((s_norm2_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign diff_60_fu_341_p2 = ($signed(sext_ln115_1_fu_337_p1) - $signed(sext_ln100_cast_fu_209_p1));

assign diff_fu_281_p2 = ($signed(sext_ln115_fu_277_p1) - $signed(sext_ln100_cast_fu_209_p1));

assign elems_fu_362_p1 = $signed(tmp_reg_387);

assign icmp_ln109_fu_221_p2 = ((ap_sig_allocacmp_i == 4'd8) ? 1'b1 : 1'b0);

assign s_norm2_out_din = $signed(tmp_3_fu_365_p3);

assign sext_ln100_cast_fu_209_p1 = $signed(sext_ln100);

assign sext_ln115_1_fu_337_p1 = $signed(x_2_fu_297_p19);

assign sext_ln115_fu_277_p1 = $signed(x_fu_237_p19);

assign tmp_3_fu_365_p3 = {{tmp_2_reg_392}, {elems_fu_362_p1}};

assign trunc_ln109_fu_233_p1 = ap_sig_allocacmp_i[2:0];

assign x_2_fu_297_p17 = 'bx;

assign x_fu_237_p17 = 'bx;

endmodule //transformer_top_stateful_norm_Pipeline_VITIS_LOOP_109_3
