// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_stateful_softmax (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_gemm1_out_dout,
        s_gemm1_out_empty_n,
        s_gemm1_out_read,
        s_gemm1_out_num_data_valid,
        s_gemm1_out_fifo_cap,
        s_softmax_out_din,
        s_softmax_out_full_n,
        s_softmax_out_write,
        s_softmax_out_num_data_valid,
        s_softmax_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] s_gemm1_out_dout;
input   s_gemm1_out_empty_n;
output   s_gemm1_out_read;
input  [2:0] s_gemm1_out_num_data_valid;
input  [2:0] s_gemm1_out_fifo_cap;
output  [15:0] s_softmax_out_din;
input   s_softmax_out_full_n;
output   s_softmax_out_write;
input  [31:0] s_softmax_out_num_data_valid;
input  [31:0] s_softmax_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] EXP_LUT_q0;
wire   [8:0] EXP_LUT_q1;
wire   [8:0] EXP_LUT_q2;
wire   [8:0] EXP_LUT_q3;
wire   [8:0] EXP_LUT_q4;
wire   [8:0] EXP_LUT_q5;
wire  signed [8:0] sext_ln207_fu_343_p1;
reg  signed [8:0] sext_ln207_reg_1731;
wire    ap_CS_fsm_state3;
wire   [3:0] idx_fu_403_p3;
reg   [3:0] idx_reg_1745;
wire   [3:0] idx_16_fu_467_p3;
reg   [3:0] idx_16_reg_1750;
wire   [3:0] idx_17_fu_531_p3;
reg   [3:0] idx_17_reg_1755;
wire   [3:0] idx_19_fu_595_p3;
reg   [3:0] idx_19_reg_1760;
wire   [3:0] idx_20_fu_659_p3;
reg   [3:0] idx_20_reg_1765;
wire   [3:0] idx_21_fu_723_p3;
reg   [3:0] idx_21_reg_1770;
wire    ap_CS_fsm_state4;
wire   [3:0] idx_18_fu_828_p3;
reg   [3:0] idx_18_reg_1790;
wire   [3:0] idx_25_fu_903_p3;
reg   [3:0] idx_25_reg_1810;
wire   [3:0] idx_26_fu_966_p3;
reg   [3:0] idx_26_reg_1815;
wire   [3:0] idx_27_fu_1029_p3;
reg   [3:0] idx_27_reg_1820;
wire   [3:0] idx_28_fu_1092_p3;
reg   [3:0] idx_28_reg_1825;
wire   [3:0] idx_29_fu_1155_p3;
reg   [3:0] idx_29_reg_1830;
reg   [8:0] exp_val_reg_1835;
wire    ap_CS_fsm_state5;
reg   [8:0] exp_val_15_reg_1841;
reg   [8:0] exp_val_16_reg_1847;
reg   [8:0] exp_val_18_reg_1858;
reg   [8:0] exp_val_19_reg_1864;
reg   [8:0] exp_val_20_reg_1870;
wire   [3:0] idx_22_fu_1234_p3;
reg   [3:0] idx_22_reg_1876;
wire   [3:0] idx_23_fu_1297_p3;
reg   [3:0] idx_23_reg_1881;
wire   [3:0] idx_24_fu_1360_p3;
reg   [3:0] idx_24_reg_1886;
wire   [3:0] idx_15_fu_1443_p3;
reg   [3:0] idx_15_reg_1916;
reg   [8:0] exp_val_17_reg_1921;
wire    ap_CS_fsm_state6;
reg   [8:0] exp_val_24_reg_1941;
reg   [8:0] exp_val_25_reg_1947;
reg   [8:0] exp_val_26_reg_1953;
reg   [8:0] exp_val_27_reg_1958;
reg   [8:0] exp_val_28_reg_1963;
wire   [10:0] add_ln213_5_fu_1523_p2;
reg   [10:0] add_ln213_5_reg_1968;
wire   [9:0] add_ln213_11_fu_1547_p2;
reg   [9:0] add_ln213_11_reg_1973;
reg   [8:0] exp_val_21_reg_1978;
wire    ap_CS_fsm_state7;
reg   [8:0] exp_val_22_reg_1983;
reg   [8:0] exp_val_23_reg_1988;
wire   [11:0] add_ln213_13_fu_1623_p2;
reg   [11:0] add_ln213_13_reg_1998;
reg   [8:0] exp_val_29_reg_2003;
wire    ap_CS_fsm_state8;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_done;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_idle;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_ready;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_s_gemm1_out_read;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out1;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out1_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out2;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out2_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out3;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out3_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out4;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out4_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out5;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out5_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out6;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out6_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out7;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out7_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out8;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out8_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out9;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out9_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out10;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out10_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out11;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out11_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out12;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out12_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out13;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out13_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out14;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out14_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out15;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out15_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_max_val_out;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_max_val_out_ap_vld;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_idle;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_ready;
wire   [15:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_din;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_write;
reg    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg;
reg    ap_block_state1_ignore_call19;
wire    ap_CS_fsm_state2;
reg    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln211_fu_761_p1;
wire   [63:0] zext_ln211_1_fu_765_p1;
wire   [63:0] zext_ln211_2_fu_769_p1;
wire   [63:0] zext_ln211_4_fu_836_p1;
wire   [63:0] zext_ln211_5_fu_840_p1;
wire   [63:0] zext_ln211_6_fu_844_p1;
wire   [63:0] zext_ln211_3_fu_1175_p1;
wire   [63:0] zext_ln211_10_fu_1368_p1;
wire   [63:0] zext_ln211_11_fu_1372_p1;
wire   [63:0] zext_ln211_12_fu_1376_p1;
wire   [63:0] zext_ln211_13_fu_1380_p1;
wire   [63:0] zext_ln211_14_fu_1384_p1;
wire   [63:0] zext_ln211_7_fu_1451_p1;
wire   [63:0] zext_ln211_8_fu_1455_p1;
wire   [63:0] zext_ln211_9_fu_1459_p1;
wire   [63:0] zext_ln211_15_fu_1553_p1;
reg    EXP_LUT_ce5_local;
reg   [3:0] EXP_LUT_address5_local;
reg    EXP_LUT_ce4_local;
reg   [3:0] EXP_LUT_address4_local;
reg    EXP_LUT_ce3_local;
reg   [3:0] EXP_LUT_address3_local;
reg    EXP_LUT_ce2_local;
reg   [3:0] EXP_LUT_address2_local;
reg    EXP_LUT_ce1_local;
reg   [3:0] EXP_LUT_address1_local;
reg    EXP_LUT_ce0_local;
reg   [3:0] EXP_LUT_address0_local;
wire  signed [8:0] sext_ln207_1_fu_347_p1;
wire   [8:0] diff_fu_351_p2;
wire   [0:0] icmp_ln208_fu_357_p2;
wire   [8:0] diff_1_fu_363_p3;
wire   [0:0] bit_sel2_fu_377_p3;
wire   [0:0] xor_ln210_15_fu_385_p2;
wire   [2:0] trunc_ln210_fu_391_p1;
wire   [0:0] icmp_ln209_fu_371_p2;
wire   [3:0] xor_ln_fu_395_p3;
wire  signed [8:0] sext_ln207_2_fu_411_p1;
wire   [8:0] diff_32_fu_415_p2;
wire   [0:0] icmp_ln208_1_fu_421_p2;
wire   [8:0] diff_33_fu_427_p3;
wire   [0:0] bit_sel3_fu_441_p3;
wire   [0:0] xor_ln210_fu_449_p2;
wire   [2:0] trunc_ln210_1_fu_455_p1;
wire   [0:0] icmp_ln209_1_fu_435_p2;
wire   [3:0] xor_ln210_1_fu_459_p3;
wire  signed [8:0] sext_ln207_3_fu_475_p1;
wire   [8:0] diff_34_fu_479_p2;
wire   [0:0] icmp_ln208_2_fu_485_p2;
wire   [8:0] diff_35_fu_491_p3;
wire   [0:0] bit_sel5_fu_505_p3;
wire   [0:0] xor_ln210_16_fu_513_p2;
wire   [2:0] trunc_ln210_2_fu_519_p1;
wire   [0:0] icmp_ln209_2_fu_499_p2;
wire   [3:0] xor_ln210_2_fu_523_p3;
wire  signed [8:0] sext_ln207_5_fu_539_p1;
wire   [8:0] diff_38_fu_543_p2;
wire   [0:0] icmp_ln208_4_fu_549_p2;
wire   [8:0] diff_39_fu_555_p3;
wire   [0:0] bit_sel8_fu_569_p3;
wire   [0:0] xor_ln210_18_fu_577_p2;
wire   [2:0] trunc_ln210_4_fu_583_p1;
wire   [0:0] icmp_ln209_4_fu_563_p2;
wire   [3:0] xor_ln210_4_fu_587_p3;
wire  signed [8:0] sext_ln207_6_fu_603_p1;
wire   [8:0] diff_40_fu_607_p2;
wire   [0:0] icmp_ln208_5_fu_613_p2;
wire   [8:0] diff_41_fu_619_p3;
wire   [0:0] bit_sel9_fu_633_p3;
wire   [0:0] xor_ln210_19_fu_641_p2;
wire   [2:0] trunc_ln210_5_fu_647_p1;
wire   [0:0] icmp_ln209_5_fu_627_p2;
wire   [3:0] xor_ln210_5_fu_651_p3;
wire  signed [8:0] sext_ln207_7_fu_667_p1;
wire   [8:0] diff_42_fu_671_p2;
wire   [0:0] icmp_ln208_6_fu_677_p2;
wire   [8:0] diff_43_fu_683_p3;
wire   [0:0] bit_sel11_fu_697_p3;
wire   [0:0] xor_ln210_20_fu_705_p2;
wire   [2:0] trunc_ln210_6_fu_711_p1;
wire   [0:0] icmp_ln209_6_fu_691_p2;
wire   [3:0] xor_ln210_6_fu_715_p3;
wire  signed [8:0] sext_ln207_4_fu_773_p1;
wire   [8:0] diff_36_fu_777_p2;
wire   [0:0] icmp_ln208_3_fu_782_p2;
wire   [8:0] diff_37_fu_788_p3;
wire   [0:0] bit_sel6_fu_802_p3;
wire   [0:0] xor_ln210_17_fu_810_p2;
wire   [2:0] trunc_ln210_3_fu_816_p1;
wire   [0:0] icmp_ln209_3_fu_796_p2;
wire   [3:0] xor_ln210_3_fu_820_p3;
wire  signed [8:0] sext_ln207_11_fu_848_p1;
wire   [8:0] diff_50_fu_852_p2;
wire   [0:0] icmp_ln208_10_fu_857_p2;
wire   [8:0] diff_51_fu_863_p3;
wire   [0:0] bit_sel13_fu_877_p3;
wire   [0:0] xor_ln210_24_fu_885_p2;
wire   [2:0] trunc_ln210_10_fu_891_p1;
wire   [0:0] icmp_ln209_10_fu_871_p2;
wire   [3:0] xor_ln210_s_fu_895_p3;
wire  signed [8:0] sext_ln207_12_fu_911_p1;
wire   [8:0] diff_52_fu_915_p2;
wire   [0:0] icmp_ln208_11_fu_920_p2;
wire   [8:0] diff_53_fu_926_p3;
wire   [0:0] bit_sel10_fu_940_p3;
wire   [0:0] xor_ln210_25_fu_948_p2;
wire   [2:0] trunc_ln210_11_fu_954_p1;
wire   [0:0] icmp_ln209_11_fu_934_p2;
wire   [3:0] xor_ln210_10_fu_958_p3;
wire  signed [8:0] sext_ln207_13_fu_974_p1;
wire   [8:0] diff_54_fu_978_p2;
wire   [0:0] icmp_ln208_12_fu_983_p2;
wire   [8:0] diff_55_fu_989_p3;
wire   [0:0] bit_sel7_fu_1003_p3;
wire   [0:0] xor_ln210_26_fu_1011_p2;
wire   [2:0] trunc_ln210_12_fu_1017_p1;
wire   [0:0] icmp_ln209_12_fu_997_p2;
wire   [3:0] xor_ln210_11_fu_1021_p3;
wire  signed [8:0] sext_ln207_14_fu_1037_p1;
wire   [8:0] diff_56_fu_1041_p2;
wire   [0:0] icmp_ln208_13_fu_1046_p2;
wire   [8:0] diff_57_fu_1052_p3;
wire   [0:0] bit_sel4_fu_1066_p3;
wire   [0:0] xor_ln210_27_fu_1074_p2;
wire   [2:0] trunc_ln210_13_fu_1080_p1;
wire   [0:0] icmp_ln209_13_fu_1060_p2;
wire   [3:0] xor_ln210_12_fu_1084_p3;
wire  signed [8:0] sext_ln207_15_fu_1100_p1;
wire   [8:0] diff_58_fu_1104_p2;
wire   [0:0] icmp_ln208_14_fu_1109_p2;
wire   [8:0] diff_59_fu_1115_p3;
wire   [0:0] bit_sel1_fu_1129_p3;
wire   [0:0] xor_ln210_28_fu_1137_p2;
wire   [2:0] trunc_ln210_14_fu_1143_p1;
wire   [0:0] icmp_ln209_14_fu_1123_p2;
wire   [3:0] xor_ln210_13_fu_1147_p3;
wire  signed [8:0] sext_ln207_8_fu_1179_p1;
wire   [8:0] diff_44_fu_1183_p2;
wire   [0:0] icmp_ln208_7_fu_1188_p2;
wire   [8:0] diff_45_fu_1194_p3;
wire   [0:0] bit_sel12_fu_1208_p3;
wire   [0:0] xor_ln210_21_fu_1216_p2;
wire   [2:0] trunc_ln210_7_fu_1222_p1;
wire   [0:0] icmp_ln209_7_fu_1202_p2;
wire   [3:0] xor_ln210_7_fu_1226_p3;
wire  signed [8:0] sext_ln207_9_fu_1242_p1;
wire   [8:0] diff_46_fu_1246_p2;
wire   [0:0] icmp_ln208_8_fu_1251_p2;
wire   [8:0] diff_47_fu_1257_p3;
wire   [0:0] bit_sel14_fu_1271_p3;
wire   [0:0] xor_ln210_22_fu_1279_p2;
wire   [2:0] trunc_ln210_8_fu_1285_p1;
wire   [0:0] icmp_ln209_8_fu_1265_p2;
wire   [3:0] xor_ln210_8_fu_1289_p3;
wire  signed [8:0] sext_ln207_10_fu_1305_p1;
wire   [8:0] diff_48_fu_1309_p2;
wire   [0:0] icmp_ln208_9_fu_1314_p2;
wire   [8:0] diff_49_fu_1320_p3;
wire   [0:0] bit_sel15_fu_1334_p3;
wire   [0:0] xor_ln210_23_fu_1342_p2;
wire   [2:0] trunc_ln210_9_fu_1348_p1;
wire   [0:0] icmp_ln209_9_fu_1328_p2;
wire   [3:0] xor_ln210_9_fu_1352_p3;
wire  signed [8:0] sext_ln207_16_fu_1388_p1;
wire   [8:0] diff_30_fu_1392_p2;
wire   [0:0] icmp_ln208_15_fu_1397_p2;
wire   [8:0] diff_31_fu_1403_p3;
wire   [0:0] bit_sel_fu_1417_p3;
wire   [0:0] xor_ln210_29_fu_1425_p2;
wire   [2:0] trunc_ln210_15_fu_1431_p1;
wire   [0:0] icmp_ln209_15_fu_1411_p2;
wire   [3:0] xor_ln210_14_fu_1435_p3;
wire   [9:0] zext_ln213_fu_1463_p1;
wire   [9:0] zext_ln213_2_fu_1469_p1;
wire   [9:0] add_ln213_fu_1476_p2;
wire   [9:0] zext_ln213_1_fu_1466_p1;
wire   [9:0] add_ln213_1_fu_1482_p2;
wire   [10:0] zext_ln213_4_fu_1488_p1;
wire   [10:0] zext_ln213_3_fu_1472_p1;
wire   [9:0] zext_ln213_6_fu_1495_p1;
wire   [9:0] zext_ln213_7_fu_1498_p1;
wire   [9:0] add_ln213_3_fu_1507_p2;
wire   [9:0] zext_ln213_5_fu_1492_p1;
wire   [9:0] add_ln213_4_fu_1513_p2;
wire   [10:0] zext_ln213_10_fu_1519_p1;
wire   [10:0] add_ln213_2_fu_1501_p2;
wire   [9:0] zext_ln213_16_fu_1533_p1;
wire   [9:0] zext_ln213_17_fu_1537_p1;
wire   [9:0] add_ln213_10_fu_1541_p2;
wire   [9:0] zext_ln213_15_fu_1529_p1;
wire   [11:0] zext_ln213_9_fu_1561_p1;
wire   [11:0] zext_ln213_8_fu_1557_p1;
wire   [9:0] zext_ln213_11_fu_1564_p1;
wire   [9:0] zext_ln213_12_fu_1568_p1;
wire   [9:0] add_ln213_7_fu_1584_p2;
wire   [11:0] zext_ln213_18_fu_1590_p1;
wire   [11:0] add_ln213_6_fu_1578_p2;
wire   [9:0] zext_ln213_13_fu_1572_p1;
wire   [9:0] zext_ln213_14_fu_1575_p1;
wire   [9:0] add_ln213_9_fu_1600_p2;
wire   [10:0] zext_ln213_20_fu_1610_p1;
wire   [10:0] zext_ln213_19_fu_1606_p1;
wire   [10:0] add_ln213_12_fu_1613_p2;
wire   [11:0] zext_ln213_21_fu_1619_p1;
wire   [11:0] add_ln213_8_fu_1594_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg = 1'b0;
#0 grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg = 1'b0;
end

transformer_top_stateful_softmax_EXP_LUT_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
EXP_LUT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(EXP_LUT_address0_local),
    .ce0(EXP_LUT_ce0_local),
    .q0(EXP_LUT_q0),
    .address1(EXP_LUT_address1_local),
    .ce1(EXP_LUT_ce1_local),
    .q1(EXP_LUT_q1),
    .address2(EXP_LUT_address2_local),
    .ce2(EXP_LUT_ce2_local),
    .q2(EXP_LUT_q2),
    .address3(EXP_LUT_address3_local),
    .ce3(EXP_LUT_ce3_local),
    .q3(EXP_LUT_q3),
    .address4(EXP_LUT_address4_local),
    .ce4(EXP_LUT_ce4_local),
    .q4(EXP_LUT_q4),
    .address5(EXP_LUT_address5_local),
    .ce5(EXP_LUT_ce5_local),
    .q5(EXP_LUT_q5)
);

transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_188_1 grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start),
    .ap_done(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_done),
    .ap_idle(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_idle),
    .ap_ready(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_ready),
    .s_gemm1_out_dout(s_gemm1_out_dout),
    .s_gemm1_out_empty_n(s_gemm1_out_empty_n),
    .s_gemm1_out_read(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_s_gemm1_out_read),
    .s_gemm1_out_num_data_valid(3'd0),
    .s_gemm1_out_fifo_cap(3'd0),
    .p_out(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out),
    .p_out_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out_ap_vld),
    .p_out1(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out1),
    .p_out1_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out1_ap_vld),
    .p_out2(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out2),
    .p_out2_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out2_ap_vld),
    .p_out3(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out3),
    .p_out3_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out3_ap_vld),
    .p_out4(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out4),
    .p_out4_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out4_ap_vld),
    .p_out5(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out5),
    .p_out5_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out5_ap_vld),
    .p_out6(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out6),
    .p_out6_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out6_ap_vld),
    .p_out7(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out7),
    .p_out7_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out7_ap_vld),
    .p_out8(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out8),
    .p_out8_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out8_ap_vld),
    .p_out9(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out9),
    .p_out9_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out9_ap_vld),
    .p_out10(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out10),
    .p_out10_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out10_ap_vld),
    .p_out11(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out11),
    .p_out11_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out11_ap_vld),
    .p_out12(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out12),
    .p_out12_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out12_ap_vld),
    .p_out13(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out13),
    .p_out13_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out13_ap_vld),
    .p_out14(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out14),
    .p_out14_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out14_ap_vld),
    .p_out15(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out15),
    .p_out15_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out15_ap_vld),
    .max_val_out(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_max_val_out),
    .max_val_out_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_max_val_out_ap_vld)
);

transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_217_4 grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start),
    .ap_done(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done),
    .ap_idle(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_idle),
    .ap_ready(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_ready),
    .s_softmax_out_din(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_din),
    .s_softmax_out_full_n(s_softmax_out_full_n),
    .s_softmax_out_write(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_write),
    .s_softmax_out_num_data_valid(s_softmax_out_num_data_valid),
    .s_softmax_out_fifo_cap(s_softmax_out_fifo_cap),
    .exp_val_18(exp_val_reg_1835),
    .exp_val_20(exp_val_16_reg_1847),
    .exp_val_22(exp_val_18_reg_1858),
    .exp_val_24(exp_val_20_reg_1870),
    .exp_val_26(exp_val_22_reg_1983),
    .exp_val_28(exp_val_24_reg_1941),
    .exp_val_30(exp_val_26_reg_1953),
    .exp_val_32(exp_val_28_reg_1963),
    .zext_ln217(add_ln213_13_reg_1998),
    .zext_ln213_17(exp_val_29_reg_2003),
    .exp_val_19(exp_val_15_reg_1841),
    .exp_val_21(exp_val_17_reg_1921),
    .exp_val_23(exp_val_19_reg_1864),
    .exp_val_25(exp_val_21_reg_1978),
    .exp_val_27(exp_val_23_reg_1988),
    .exp_val_29(exp_val_25_reg_1947),
    .exp_val_31(exp_val_27_reg_1958),
    .exp_val_33(exp_val_29_reg_2003)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call19) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg <= 1'b1;
        end else if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_ready == 1'b1)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg <= 1'b1;
        end else if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_ready == 1'b1)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln213_11_reg_1973 <= add_ln213_11_fu_1547_p2;
        add_ln213_5_reg_1968 <= add_ln213_5_fu_1523_p2;
        exp_val_17_reg_1921 <= EXP_LUT_q5;
        exp_val_24_reg_1941 <= EXP_LUT_q4;
        exp_val_25_reg_1947 <= EXP_LUT_q3;
        exp_val_26_reg_1953 <= EXP_LUT_q2;
        exp_val_27_reg_1958 <= EXP_LUT_q1;
        exp_val_28_reg_1963 <= EXP_LUT_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln213_13_reg_1998 <= add_ln213_13_fu_1623_p2;
        exp_val_21_reg_1978 <= EXP_LUT_q2;
        exp_val_22_reg_1983 <= EXP_LUT_q1;
        exp_val_23_reg_1988 <= EXP_LUT_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        exp_val_15_reg_1841 <= EXP_LUT_q4;
        exp_val_16_reg_1847 <= EXP_LUT_q3;
        exp_val_18_reg_1858 <= EXP_LUT_q2;
        exp_val_19_reg_1864 <= EXP_LUT_q1;
        exp_val_20_reg_1870 <= EXP_LUT_q0;
        exp_val_reg_1835 <= EXP_LUT_q5;
        idx_15_reg_1916 <= idx_15_fu_1443_p3;
        idx_22_reg_1876 <= idx_22_fu_1234_p3;
        idx_23_reg_1881 <= idx_23_fu_1297_p3;
        idx_24_reg_1886 <= idx_24_fu_1360_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        exp_val_29_reg_2003 <= EXP_LUT_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        idx_16_reg_1750 <= idx_16_fu_467_p3;
        idx_17_reg_1755 <= idx_17_fu_531_p3;
        idx_19_reg_1760 <= idx_19_fu_595_p3;
        idx_20_reg_1765 <= idx_20_fu_659_p3;
        idx_21_reg_1770 <= idx_21_fu_723_p3;
        idx_reg_1745 <= idx_fu_403_p3;
        sext_ln207_reg_1731 <= sext_ln207_fu_343_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        idx_18_reg_1790 <= idx_18_fu_828_p3;
        idx_25_reg_1810 <= idx_25_fu_903_p3;
        idx_26_reg_1815 <= idx_26_fu_966_p3;
        idx_27_reg_1820 <= idx_27_fu_1029_p3;
        idx_28_reg_1825 <= idx_28_fu_1092_p3;
        idx_29_reg_1830 <= idx_29_fu_1155_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        EXP_LUT_address0_local = zext_ln211_15_fu_1553_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        EXP_LUT_address0_local = zext_ln211_9_fu_1459_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address0_local = zext_ln211_14_fu_1384_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address0_local = zext_ln211_6_fu_844_p1;
    end else begin
        EXP_LUT_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        EXP_LUT_address1_local = zext_ln211_8_fu_1455_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address1_local = zext_ln211_13_fu_1380_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address1_local = zext_ln211_5_fu_840_p1;
    end else begin
        EXP_LUT_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        EXP_LUT_address2_local = zext_ln211_7_fu_1451_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address2_local = zext_ln211_12_fu_1376_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address2_local = zext_ln211_4_fu_836_p1;
    end else begin
        EXP_LUT_address2_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address3_local = zext_ln211_11_fu_1372_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address3_local = zext_ln211_2_fu_769_p1;
    end else begin
        EXP_LUT_address3_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address4_local = zext_ln211_10_fu_1368_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address4_local = zext_ln211_1_fu_765_p1;
    end else begin
        EXP_LUT_address4_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address5_local = zext_ln211_3_fu_1175_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address5_local = zext_ln211_fu_761_p1;
    end else begin
        EXP_LUT_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce0_local = 1'b1;
    end else begin
        EXP_LUT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce1_local = 1'b1;
    end else begin
        EXP_LUT_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce2_local = 1'b1;
    end else begin
        EXP_LUT_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce3_local = 1'b1;
    end else begin
        EXP_LUT_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce4_local = 1'b1;
    end else begin
        EXP_LUT_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5))) begin
        EXP_LUT_ce5_local = 1'b1;
    end else begin
        EXP_LUT_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln213_10_fu_1541_p2 = (zext_ln213_16_fu_1533_p1 + zext_ln213_17_fu_1537_p1);

assign add_ln213_11_fu_1547_p2 = (add_ln213_10_fu_1541_p2 + zext_ln213_15_fu_1529_p1);

assign add_ln213_12_fu_1613_p2 = (zext_ln213_20_fu_1610_p1 + zext_ln213_19_fu_1606_p1);

assign add_ln213_13_fu_1623_p2 = (zext_ln213_21_fu_1619_p1 + add_ln213_8_fu_1594_p2);

assign add_ln213_1_fu_1482_p2 = (add_ln213_fu_1476_p2 + zext_ln213_1_fu_1466_p1);

assign add_ln213_2_fu_1501_p2 = (zext_ln213_4_fu_1488_p1 + zext_ln213_3_fu_1472_p1);

assign add_ln213_3_fu_1507_p2 = (zext_ln213_6_fu_1495_p1 + zext_ln213_7_fu_1498_p1);

assign add_ln213_4_fu_1513_p2 = (add_ln213_3_fu_1507_p2 + zext_ln213_5_fu_1492_p1);

assign add_ln213_5_fu_1523_p2 = (zext_ln213_10_fu_1519_p1 + add_ln213_2_fu_1501_p2);

assign add_ln213_6_fu_1578_p2 = (zext_ln213_9_fu_1561_p1 + zext_ln213_8_fu_1557_p1);

assign add_ln213_7_fu_1584_p2 = (zext_ln213_11_fu_1564_p1 + zext_ln213_12_fu_1568_p1);

assign add_ln213_8_fu_1594_p2 = (zext_ln213_18_fu_1590_p1 + add_ln213_6_fu_1578_p2);

assign add_ln213_9_fu_1600_p2 = (zext_ln213_13_fu_1572_p1 + zext_ln213_14_fu_1575_p1);

assign add_ln213_fu_1476_p2 = (zext_ln213_fu_1463_p1 + zext_ln213_2_fu_1469_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call19 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bit_sel10_fu_940_p3 = diff_53_fu_926_p3[32'd3];

assign bit_sel11_fu_697_p3 = diff_43_fu_683_p3[32'd3];

assign bit_sel12_fu_1208_p3 = diff_45_fu_1194_p3[32'd3];

assign bit_sel13_fu_877_p3 = diff_51_fu_863_p3[32'd3];

assign bit_sel14_fu_1271_p3 = diff_47_fu_1257_p3[32'd3];

assign bit_sel15_fu_1334_p3 = diff_49_fu_1320_p3[32'd3];

assign bit_sel1_fu_1129_p3 = diff_59_fu_1115_p3[32'd3];

assign bit_sel2_fu_377_p3 = diff_1_fu_363_p3[32'd3];

assign bit_sel3_fu_441_p3 = diff_33_fu_427_p3[32'd3];

assign bit_sel4_fu_1066_p3 = diff_57_fu_1052_p3[32'd3];

assign bit_sel5_fu_505_p3 = diff_35_fu_491_p3[32'd3];

assign bit_sel6_fu_802_p3 = diff_37_fu_788_p3[32'd3];

assign bit_sel7_fu_1003_p3 = diff_55_fu_989_p3[32'd3];

assign bit_sel8_fu_569_p3 = diff_39_fu_555_p3[32'd3];

assign bit_sel9_fu_633_p3 = diff_41_fu_619_p3[32'd3];

assign bit_sel_fu_1417_p3 = diff_31_fu_1403_p3[32'd3];

assign diff_1_fu_363_p3 = ((icmp_ln208_fu_357_p2[0:0] == 1'b1) ? 9'd504 : diff_fu_351_p2);

assign diff_30_fu_1392_p2 = ($signed(sext_ln207_16_fu_1388_p1) - $signed(sext_ln207_reg_1731));

assign diff_31_fu_1403_p3 = ((icmp_ln208_15_fu_1397_p2[0:0] == 1'b1) ? 9'd504 : diff_30_fu_1392_p2);

assign diff_32_fu_415_p2 = ($signed(sext_ln207_2_fu_411_p1) - $signed(sext_ln207_fu_343_p1));

assign diff_33_fu_427_p3 = ((icmp_ln208_1_fu_421_p2[0:0] == 1'b1) ? 9'd504 : diff_32_fu_415_p2);

assign diff_34_fu_479_p2 = ($signed(sext_ln207_3_fu_475_p1) - $signed(sext_ln207_fu_343_p1));

assign diff_35_fu_491_p3 = ((icmp_ln208_2_fu_485_p2[0:0] == 1'b1) ? 9'd504 : diff_34_fu_479_p2);

assign diff_36_fu_777_p2 = ($signed(sext_ln207_4_fu_773_p1) - $signed(sext_ln207_reg_1731));

assign diff_37_fu_788_p3 = ((icmp_ln208_3_fu_782_p2[0:0] == 1'b1) ? 9'd504 : diff_36_fu_777_p2);

assign diff_38_fu_543_p2 = ($signed(sext_ln207_5_fu_539_p1) - $signed(sext_ln207_fu_343_p1));

assign diff_39_fu_555_p3 = ((icmp_ln208_4_fu_549_p2[0:0] == 1'b1) ? 9'd504 : diff_38_fu_543_p2);

assign diff_40_fu_607_p2 = ($signed(sext_ln207_6_fu_603_p1) - $signed(sext_ln207_fu_343_p1));

assign diff_41_fu_619_p3 = ((icmp_ln208_5_fu_613_p2[0:0] == 1'b1) ? 9'd504 : diff_40_fu_607_p2);

assign diff_42_fu_671_p2 = ($signed(sext_ln207_7_fu_667_p1) - $signed(sext_ln207_fu_343_p1));

assign diff_43_fu_683_p3 = ((icmp_ln208_6_fu_677_p2[0:0] == 1'b1) ? 9'd504 : diff_42_fu_671_p2);

assign diff_44_fu_1183_p2 = ($signed(sext_ln207_8_fu_1179_p1) - $signed(sext_ln207_reg_1731));

assign diff_45_fu_1194_p3 = ((icmp_ln208_7_fu_1188_p2[0:0] == 1'b1) ? 9'd504 : diff_44_fu_1183_p2);

assign diff_46_fu_1246_p2 = ($signed(sext_ln207_9_fu_1242_p1) - $signed(sext_ln207_reg_1731));

assign diff_47_fu_1257_p3 = ((icmp_ln208_8_fu_1251_p2[0:0] == 1'b1) ? 9'd504 : diff_46_fu_1246_p2);

assign diff_48_fu_1309_p2 = ($signed(sext_ln207_10_fu_1305_p1) - $signed(sext_ln207_reg_1731));

assign diff_49_fu_1320_p3 = ((icmp_ln208_9_fu_1314_p2[0:0] == 1'b1) ? 9'd504 : diff_48_fu_1309_p2);

assign diff_50_fu_852_p2 = ($signed(sext_ln207_11_fu_848_p1) - $signed(sext_ln207_reg_1731));

assign diff_51_fu_863_p3 = ((icmp_ln208_10_fu_857_p2[0:0] == 1'b1) ? 9'd504 : diff_50_fu_852_p2);

assign diff_52_fu_915_p2 = ($signed(sext_ln207_12_fu_911_p1) - $signed(sext_ln207_reg_1731));

assign diff_53_fu_926_p3 = ((icmp_ln208_11_fu_920_p2[0:0] == 1'b1) ? 9'd504 : diff_52_fu_915_p2);

assign diff_54_fu_978_p2 = ($signed(sext_ln207_13_fu_974_p1) - $signed(sext_ln207_reg_1731));

assign diff_55_fu_989_p3 = ((icmp_ln208_12_fu_983_p2[0:0] == 1'b1) ? 9'd504 : diff_54_fu_978_p2);

assign diff_56_fu_1041_p2 = ($signed(sext_ln207_14_fu_1037_p1) - $signed(sext_ln207_reg_1731));

assign diff_57_fu_1052_p3 = ((icmp_ln208_13_fu_1046_p2[0:0] == 1'b1) ? 9'd504 : diff_56_fu_1041_p2);

assign diff_58_fu_1104_p2 = ($signed(sext_ln207_15_fu_1100_p1) - $signed(sext_ln207_reg_1731));

assign diff_59_fu_1115_p3 = ((icmp_ln208_14_fu_1109_p2[0:0] == 1'b1) ? 9'd504 : diff_58_fu_1104_p2);

assign diff_fu_351_p2 = ($signed(sext_ln207_1_fu_347_p1) - $signed(sext_ln207_fu_343_p1));

assign grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start = grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_ap_start_reg;

assign grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_ap_start_reg;

assign icmp_ln208_10_fu_857_p2 = (($signed(diff_50_fu_852_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_11_fu_920_p2 = (($signed(diff_52_fu_915_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_12_fu_983_p2 = (($signed(diff_54_fu_978_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_13_fu_1046_p2 = (($signed(diff_56_fu_1041_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_14_fu_1109_p2 = (($signed(diff_58_fu_1104_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_15_fu_1397_p2 = (($signed(diff_30_fu_1392_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_1_fu_421_p2 = (($signed(diff_32_fu_415_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_2_fu_485_p2 = (($signed(diff_34_fu_479_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_3_fu_782_p2 = (($signed(diff_36_fu_777_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_4_fu_549_p2 = (($signed(diff_38_fu_543_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_5_fu_613_p2 = (($signed(diff_40_fu_607_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_6_fu_677_p2 = (($signed(diff_42_fu_671_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_7_fu_1188_p2 = (($signed(diff_44_fu_1183_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_8_fu_1251_p2 = (($signed(diff_46_fu_1246_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_9_fu_1314_p2 = (($signed(diff_48_fu_1309_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_357_p2 = (($signed(diff_fu_351_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln209_10_fu_871_p2 = (($signed(diff_51_fu_863_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_11_fu_934_p2 = (($signed(diff_53_fu_926_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_12_fu_997_p2 = (($signed(diff_55_fu_989_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_13_fu_1060_p2 = (($signed(diff_57_fu_1052_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_14_fu_1123_p2 = (($signed(diff_59_fu_1115_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_15_fu_1411_p2 = (($signed(diff_31_fu_1403_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_1_fu_435_p2 = (($signed(diff_33_fu_427_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_2_fu_499_p2 = (($signed(diff_35_fu_491_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_3_fu_796_p2 = (($signed(diff_37_fu_788_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_4_fu_563_p2 = (($signed(diff_39_fu_555_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_5_fu_627_p2 = (($signed(diff_41_fu_619_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_6_fu_691_p2 = (($signed(diff_43_fu_683_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_7_fu_1202_p2 = (($signed(diff_45_fu_1194_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_8_fu_1265_p2 = (($signed(diff_47_fu_1257_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_9_fu_1328_p2 = (($signed(diff_49_fu_1320_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_371_p2 = (($signed(diff_1_fu_363_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign idx_15_fu_1443_p3 = ((icmp_ln209_15_fu_1411_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_14_fu_1435_p3);

assign idx_16_fu_467_p3 = ((icmp_ln209_1_fu_435_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_1_fu_459_p3);

assign idx_17_fu_531_p3 = ((icmp_ln209_2_fu_499_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_2_fu_523_p3);

assign idx_18_fu_828_p3 = ((icmp_ln209_3_fu_796_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_3_fu_820_p3);

assign idx_19_fu_595_p3 = ((icmp_ln209_4_fu_563_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_4_fu_587_p3);

assign idx_20_fu_659_p3 = ((icmp_ln209_5_fu_627_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_5_fu_651_p3);

assign idx_21_fu_723_p3 = ((icmp_ln209_6_fu_691_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_6_fu_715_p3);

assign idx_22_fu_1234_p3 = ((icmp_ln209_7_fu_1202_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_7_fu_1226_p3);

assign idx_23_fu_1297_p3 = ((icmp_ln209_8_fu_1265_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_8_fu_1289_p3);

assign idx_24_fu_1360_p3 = ((icmp_ln209_9_fu_1328_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_9_fu_1352_p3);

assign idx_25_fu_903_p3 = ((icmp_ln209_10_fu_871_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_s_fu_895_p3);

assign idx_26_fu_966_p3 = ((icmp_ln209_11_fu_934_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_10_fu_958_p3);

assign idx_27_fu_1029_p3 = ((icmp_ln209_12_fu_997_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_11_fu_1021_p3);

assign idx_28_fu_1092_p3 = ((icmp_ln209_13_fu_1060_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_12_fu_1084_p3);

assign idx_29_fu_1155_p3 = ((icmp_ln209_14_fu_1123_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_13_fu_1147_p3);

assign idx_fu_403_p3 = ((icmp_ln209_fu_371_p2[0:0] == 1'b1) ? 4'd8 : xor_ln_fu_395_p3);

assign s_gemm1_out_read = grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_s_gemm1_out_read;

assign s_softmax_out_din = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_din;

assign s_softmax_out_write = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_284_s_softmax_out_write;

assign sext_ln207_10_fu_1305_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out6);

assign sext_ln207_11_fu_848_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out5);

assign sext_ln207_12_fu_911_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out4);

assign sext_ln207_13_fu_974_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out3);

assign sext_ln207_14_fu_1037_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out2);

assign sext_ln207_15_fu_1100_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out1);

assign sext_ln207_16_fu_1388_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out);

assign sext_ln207_1_fu_347_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out15);

assign sext_ln207_2_fu_411_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out14);

assign sext_ln207_3_fu_475_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out13);

assign sext_ln207_4_fu_773_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out12);

assign sext_ln207_5_fu_539_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out11);

assign sext_ln207_6_fu_603_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out10);

assign sext_ln207_7_fu_667_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out9);

assign sext_ln207_8_fu_1179_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out8);

assign sext_ln207_9_fu_1242_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_p_out7);

assign sext_ln207_fu_343_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_261_max_val_out);

assign trunc_ln210_10_fu_891_p1 = diff_51_fu_863_p3[2:0];

assign trunc_ln210_11_fu_954_p1 = diff_53_fu_926_p3[2:0];

assign trunc_ln210_12_fu_1017_p1 = diff_55_fu_989_p3[2:0];

assign trunc_ln210_13_fu_1080_p1 = diff_57_fu_1052_p3[2:0];

assign trunc_ln210_14_fu_1143_p1 = diff_59_fu_1115_p3[2:0];

assign trunc_ln210_15_fu_1431_p1 = diff_31_fu_1403_p3[2:0];

assign trunc_ln210_1_fu_455_p1 = diff_33_fu_427_p3[2:0];

assign trunc_ln210_2_fu_519_p1 = diff_35_fu_491_p3[2:0];

assign trunc_ln210_3_fu_816_p1 = diff_37_fu_788_p3[2:0];

assign trunc_ln210_4_fu_583_p1 = diff_39_fu_555_p3[2:0];

assign trunc_ln210_5_fu_647_p1 = diff_41_fu_619_p3[2:0];

assign trunc_ln210_6_fu_711_p1 = diff_43_fu_683_p3[2:0];

assign trunc_ln210_7_fu_1222_p1 = diff_45_fu_1194_p3[2:0];

assign trunc_ln210_8_fu_1285_p1 = diff_47_fu_1257_p3[2:0];

assign trunc_ln210_9_fu_1348_p1 = diff_49_fu_1320_p3[2:0];

assign trunc_ln210_fu_391_p1 = diff_1_fu_363_p3[2:0];

assign xor_ln210_10_fu_958_p3 = {{xor_ln210_25_fu_948_p2}, {trunc_ln210_11_fu_954_p1}};

assign xor_ln210_11_fu_1021_p3 = {{xor_ln210_26_fu_1011_p2}, {trunc_ln210_12_fu_1017_p1}};

assign xor_ln210_12_fu_1084_p3 = {{xor_ln210_27_fu_1074_p2}, {trunc_ln210_13_fu_1080_p1}};

assign xor_ln210_13_fu_1147_p3 = {{xor_ln210_28_fu_1137_p2}, {trunc_ln210_14_fu_1143_p1}};

assign xor_ln210_14_fu_1435_p3 = {{xor_ln210_29_fu_1425_p2}, {trunc_ln210_15_fu_1431_p1}};

assign xor_ln210_15_fu_385_p2 = (bit_sel2_fu_377_p3 ^ 1'd1);

assign xor_ln210_16_fu_513_p2 = (bit_sel5_fu_505_p3 ^ 1'd1);

assign xor_ln210_17_fu_810_p2 = (bit_sel6_fu_802_p3 ^ 1'd1);

assign xor_ln210_18_fu_577_p2 = (bit_sel8_fu_569_p3 ^ 1'd1);

assign xor_ln210_19_fu_641_p2 = (bit_sel9_fu_633_p3 ^ 1'd1);

assign xor_ln210_1_fu_459_p3 = {{xor_ln210_fu_449_p2}, {trunc_ln210_1_fu_455_p1}};

assign xor_ln210_20_fu_705_p2 = (bit_sel11_fu_697_p3 ^ 1'd1);

assign xor_ln210_21_fu_1216_p2 = (bit_sel12_fu_1208_p3 ^ 1'd1);

assign xor_ln210_22_fu_1279_p2 = (bit_sel14_fu_1271_p3 ^ 1'd1);

assign xor_ln210_23_fu_1342_p2 = (bit_sel15_fu_1334_p3 ^ 1'd1);

assign xor_ln210_24_fu_885_p2 = (bit_sel13_fu_877_p3 ^ 1'd1);

assign xor_ln210_25_fu_948_p2 = (bit_sel10_fu_940_p3 ^ 1'd1);

assign xor_ln210_26_fu_1011_p2 = (bit_sel7_fu_1003_p3 ^ 1'd1);

assign xor_ln210_27_fu_1074_p2 = (bit_sel4_fu_1066_p3 ^ 1'd1);

assign xor_ln210_28_fu_1137_p2 = (bit_sel1_fu_1129_p3 ^ 1'd1);

assign xor_ln210_29_fu_1425_p2 = (bit_sel_fu_1417_p3 ^ 1'd1);

assign xor_ln210_2_fu_523_p3 = {{xor_ln210_16_fu_513_p2}, {trunc_ln210_2_fu_519_p1}};

assign xor_ln210_3_fu_820_p3 = {{xor_ln210_17_fu_810_p2}, {trunc_ln210_3_fu_816_p1}};

assign xor_ln210_4_fu_587_p3 = {{xor_ln210_18_fu_577_p2}, {trunc_ln210_4_fu_583_p1}};

assign xor_ln210_5_fu_651_p3 = {{xor_ln210_19_fu_641_p2}, {trunc_ln210_5_fu_647_p1}};

assign xor_ln210_6_fu_715_p3 = {{xor_ln210_20_fu_705_p2}, {trunc_ln210_6_fu_711_p1}};

assign xor_ln210_7_fu_1226_p3 = {{xor_ln210_21_fu_1216_p2}, {trunc_ln210_7_fu_1222_p1}};

assign xor_ln210_8_fu_1289_p3 = {{xor_ln210_22_fu_1279_p2}, {trunc_ln210_8_fu_1285_p1}};

assign xor_ln210_9_fu_1352_p3 = {{xor_ln210_23_fu_1342_p2}, {trunc_ln210_9_fu_1348_p1}};

assign xor_ln210_fu_449_p2 = (bit_sel3_fu_441_p3 ^ 1'd1);

assign xor_ln210_s_fu_895_p3 = {{xor_ln210_24_fu_885_p2}, {trunc_ln210_10_fu_891_p1}};

assign xor_ln_fu_395_p3 = {{xor_ln210_15_fu_385_p2}, {trunc_ln210_fu_391_p1}};

assign zext_ln211_10_fu_1368_p1 = idx_25_reg_1810;

assign zext_ln211_11_fu_1372_p1 = idx_26_reg_1815;

assign zext_ln211_12_fu_1376_p1 = idx_27_reg_1820;

assign zext_ln211_13_fu_1380_p1 = idx_28_reg_1825;

assign zext_ln211_14_fu_1384_p1 = idx_29_reg_1830;

assign zext_ln211_15_fu_1553_p1 = idx_15_reg_1916;

assign zext_ln211_1_fu_765_p1 = idx_16_reg_1750;

assign zext_ln211_2_fu_769_p1 = idx_17_reg_1755;

assign zext_ln211_3_fu_1175_p1 = idx_18_reg_1790;

assign zext_ln211_4_fu_836_p1 = idx_19_reg_1760;

assign zext_ln211_5_fu_840_p1 = idx_20_reg_1765;

assign zext_ln211_6_fu_844_p1 = idx_21_reg_1770;

assign zext_ln211_7_fu_1451_p1 = idx_22_reg_1876;

assign zext_ln211_8_fu_1455_p1 = idx_23_reg_1881;

assign zext_ln211_9_fu_1459_p1 = idx_24_reg_1886;

assign zext_ln211_fu_761_p1 = idx_reg_1745;

assign zext_ln213_10_fu_1519_p1 = add_ln213_4_fu_1513_p2;

assign zext_ln213_11_fu_1564_p1 = EXP_LUT_q1;

assign zext_ln213_12_fu_1568_p1 = EXP_LUT_q0;

assign zext_ln213_13_fu_1572_p1 = exp_val_24_reg_1941;

assign zext_ln213_14_fu_1575_p1 = exp_val_25_reg_1947;

assign zext_ln213_15_fu_1529_p1 = EXP_LUT_q2;

assign zext_ln213_16_fu_1533_p1 = EXP_LUT_q1;

assign zext_ln213_17_fu_1537_p1 = EXP_LUT_q0;

assign zext_ln213_18_fu_1590_p1 = add_ln213_7_fu_1584_p2;

assign zext_ln213_19_fu_1606_p1 = add_ln213_9_fu_1600_p2;

assign zext_ln213_1_fu_1466_p1 = exp_val_15_reg_1841;

assign zext_ln213_20_fu_1610_p1 = add_ln213_11_reg_1973;

assign zext_ln213_21_fu_1619_p1 = add_ln213_12_fu_1613_p2;

assign zext_ln213_2_fu_1469_p1 = exp_val_16_reg_1847;

assign zext_ln213_3_fu_1472_p1 = EXP_LUT_q5;

assign zext_ln213_4_fu_1488_p1 = add_ln213_1_fu_1482_p2;

assign zext_ln213_5_fu_1492_p1 = exp_val_18_reg_1858;

assign zext_ln213_6_fu_1495_p1 = exp_val_19_reg_1864;

assign zext_ln213_7_fu_1498_p1 = exp_val_20_reg_1870;

assign zext_ln213_8_fu_1557_p1 = EXP_LUT_q2;

assign zext_ln213_9_fu_1561_p1 = add_ln213_5_reg_1968;

assign zext_ln213_fu_1463_p1 = exp_val_reg_1835;

endmodule //transformer_top_stateful_softmax
