-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_109_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_norm1_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_norm1_out_full_n : IN STD_LOGIC;
    s_norm1_out_write : OUT STD_LOGIC;
    s_norm1_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    s_norm1_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    buf_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_3_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_5_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_7_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_9_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_11_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_13_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_15_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln100 : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_2_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_4_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_6_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_8_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_10_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_12_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_14_reload : IN STD_LOGIC_VECTOR (7 downto 0);
    buf_16_reload : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_109_3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal s_norm1_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal tmp_reg_387 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_4_reg_392 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_2_fu_96 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln109_fu_227_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal x_fu_237_p17 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln109_fu_233_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p19 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln115_fu_277_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln100_cast_fu_209_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_fu_281_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_2_fu_297_p17 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_2_fu_297_p19 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln115_2_fu_337_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal diff_61_fu_341_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal elems_fu_362_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_365_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal x_fu_237_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_fu_237_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p11 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p13 : STD_LOGIC_VECTOR (2 downto 0);
    signal x_2_fu_297_p15 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component transformer_top_sparsemux_17_3_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (2 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (2 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (2 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (2 downto 0);
        din7_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component transformer_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_17_3_8_1_1_U25 : component transformer_top_sparsemux_17_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 8,
        CASE1 => "001",
        din1_WIDTH => 8,
        CASE2 => "010",
        din2_WIDTH => 8,
        CASE3 => "011",
        din3_WIDTH => 8,
        CASE4 => "100",
        din4_WIDTH => 8,
        CASE5 => "101",
        din5_WIDTH => 8,
        CASE6 => "110",
        din6_WIDTH => 8,
        CASE7 => "111",
        din7_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => buf_reload,
        din1 => buf_3_reload,
        din2 => buf_5_reload,
        din3 => buf_7_reload,
        din4 => buf_9_reload,
        din5 => buf_11_reload,
        din6 => buf_13_reload,
        din7 => buf_15_reload,
        def => x_fu_237_p17,
        sel => trunc_ln109_fu_233_p1,
        dout => x_fu_237_p19);

    sparsemux_17_3_8_1_1_U26 : component transformer_top_sparsemux_17_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000",
        din0_WIDTH => 8,
        CASE1 => "001",
        din1_WIDTH => 8,
        CASE2 => "010",
        din2_WIDTH => 8,
        CASE3 => "011",
        din3_WIDTH => 8,
        CASE4 => "100",
        din4_WIDTH => 8,
        CASE5 => "101",
        din5_WIDTH => 8,
        CASE6 => "110",
        din6_WIDTH => 8,
        CASE7 => "111",
        din7_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => buf_2_reload,
        din1 => buf_4_reload,
        din2 => buf_6_reload,
        din3 => buf_8_reload,
        din4 => buf_10_reload,
        din5 => buf_12_reload,
        din6 => buf_14_reload,
        din7 => buf_16_reload,
        def => x_2_fu_297_p17,
        sel => trunc_ln109_fu_233_p1,
        dout => x_2_fu_297_p19);

    flow_control_loop_pipe_sequential_init_U : component transformer_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_2_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_221_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_2_fu_96 <= add_ln109_fu_227_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_2_fu_96 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_4_reg_392 <= diff_61_fu_341_p2(8 downto 2);
                tmp_reg_387 <= diff_fu_281_p2(8 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln109_fu_227_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, s_norm1_out_full_n)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((s_norm1_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, s_norm1_out_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((s_norm1_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, s_norm1_out_full_n)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((s_norm1_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, s_norm1_out_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((s_norm1_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_221_p2)
    begin
        if (((icmp_ln109_fu_221_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, i_2_fu_96, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= i_2_fu_96;
        end if; 
    end process;

    diff_61_fu_341_p2 <= std_logic_vector(signed(sext_ln115_2_fu_337_p1) - signed(sext_ln100_cast_fu_209_p1));
    diff_fu_281_p2 <= std_logic_vector(signed(sext_ln115_fu_277_p1) - signed(sext_ln100_cast_fu_209_p1));
        elems_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_reg_387),8));

    icmp_ln109_fu_221_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_8) else "0";

    s_norm1_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, s_norm1_out_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_norm1_out_blk_n <= s_norm1_out_full_n;
        else 
            s_norm1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

        s_norm1_out_din <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_365_p3),16));


    s_norm1_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_norm1_out_write <= ap_const_logic_1;
        else 
            s_norm1_out_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln100_cast_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln100),9));

        sext_ln115_2_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_2_fu_297_p19),9));

        sext_ln115_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_fu_237_p19),9));

    tmp_5_fu_365_p3 <= (tmp_4_reg_392 & elems_fu_362_p1);
    trunc_ln109_fu_233_p1 <= ap_sig_allocacmp_i(3 - 1 downto 0);
    x_2_fu_297_p17 <= "XXXXXXXX";
    x_fu_237_p17 <= "XXXXXXXX";
end behav;
