// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_stateful_softmax (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_gemm1_out_dout,
        s_gemm1_out_empty_n,
        s_gemm1_out_read,
        s_gemm1_out_num_data_valid,
        s_gemm1_out_fifo_cap,
        s_softmax_out_din,
        s_softmax_out_full_n,
        s_softmax_out_write,
        s_softmax_out_num_data_valid,
        s_softmax_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] s_gemm1_out_dout;
input   s_gemm1_out_empty_n;
output   s_gemm1_out_read;
input  [2:0] s_gemm1_out_num_data_valid;
input  [2:0] s_gemm1_out_fifo_cap;
output  [15:0] s_softmax_out_din;
input   s_softmax_out_full_n;
output   s_softmax_out_write;
input  [31:0] s_softmax_out_num_data_valid;
input  [31:0] s_softmax_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] EXP_LUT_q0;
wire   [8:0] EXP_LUT_q1;
wire   [8:0] EXP_LUT_q2;
wire   [8:0] EXP_LUT_q3;
wire   [8:0] EXP_LUT_q4;
wire   [8:0] EXP_LUT_q5;
wire   [3:0] EXP_LUT_address6;
wire   [8:0] EXP_LUT_q6;
wire   [3:0] EXP_LUT_address7;
wire   [8:0] EXP_LUT_q7;
wire   [3:0] EXP_LUT_address8;
wire   [8:0] EXP_LUT_q8;
wire  signed [8:0] sext_ln207_fu_355_p1;
reg  signed [8:0] sext_ln207_reg_1760;
wire    ap_CS_fsm_state3;
reg   [8:0] exp_val_reg_1804;
wire    ap_CS_fsm_state4;
reg   [8:0] exp_val_15_reg_1810;
reg   [8:0] exp_val_16_reg_1816;
reg   [8:0] exp_val_18_reg_1827;
reg   [8:0] exp_val_19_reg_1833;
reg   [8:0] exp_val_20_reg_1839;
wire   [3:0] idx_15_fu_1482_p3;
reg   [3:0] idx_15_reg_1885;
reg   [8:0] exp_val_17_reg_1890;
wire    ap_CS_fsm_state5;
reg   [8:0] exp_val_21_reg_1895;
reg   [8:0] exp_val_22_reg_1900;
reg   [8:0] exp_val_23_reg_1905;
reg   [8:0] exp_val_24_reg_1910;
reg   [8:0] exp_val_25_reg_1915;
reg   [8:0] exp_val_26_reg_1920;
reg   [8:0] exp_val_27_reg_1925;
reg   [8:0] exp_val_28_reg_1930;
wire   [11:0] add_ln213_6_fu_1596_p2;
reg   [11:0] add_ln213_6_reg_1940;
wire   [9:0] add_ln213_7_fu_1602_p2;
reg   [9:0] add_ln213_7_reg_1945;
wire   [10:0] add_ln213_12_fu_1634_p2;
reg   [10:0] add_ln213_12_reg_1950;
reg   [8:0] exp_val_29_reg_1955;
wire    ap_CS_fsm_state6;
wire   [11:0] add_ln213_13_fu_1651_p2;
reg   [11:0] add_ln213_13_reg_1961;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_done;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_idle;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_ready;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_s_gemm1_out_read;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out1;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out1_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out2;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out2_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out3;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out3_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out4;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out4_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out5;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out5_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out6;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out6_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out7;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out7_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out8;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out8_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out9;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out9_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out10;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out10_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out11;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out11_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out12;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out12_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out13;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out13_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out14;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out14_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out15;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out15_ap_vld;
wire   [7:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_max_val_out;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_max_val_out_ap_vld;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_idle;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_ready;
wire   [15:0] grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_din;
wire    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_write;
reg    grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg;
reg    ap_block_state1_ignore_call19;
wire    ap_CS_fsm_state2;
reg    grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg;
wire    ap_CS_fsm_state7;
wire   [63:0] zext_ln211_fu_423_p1;
wire   [63:0] zext_ln211_1_fu_492_p1;
wire   [63:0] zext_ln211_2_fu_561_p1;
wire   [63:0] zext_ln211_4_fu_630_p1;
wire   [63:0] zext_ln211_5_fu_699_p1;
wire   [63:0] zext_ln211_6_fu_768_p1;
wire   [63:0] zext_ln211_3_fu_878_p1;
wire   [63:0] zext_ln211_7_fu_946_p1;
wire   [63:0] zext_ln211_8_fu_1014_p1;
wire   [63:0] zext_ln211_9_fu_1082_p1;
wire   [63:0] zext_ln211_10_fu_1150_p1;
wire   [63:0] zext_ln211_11_fu_1218_p1;
wire   [63:0] zext_ln211_12_fu_1286_p1;
wire   [63:0] zext_ln211_13_fu_1354_p1;
wire   [63:0] zext_ln211_14_fu_1422_p1;
wire   [63:0] zext_ln211_15_fu_1490_p1;
reg    EXP_LUT_ce5_local;
reg   [3:0] EXP_LUT_address5_local;
reg    EXP_LUT_ce4_local;
reg   [3:0] EXP_LUT_address4_local;
reg    EXP_LUT_ce3_local;
reg   [3:0] EXP_LUT_address3_local;
reg    EXP_LUT_ce2_local;
reg   [3:0] EXP_LUT_address2_local;
reg    EXP_LUT_ce1_local;
reg   [3:0] EXP_LUT_address1_local;
reg    EXP_LUT_ce0_local;
reg   [3:0] EXP_LUT_address0_local;
reg    EXP_LUT_ce8_local;
reg    EXP_LUT_ce7_local;
reg    EXP_LUT_ce6_local;
wire  signed [8:0] sext_ln207_1_fu_359_p1;
wire   [8:0] diff_fu_363_p2;
wire   [0:0] icmp_ln208_fu_369_p2;
wire   [8:0] diff_1_fu_375_p3;
wire   [0:0] bit_sel2_fu_389_p3;
wire   [0:0] xor_ln210_15_fu_397_p2;
wire   [2:0] trunc_ln210_fu_403_p1;
wire   [0:0] icmp_ln209_fu_383_p2;
wire   [3:0] xor_ln_fu_407_p3;
wire   [3:0] idx_fu_415_p3;
wire  signed [8:0] sext_ln207_2_fu_428_p1;
wire   [8:0] diff_32_fu_432_p2;
wire   [0:0] icmp_ln208_1_fu_438_p2;
wire   [8:0] diff_33_fu_444_p3;
wire   [0:0] bit_sel3_fu_458_p3;
wire   [0:0] xor_ln210_fu_466_p2;
wire   [2:0] trunc_ln210_1_fu_472_p1;
wire   [0:0] icmp_ln209_1_fu_452_p2;
wire   [3:0] xor_ln210_1_fu_476_p3;
wire   [3:0] idx_16_fu_484_p3;
wire  signed [8:0] sext_ln207_3_fu_497_p1;
wire   [8:0] diff_34_fu_501_p2;
wire   [0:0] icmp_ln208_2_fu_507_p2;
wire   [8:0] diff_35_fu_513_p3;
wire   [0:0] bit_sel5_fu_527_p3;
wire   [0:0] xor_ln210_16_fu_535_p2;
wire   [2:0] trunc_ln210_2_fu_541_p1;
wire   [0:0] icmp_ln209_2_fu_521_p2;
wire   [3:0] xor_ln210_2_fu_545_p3;
wire   [3:0] idx_17_fu_553_p3;
wire  signed [8:0] sext_ln207_5_fu_566_p1;
wire   [8:0] diff_38_fu_570_p2;
wire   [0:0] icmp_ln208_4_fu_576_p2;
wire   [8:0] diff_39_fu_582_p3;
wire   [0:0] bit_sel8_fu_596_p3;
wire   [0:0] xor_ln210_18_fu_604_p2;
wire   [2:0] trunc_ln210_4_fu_610_p1;
wire   [0:0] icmp_ln209_4_fu_590_p2;
wire   [3:0] xor_ln210_4_fu_614_p3;
wire   [3:0] idx_19_fu_622_p3;
wire  signed [8:0] sext_ln207_6_fu_635_p1;
wire   [8:0] diff_40_fu_639_p2;
wire   [0:0] icmp_ln208_5_fu_645_p2;
wire   [8:0] diff_41_fu_651_p3;
wire   [0:0] bit_sel9_fu_665_p3;
wire   [0:0] xor_ln210_19_fu_673_p2;
wire   [2:0] trunc_ln210_5_fu_679_p1;
wire   [0:0] icmp_ln209_5_fu_659_p2;
wire   [3:0] xor_ln210_5_fu_683_p3;
wire   [3:0] idx_20_fu_691_p3;
wire  signed [8:0] sext_ln207_7_fu_704_p1;
wire   [8:0] diff_42_fu_708_p2;
wire   [0:0] icmp_ln208_6_fu_714_p2;
wire   [8:0] diff_43_fu_720_p3;
wire   [0:0] bit_sel11_fu_734_p3;
wire   [0:0] xor_ln210_20_fu_742_p2;
wire   [2:0] trunc_ln210_6_fu_748_p1;
wire   [0:0] icmp_ln209_6_fu_728_p2;
wire   [3:0] xor_ln210_6_fu_752_p3;
wire   [3:0] idx_21_fu_760_p3;
wire  signed [8:0] sext_ln207_4_fu_815_p1;
wire   [8:0] diff_36_fu_819_p2;
wire   [0:0] icmp_ln208_3_fu_824_p2;
wire   [8:0] diff_37_fu_830_p3;
wire   [0:0] bit_sel6_fu_844_p3;
wire   [0:0] xor_ln210_17_fu_852_p2;
wire   [2:0] trunc_ln210_3_fu_858_p1;
wire   [0:0] icmp_ln209_3_fu_838_p2;
wire   [3:0] xor_ln210_3_fu_862_p3;
wire   [3:0] idx_18_fu_870_p3;
wire  signed [8:0] sext_ln207_8_fu_883_p1;
wire   [8:0] diff_44_fu_887_p2;
wire   [0:0] icmp_ln208_7_fu_892_p2;
wire   [8:0] diff_45_fu_898_p3;
wire   [0:0] bit_sel12_fu_912_p3;
wire   [0:0] xor_ln210_21_fu_920_p2;
wire   [2:0] trunc_ln210_7_fu_926_p1;
wire   [0:0] icmp_ln209_7_fu_906_p2;
wire   [3:0] xor_ln210_7_fu_930_p3;
wire   [3:0] idx_22_fu_938_p3;
wire  signed [8:0] sext_ln207_9_fu_951_p1;
wire   [8:0] diff_46_fu_955_p2;
wire   [0:0] icmp_ln208_8_fu_960_p2;
wire   [8:0] diff_47_fu_966_p3;
wire   [0:0] bit_sel14_fu_980_p3;
wire   [0:0] xor_ln210_22_fu_988_p2;
wire   [2:0] trunc_ln210_8_fu_994_p1;
wire   [0:0] icmp_ln209_8_fu_974_p2;
wire   [3:0] xor_ln210_8_fu_998_p3;
wire   [3:0] idx_23_fu_1006_p3;
wire  signed [8:0] sext_ln207_10_fu_1019_p1;
wire   [8:0] diff_48_fu_1023_p2;
wire   [0:0] icmp_ln208_9_fu_1028_p2;
wire   [8:0] diff_49_fu_1034_p3;
wire   [0:0] bit_sel15_fu_1048_p3;
wire   [0:0] xor_ln210_23_fu_1056_p2;
wire   [2:0] trunc_ln210_9_fu_1062_p1;
wire   [0:0] icmp_ln209_9_fu_1042_p2;
wire   [3:0] xor_ln210_9_fu_1066_p3;
wire   [3:0] idx_24_fu_1074_p3;
wire  signed [8:0] sext_ln207_11_fu_1087_p1;
wire   [8:0] diff_50_fu_1091_p2;
wire   [0:0] icmp_ln208_10_fu_1096_p2;
wire   [8:0] diff_51_fu_1102_p3;
wire   [0:0] bit_sel13_fu_1116_p3;
wire   [0:0] xor_ln210_24_fu_1124_p2;
wire   [2:0] trunc_ln210_10_fu_1130_p1;
wire   [0:0] icmp_ln209_10_fu_1110_p2;
wire   [3:0] xor_ln210_s_fu_1134_p3;
wire   [3:0] idx_25_fu_1142_p3;
wire  signed [8:0] sext_ln207_12_fu_1155_p1;
wire   [8:0] diff_52_fu_1159_p2;
wire   [0:0] icmp_ln208_11_fu_1164_p2;
wire   [8:0] diff_53_fu_1170_p3;
wire   [0:0] bit_sel10_fu_1184_p3;
wire   [0:0] xor_ln210_25_fu_1192_p2;
wire   [2:0] trunc_ln210_11_fu_1198_p1;
wire   [0:0] icmp_ln209_11_fu_1178_p2;
wire   [3:0] xor_ln210_10_fu_1202_p3;
wire   [3:0] idx_26_fu_1210_p3;
wire  signed [8:0] sext_ln207_13_fu_1223_p1;
wire   [8:0] diff_54_fu_1227_p2;
wire   [0:0] icmp_ln208_12_fu_1232_p2;
wire   [8:0] diff_55_fu_1238_p3;
wire   [0:0] bit_sel7_fu_1252_p3;
wire   [0:0] xor_ln210_26_fu_1260_p2;
wire   [2:0] trunc_ln210_12_fu_1266_p1;
wire   [0:0] icmp_ln209_12_fu_1246_p2;
wire   [3:0] xor_ln210_11_fu_1270_p3;
wire   [3:0] idx_27_fu_1278_p3;
wire  signed [8:0] sext_ln207_14_fu_1291_p1;
wire   [8:0] diff_56_fu_1295_p2;
wire   [0:0] icmp_ln208_13_fu_1300_p2;
wire   [8:0] diff_57_fu_1306_p3;
wire   [0:0] bit_sel4_fu_1320_p3;
wire   [0:0] xor_ln210_27_fu_1328_p2;
wire   [2:0] trunc_ln210_13_fu_1334_p1;
wire   [0:0] icmp_ln209_13_fu_1314_p2;
wire   [3:0] xor_ln210_12_fu_1338_p3;
wire   [3:0] idx_28_fu_1346_p3;
wire  signed [8:0] sext_ln207_15_fu_1359_p1;
wire   [8:0] diff_58_fu_1363_p2;
wire   [0:0] icmp_ln208_14_fu_1368_p2;
wire   [8:0] diff_59_fu_1374_p3;
wire   [0:0] bit_sel1_fu_1388_p3;
wire   [0:0] xor_ln210_28_fu_1396_p2;
wire   [2:0] trunc_ln210_14_fu_1402_p1;
wire   [0:0] icmp_ln209_14_fu_1382_p2;
wire   [3:0] xor_ln210_13_fu_1406_p3;
wire   [3:0] idx_29_fu_1414_p3;
wire  signed [8:0] sext_ln207_16_fu_1427_p1;
wire   [8:0] diff_30_fu_1431_p2;
wire   [0:0] icmp_ln208_15_fu_1436_p2;
wire   [8:0] diff_31_fu_1442_p3;
wire   [0:0] bit_sel_fu_1456_p3;
wire   [0:0] xor_ln210_29_fu_1464_p2;
wire   [2:0] trunc_ln210_15_fu_1470_p1;
wire   [0:0] icmp_ln209_15_fu_1450_p2;
wire   [3:0] xor_ln210_14_fu_1474_p3;
wire   [9:0] zext_ln213_fu_1494_p1;
wire   [9:0] zext_ln213_2_fu_1500_p1;
wire   [9:0] add_ln213_fu_1507_p2;
wire   [9:0] zext_ln213_1_fu_1497_p1;
wire   [9:0] add_ln213_1_fu_1513_p2;
wire   [10:0] zext_ln213_4_fu_1519_p1;
wire   [10:0] zext_ln213_3_fu_1503_p1;
wire   [9:0] zext_ln213_6_fu_1526_p1;
wire   [9:0] zext_ln213_7_fu_1529_p1;
wire   [9:0] add_ln213_3_fu_1542_p2;
wire   [9:0] zext_ln213_5_fu_1523_p1;
wire   [9:0] add_ln213_4_fu_1548_p2;
wire   [10:0] zext_ln213_10_fu_1554_p1;
wire   [10:0] add_ln213_2_fu_1536_p2;
wire   [10:0] add_ln213_5_fu_1558_p2;
wire   [11:0] zext_ln213_9_fu_1564_p1;
wire   [11:0] zext_ln213_8_fu_1532_p1;
wire   [9:0] zext_ln213_11_fu_1568_p1;
wire   [9:0] zext_ln213_12_fu_1572_p1;
wire   [9:0] zext_ln213_13_fu_1576_p1;
wire   [9:0] zext_ln213_14_fu_1580_p1;
wire   [9:0] add_ln213_9_fu_1608_p2;
wire   [9:0] zext_ln213_16_fu_1588_p1;
wire   [9:0] zext_ln213_17_fu_1592_p1;
wire   [9:0] add_ln213_10_fu_1618_p2;
wire   [9:0] zext_ln213_15_fu_1584_p1;
wire   [9:0] add_ln213_11_fu_1624_p2;
wire   [10:0] zext_ln213_20_fu_1630_p1;
wire   [10:0] zext_ln213_19_fu_1614_p1;
wire   [11:0] zext_ln213_18_fu_1640_p1;
wire   [11:0] zext_ln213_21_fu_1648_p1;
wire   [11:0] add_ln213_8_fu_1643_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg = 1'b0;
#0 grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg = 1'b0;
end

transformer_top_stateful_softmax_EXP_LUT_ROM_AUTO_1R #(
    .DataWidth( 9 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
EXP_LUT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(EXP_LUT_address0_local),
    .ce0(EXP_LUT_ce0_local),
    .q0(EXP_LUT_q0),
    .address1(EXP_LUT_address1_local),
    .ce1(EXP_LUT_ce1_local),
    .q1(EXP_LUT_q1),
    .address2(EXP_LUT_address2_local),
    .ce2(EXP_LUT_ce2_local),
    .q2(EXP_LUT_q2),
    .address3(EXP_LUT_address3_local),
    .ce3(EXP_LUT_ce3_local),
    .q3(EXP_LUT_q3),
    .address4(EXP_LUT_address4_local),
    .ce4(EXP_LUT_ce4_local),
    .q4(EXP_LUT_q4),
    .address5(EXP_LUT_address5_local),
    .ce5(EXP_LUT_ce5_local),
    .q5(EXP_LUT_q5),
    .address6(EXP_LUT_address6),
    .ce6(EXP_LUT_ce6_local),
    .q6(EXP_LUT_q6),
    .address7(EXP_LUT_address7),
    .ce7(EXP_LUT_ce7_local),
    .q7(EXP_LUT_q7),
    .address8(EXP_LUT_address8),
    .ce8(EXP_LUT_ce8_local),
    .q8(EXP_LUT_q8)
);

transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_188_1 grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start),
    .ap_done(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_done),
    .ap_idle(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_idle),
    .ap_ready(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_ready),
    .s_gemm1_out_dout(s_gemm1_out_dout),
    .s_gemm1_out_empty_n(s_gemm1_out_empty_n),
    .s_gemm1_out_read(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_s_gemm1_out_read),
    .s_gemm1_out_num_data_valid(3'd0),
    .s_gemm1_out_fifo_cap(3'd0),
    .p_out(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out),
    .p_out_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out_ap_vld),
    .p_out1(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out1),
    .p_out1_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out1_ap_vld),
    .p_out2(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out2),
    .p_out2_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out2_ap_vld),
    .p_out3(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out3),
    .p_out3_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out3_ap_vld),
    .p_out4(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out4),
    .p_out4_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out4_ap_vld),
    .p_out5(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out5),
    .p_out5_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out5_ap_vld),
    .p_out6(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out6),
    .p_out6_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out6_ap_vld),
    .p_out7(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out7),
    .p_out7_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out7_ap_vld),
    .p_out8(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out8),
    .p_out8_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out8_ap_vld),
    .p_out9(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out9),
    .p_out9_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out9_ap_vld),
    .p_out10(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out10),
    .p_out10_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out10_ap_vld),
    .p_out11(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out11),
    .p_out11_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out11_ap_vld),
    .p_out12(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out12),
    .p_out12_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out12_ap_vld),
    .p_out13(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out13),
    .p_out13_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out13_ap_vld),
    .p_out14(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out14),
    .p_out14_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out14_ap_vld),
    .p_out15(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out15),
    .p_out15_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out15_ap_vld),
    .max_val_out(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_max_val_out),
    .max_val_out_ap_vld(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_max_val_out_ap_vld)
);

transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_217_4 grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start),
    .ap_done(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done),
    .ap_idle(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_idle),
    .ap_ready(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_ready),
    .s_softmax_out_din(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_din),
    .s_softmax_out_full_n(s_softmax_out_full_n),
    .s_softmax_out_write(grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_write),
    .s_softmax_out_num_data_valid(s_softmax_out_num_data_valid),
    .s_softmax_out_fifo_cap(s_softmax_out_fifo_cap),
    .exp_val_18(exp_val_reg_1804),
    .exp_val_20(exp_val_16_reg_1816),
    .exp_val_22(exp_val_18_reg_1827),
    .exp_val_24(exp_val_20_reg_1839),
    .exp_val_26(exp_val_22_reg_1900),
    .exp_val_28(exp_val_24_reg_1910),
    .exp_val_30(exp_val_26_reg_1920),
    .exp_val_32(exp_val_28_reg_1930),
    .zext_ln217(add_ln213_13_reg_1961),
    .zext_ln213_17(exp_val_29_reg_1955),
    .exp_val_19(exp_val_15_reg_1810),
    .exp_val_21(exp_val_17_reg_1890),
    .exp_val_23(exp_val_19_reg_1833),
    .exp_val_25(exp_val_21_reg_1895),
    .exp_val_27(exp_val_23_reg_1905),
    .exp_val_29(exp_val_25_reg_1915),
    .exp_val_31(exp_val_27_reg_1925),
    .exp_val_33(exp_val_29_reg_1955)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call19) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg <= 1'b1;
        end else if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_ready == 1'b1)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg <= 1'b1;
        end else if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_ready == 1'b1)) begin
            grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln213_12_reg_1950 <= add_ln213_12_fu_1634_p2;
        add_ln213_6_reg_1940 <= add_ln213_6_fu_1596_p2;
        add_ln213_7_reg_1945 <= add_ln213_7_fu_1602_p2;
        exp_val_17_reg_1890 <= EXP_LUT_q8;
        exp_val_21_reg_1895 <= EXP_LUT_q7;
        exp_val_22_reg_1900 <= EXP_LUT_q6;
        exp_val_23_reg_1905 <= EXP_LUT_q5;
        exp_val_24_reg_1910 <= EXP_LUT_q4;
        exp_val_25_reg_1915 <= EXP_LUT_q3;
        exp_val_26_reg_1920 <= EXP_LUT_q2;
        exp_val_27_reg_1925 <= EXP_LUT_q1;
        exp_val_28_reg_1930 <= EXP_LUT_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln213_13_reg_1961 <= add_ln213_13_fu_1651_p2;
        exp_val_29_reg_1955 <= EXP_LUT_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_val_15_reg_1810 <= EXP_LUT_q4;
        exp_val_16_reg_1816 <= EXP_LUT_q3;
        exp_val_18_reg_1827 <= EXP_LUT_q2;
        exp_val_19_reg_1833 <= EXP_LUT_q1;
        exp_val_20_reg_1839 <= EXP_LUT_q0;
        exp_val_reg_1804 <= EXP_LUT_q5;
        idx_15_reg_1885 <= idx_15_fu_1482_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sext_ln207_reg_1760 <= sext_ln207_fu_355_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        EXP_LUT_address0_local = zext_ln211_15_fu_1490_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address0_local = zext_ln211_14_fu_1422_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address0_local = zext_ln211_6_fu_768_p1;
    end else begin
        EXP_LUT_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address1_local = zext_ln211_13_fu_1354_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address1_local = zext_ln211_5_fu_699_p1;
    end else begin
        EXP_LUT_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address2_local = zext_ln211_12_fu_1286_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address2_local = zext_ln211_4_fu_630_p1;
    end else begin
        EXP_LUT_address2_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address3_local = zext_ln211_11_fu_1218_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address3_local = zext_ln211_2_fu_561_p1;
    end else begin
        EXP_LUT_address3_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address4_local = zext_ln211_10_fu_1150_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address4_local = zext_ln211_1_fu_492_p1;
    end else begin
        EXP_LUT_address4_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_address5_local = zext_ln211_9_fu_1082_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_LUT_address5_local = zext_ln211_fu_423_p1;
    end else begin
        EXP_LUT_address5_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce0_local = 1'b1;
    end else begin
        EXP_LUT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce1_local = 1'b1;
    end else begin
        EXP_LUT_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce2_local = 1'b1;
    end else begin
        EXP_LUT_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce3_local = 1'b1;
    end else begin
        EXP_LUT_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce4_local = 1'b1;
    end else begin
        EXP_LUT_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        EXP_LUT_ce5_local = 1'b1;
    end else begin
        EXP_LUT_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_ce6_local = 1'b1;
    end else begin
        EXP_LUT_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_ce7_local = 1'b1;
    end else begin
        EXP_LUT_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_LUT_ce8_local = 1'b1;
    end else begin
        EXP_LUT_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign EXP_LUT_address6 = zext_ln211_8_fu_1014_p1;

assign EXP_LUT_address7 = zext_ln211_7_fu_946_p1;

assign EXP_LUT_address8 = zext_ln211_3_fu_878_p1;

assign add_ln213_10_fu_1618_p2 = (zext_ln213_16_fu_1588_p1 + zext_ln213_17_fu_1592_p1);

assign add_ln213_11_fu_1624_p2 = (add_ln213_10_fu_1618_p2 + zext_ln213_15_fu_1584_p1);

assign add_ln213_12_fu_1634_p2 = (zext_ln213_20_fu_1630_p1 + zext_ln213_19_fu_1614_p1);

assign add_ln213_13_fu_1651_p2 = (zext_ln213_21_fu_1648_p1 + add_ln213_8_fu_1643_p2);

assign add_ln213_1_fu_1513_p2 = (add_ln213_fu_1507_p2 + zext_ln213_1_fu_1497_p1);

assign add_ln213_2_fu_1536_p2 = (zext_ln213_4_fu_1519_p1 + zext_ln213_3_fu_1503_p1);

assign add_ln213_3_fu_1542_p2 = (zext_ln213_6_fu_1526_p1 + zext_ln213_7_fu_1529_p1);

assign add_ln213_4_fu_1548_p2 = (add_ln213_3_fu_1542_p2 + zext_ln213_5_fu_1523_p1);

assign add_ln213_5_fu_1558_p2 = (zext_ln213_10_fu_1554_p1 + add_ln213_2_fu_1536_p2);

assign add_ln213_6_fu_1596_p2 = (zext_ln213_9_fu_1564_p1 + zext_ln213_8_fu_1532_p1);

assign add_ln213_7_fu_1602_p2 = (zext_ln213_11_fu_1568_p1 + zext_ln213_12_fu_1572_p1);

assign add_ln213_8_fu_1643_p2 = (zext_ln213_18_fu_1640_p1 + add_ln213_6_reg_1940);

assign add_ln213_9_fu_1608_p2 = (zext_ln213_13_fu_1576_p1 + zext_ln213_14_fu_1580_p1);

assign add_ln213_fu_1507_p2 = (zext_ln213_fu_1494_p1 + zext_ln213_2_fu_1500_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call19 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bit_sel10_fu_1184_p3 = diff_53_fu_1170_p3[32'd3];

assign bit_sel11_fu_734_p3 = diff_43_fu_720_p3[32'd3];

assign bit_sel12_fu_912_p3 = diff_45_fu_898_p3[32'd3];

assign bit_sel13_fu_1116_p3 = diff_51_fu_1102_p3[32'd3];

assign bit_sel14_fu_980_p3 = diff_47_fu_966_p3[32'd3];

assign bit_sel15_fu_1048_p3 = diff_49_fu_1034_p3[32'd3];

assign bit_sel1_fu_1388_p3 = diff_59_fu_1374_p3[32'd3];

assign bit_sel2_fu_389_p3 = diff_1_fu_375_p3[32'd3];

assign bit_sel3_fu_458_p3 = diff_33_fu_444_p3[32'd3];

assign bit_sel4_fu_1320_p3 = diff_57_fu_1306_p3[32'd3];

assign bit_sel5_fu_527_p3 = diff_35_fu_513_p3[32'd3];

assign bit_sel6_fu_844_p3 = diff_37_fu_830_p3[32'd3];

assign bit_sel7_fu_1252_p3 = diff_55_fu_1238_p3[32'd3];

assign bit_sel8_fu_596_p3 = diff_39_fu_582_p3[32'd3];

assign bit_sel9_fu_665_p3 = diff_41_fu_651_p3[32'd3];

assign bit_sel_fu_1456_p3 = diff_31_fu_1442_p3[32'd3];

assign diff_1_fu_375_p3 = ((icmp_ln208_fu_369_p2[0:0] == 1'b1) ? 9'd504 : diff_fu_363_p2);

assign diff_30_fu_1431_p2 = ($signed(sext_ln207_16_fu_1427_p1) - $signed(sext_ln207_reg_1760));

assign diff_31_fu_1442_p3 = ((icmp_ln208_15_fu_1436_p2[0:0] == 1'b1) ? 9'd504 : diff_30_fu_1431_p2);

assign diff_32_fu_432_p2 = ($signed(sext_ln207_2_fu_428_p1) - $signed(sext_ln207_fu_355_p1));

assign diff_33_fu_444_p3 = ((icmp_ln208_1_fu_438_p2[0:0] == 1'b1) ? 9'd504 : diff_32_fu_432_p2);

assign diff_34_fu_501_p2 = ($signed(sext_ln207_3_fu_497_p1) - $signed(sext_ln207_fu_355_p1));

assign diff_35_fu_513_p3 = ((icmp_ln208_2_fu_507_p2[0:0] == 1'b1) ? 9'd504 : diff_34_fu_501_p2);

assign diff_36_fu_819_p2 = ($signed(sext_ln207_4_fu_815_p1) - $signed(sext_ln207_reg_1760));

assign diff_37_fu_830_p3 = ((icmp_ln208_3_fu_824_p2[0:0] == 1'b1) ? 9'd504 : diff_36_fu_819_p2);

assign diff_38_fu_570_p2 = ($signed(sext_ln207_5_fu_566_p1) - $signed(sext_ln207_fu_355_p1));

assign diff_39_fu_582_p3 = ((icmp_ln208_4_fu_576_p2[0:0] == 1'b1) ? 9'd504 : diff_38_fu_570_p2);

assign diff_40_fu_639_p2 = ($signed(sext_ln207_6_fu_635_p1) - $signed(sext_ln207_fu_355_p1));

assign diff_41_fu_651_p3 = ((icmp_ln208_5_fu_645_p2[0:0] == 1'b1) ? 9'd504 : diff_40_fu_639_p2);

assign diff_42_fu_708_p2 = ($signed(sext_ln207_7_fu_704_p1) - $signed(sext_ln207_fu_355_p1));

assign diff_43_fu_720_p3 = ((icmp_ln208_6_fu_714_p2[0:0] == 1'b1) ? 9'd504 : diff_42_fu_708_p2);

assign diff_44_fu_887_p2 = ($signed(sext_ln207_8_fu_883_p1) - $signed(sext_ln207_reg_1760));

assign diff_45_fu_898_p3 = ((icmp_ln208_7_fu_892_p2[0:0] == 1'b1) ? 9'd504 : diff_44_fu_887_p2);

assign diff_46_fu_955_p2 = ($signed(sext_ln207_9_fu_951_p1) - $signed(sext_ln207_reg_1760));

assign diff_47_fu_966_p3 = ((icmp_ln208_8_fu_960_p2[0:0] == 1'b1) ? 9'd504 : diff_46_fu_955_p2);

assign diff_48_fu_1023_p2 = ($signed(sext_ln207_10_fu_1019_p1) - $signed(sext_ln207_reg_1760));

assign diff_49_fu_1034_p3 = ((icmp_ln208_9_fu_1028_p2[0:0] == 1'b1) ? 9'd504 : diff_48_fu_1023_p2);

assign diff_50_fu_1091_p2 = ($signed(sext_ln207_11_fu_1087_p1) - $signed(sext_ln207_reg_1760));

assign diff_51_fu_1102_p3 = ((icmp_ln208_10_fu_1096_p2[0:0] == 1'b1) ? 9'd504 : diff_50_fu_1091_p2);

assign diff_52_fu_1159_p2 = ($signed(sext_ln207_12_fu_1155_p1) - $signed(sext_ln207_reg_1760));

assign diff_53_fu_1170_p3 = ((icmp_ln208_11_fu_1164_p2[0:0] == 1'b1) ? 9'd504 : diff_52_fu_1159_p2);

assign diff_54_fu_1227_p2 = ($signed(sext_ln207_13_fu_1223_p1) - $signed(sext_ln207_reg_1760));

assign diff_55_fu_1238_p3 = ((icmp_ln208_12_fu_1232_p2[0:0] == 1'b1) ? 9'd504 : diff_54_fu_1227_p2);

assign diff_56_fu_1295_p2 = ($signed(sext_ln207_14_fu_1291_p1) - $signed(sext_ln207_reg_1760));

assign diff_57_fu_1306_p3 = ((icmp_ln208_13_fu_1300_p2[0:0] == 1'b1) ? 9'd504 : diff_56_fu_1295_p2);

assign diff_58_fu_1363_p2 = ($signed(sext_ln207_15_fu_1359_p1) - $signed(sext_ln207_reg_1760));

assign diff_59_fu_1374_p3 = ((icmp_ln208_14_fu_1368_p2[0:0] == 1'b1) ? 9'd504 : diff_58_fu_1363_p2);

assign diff_fu_363_p2 = ($signed(sext_ln207_1_fu_359_p1) - $signed(sext_ln207_fu_355_p1));

assign grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start = grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_ap_start_reg;

assign grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_ap_start_reg;

assign icmp_ln208_10_fu_1096_p2 = (($signed(diff_50_fu_1091_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_11_fu_1164_p2 = (($signed(diff_52_fu_1159_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_12_fu_1232_p2 = (($signed(diff_54_fu_1227_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_13_fu_1300_p2 = (($signed(diff_56_fu_1295_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_14_fu_1368_p2 = (($signed(diff_58_fu_1363_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_15_fu_1436_p2 = (($signed(diff_30_fu_1431_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_1_fu_438_p2 = (($signed(diff_32_fu_432_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_2_fu_507_p2 = (($signed(diff_34_fu_501_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_3_fu_824_p2 = (($signed(diff_36_fu_819_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_4_fu_576_p2 = (($signed(diff_38_fu_570_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_5_fu_645_p2 = (($signed(diff_40_fu_639_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_6_fu_714_p2 = (($signed(diff_42_fu_708_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_7_fu_892_p2 = (($signed(diff_44_fu_887_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_8_fu_960_p2 = (($signed(diff_46_fu_955_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_9_fu_1028_p2 = (($signed(diff_48_fu_1023_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_369_p2 = (($signed(diff_fu_363_p2) < $signed(9'd504)) ? 1'b1 : 1'b0);

assign icmp_ln209_10_fu_1110_p2 = (($signed(diff_51_fu_1102_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_11_fu_1178_p2 = (($signed(diff_53_fu_1170_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_12_fu_1246_p2 = (($signed(diff_55_fu_1238_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_13_fu_1314_p2 = (($signed(diff_57_fu_1306_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_14_fu_1382_p2 = (($signed(diff_59_fu_1374_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_15_fu_1450_p2 = (($signed(diff_31_fu_1442_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_1_fu_452_p2 = (($signed(diff_33_fu_444_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_2_fu_521_p2 = (($signed(diff_35_fu_513_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_3_fu_838_p2 = (($signed(diff_37_fu_830_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_4_fu_590_p2 = (($signed(diff_39_fu_582_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_5_fu_659_p2 = (($signed(diff_41_fu_651_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_6_fu_728_p2 = (($signed(diff_43_fu_720_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_7_fu_906_p2 = (($signed(diff_45_fu_898_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_8_fu_974_p2 = (($signed(diff_47_fu_966_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_9_fu_1042_p2 = (($signed(diff_49_fu_1034_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln209_fu_383_p2 = (($signed(diff_1_fu_375_p3) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign idx_15_fu_1482_p3 = ((icmp_ln209_15_fu_1450_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_14_fu_1474_p3);

assign idx_16_fu_484_p3 = ((icmp_ln209_1_fu_452_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_1_fu_476_p3);

assign idx_17_fu_553_p3 = ((icmp_ln209_2_fu_521_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_2_fu_545_p3);

assign idx_18_fu_870_p3 = ((icmp_ln209_3_fu_838_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_3_fu_862_p3);

assign idx_19_fu_622_p3 = ((icmp_ln209_4_fu_590_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_4_fu_614_p3);

assign idx_20_fu_691_p3 = ((icmp_ln209_5_fu_659_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_5_fu_683_p3);

assign idx_21_fu_760_p3 = ((icmp_ln209_6_fu_728_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_6_fu_752_p3);

assign idx_22_fu_938_p3 = ((icmp_ln209_7_fu_906_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_7_fu_930_p3);

assign idx_23_fu_1006_p3 = ((icmp_ln209_8_fu_974_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_8_fu_998_p3);

assign idx_24_fu_1074_p3 = ((icmp_ln209_9_fu_1042_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_9_fu_1066_p3);

assign idx_25_fu_1142_p3 = ((icmp_ln209_10_fu_1110_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_s_fu_1134_p3);

assign idx_26_fu_1210_p3 = ((icmp_ln209_11_fu_1178_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_10_fu_1202_p3);

assign idx_27_fu_1278_p3 = ((icmp_ln209_12_fu_1246_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_11_fu_1270_p3);

assign idx_28_fu_1346_p3 = ((icmp_ln209_13_fu_1314_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_12_fu_1338_p3);

assign idx_29_fu_1414_p3 = ((icmp_ln209_14_fu_1382_p2[0:0] == 1'b1) ? 4'd8 : xor_ln210_13_fu_1406_p3);

assign idx_fu_415_p3 = ((icmp_ln209_fu_383_p2[0:0] == 1'b1) ? 4'd8 : xor_ln_fu_407_p3);

assign s_gemm1_out_read = grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_s_gemm1_out_read;

assign s_softmax_out_din = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_din;

assign s_softmax_out_write = grp_stateful_softmax_Pipeline_VITIS_LOOP_217_4_fu_296_s_softmax_out_write;

assign sext_ln207_10_fu_1019_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out6);

assign sext_ln207_11_fu_1087_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out5);

assign sext_ln207_12_fu_1155_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out4);

assign sext_ln207_13_fu_1223_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out3);

assign sext_ln207_14_fu_1291_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out2);

assign sext_ln207_15_fu_1359_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out1);

assign sext_ln207_16_fu_1427_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out);

assign sext_ln207_1_fu_359_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out15);

assign sext_ln207_2_fu_428_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out14);

assign sext_ln207_3_fu_497_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out13);

assign sext_ln207_4_fu_815_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out12);

assign sext_ln207_5_fu_566_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out11);

assign sext_ln207_6_fu_635_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out10);

assign sext_ln207_7_fu_704_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out9);

assign sext_ln207_8_fu_883_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out8);

assign sext_ln207_9_fu_951_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_p_out7);

assign sext_ln207_fu_355_p1 = $signed(grp_stateful_softmax_Pipeline_VITIS_LOOP_188_1_fu_273_max_val_out);

assign trunc_ln210_10_fu_1130_p1 = diff_51_fu_1102_p3[2:0];

assign trunc_ln210_11_fu_1198_p1 = diff_53_fu_1170_p3[2:0];

assign trunc_ln210_12_fu_1266_p1 = diff_55_fu_1238_p3[2:0];

assign trunc_ln210_13_fu_1334_p1 = diff_57_fu_1306_p3[2:0];

assign trunc_ln210_14_fu_1402_p1 = diff_59_fu_1374_p3[2:0];

assign trunc_ln210_15_fu_1470_p1 = diff_31_fu_1442_p3[2:0];

assign trunc_ln210_1_fu_472_p1 = diff_33_fu_444_p3[2:0];

assign trunc_ln210_2_fu_541_p1 = diff_35_fu_513_p3[2:0];

assign trunc_ln210_3_fu_858_p1 = diff_37_fu_830_p3[2:0];

assign trunc_ln210_4_fu_610_p1 = diff_39_fu_582_p3[2:0];

assign trunc_ln210_5_fu_679_p1 = diff_41_fu_651_p3[2:0];

assign trunc_ln210_6_fu_748_p1 = diff_43_fu_720_p3[2:0];

assign trunc_ln210_7_fu_926_p1 = diff_45_fu_898_p3[2:0];

assign trunc_ln210_8_fu_994_p1 = diff_47_fu_966_p3[2:0];

assign trunc_ln210_9_fu_1062_p1 = diff_49_fu_1034_p3[2:0];

assign trunc_ln210_fu_403_p1 = diff_1_fu_375_p3[2:0];

assign xor_ln210_10_fu_1202_p3 = {{xor_ln210_25_fu_1192_p2}, {trunc_ln210_11_fu_1198_p1}};

assign xor_ln210_11_fu_1270_p3 = {{xor_ln210_26_fu_1260_p2}, {trunc_ln210_12_fu_1266_p1}};

assign xor_ln210_12_fu_1338_p3 = {{xor_ln210_27_fu_1328_p2}, {trunc_ln210_13_fu_1334_p1}};

assign xor_ln210_13_fu_1406_p3 = {{xor_ln210_28_fu_1396_p2}, {trunc_ln210_14_fu_1402_p1}};

assign xor_ln210_14_fu_1474_p3 = {{xor_ln210_29_fu_1464_p2}, {trunc_ln210_15_fu_1470_p1}};

assign xor_ln210_15_fu_397_p2 = (bit_sel2_fu_389_p3 ^ 1'd1);

assign xor_ln210_16_fu_535_p2 = (bit_sel5_fu_527_p3 ^ 1'd1);

assign xor_ln210_17_fu_852_p2 = (bit_sel6_fu_844_p3 ^ 1'd1);

assign xor_ln210_18_fu_604_p2 = (bit_sel8_fu_596_p3 ^ 1'd1);

assign xor_ln210_19_fu_673_p2 = (bit_sel9_fu_665_p3 ^ 1'd1);

assign xor_ln210_1_fu_476_p3 = {{xor_ln210_fu_466_p2}, {trunc_ln210_1_fu_472_p1}};

assign xor_ln210_20_fu_742_p2 = (bit_sel11_fu_734_p3 ^ 1'd1);

assign xor_ln210_21_fu_920_p2 = (bit_sel12_fu_912_p3 ^ 1'd1);

assign xor_ln210_22_fu_988_p2 = (bit_sel14_fu_980_p3 ^ 1'd1);

assign xor_ln210_23_fu_1056_p2 = (bit_sel15_fu_1048_p3 ^ 1'd1);

assign xor_ln210_24_fu_1124_p2 = (bit_sel13_fu_1116_p3 ^ 1'd1);

assign xor_ln210_25_fu_1192_p2 = (bit_sel10_fu_1184_p3 ^ 1'd1);

assign xor_ln210_26_fu_1260_p2 = (bit_sel7_fu_1252_p3 ^ 1'd1);

assign xor_ln210_27_fu_1328_p2 = (bit_sel4_fu_1320_p3 ^ 1'd1);

assign xor_ln210_28_fu_1396_p2 = (bit_sel1_fu_1388_p3 ^ 1'd1);

assign xor_ln210_29_fu_1464_p2 = (bit_sel_fu_1456_p3 ^ 1'd1);

assign xor_ln210_2_fu_545_p3 = {{xor_ln210_16_fu_535_p2}, {trunc_ln210_2_fu_541_p1}};

assign xor_ln210_3_fu_862_p3 = {{xor_ln210_17_fu_852_p2}, {trunc_ln210_3_fu_858_p1}};

assign xor_ln210_4_fu_614_p3 = {{xor_ln210_18_fu_604_p2}, {trunc_ln210_4_fu_610_p1}};

assign xor_ln210_5_fu_683_p3 = {{xor_ln210_19_fu_673_p2}, {trunc_ln210_5_fu_679_p1}};

assign xor_ln210_6_fu_752_p3 = {{xor_ln210_20_fu_742_p2}, {trunc_ln210_6_fu_748_p1}};

assign xor_ln210_7_fu_930_p3 = {{xor_ln210_21_fu_920_p2}, {trunc_ln210_7_fu_926_p1}};

assign xor_ln210_8_fu_998_p3 = {{xor_ln210_22_fu_988_p2}, {trunc_ln210_8_fu_994_p1}};

assign xor_ln210_9_fu_1066_p3 = {{xor_ln210_23_fu_1056_p2}, {trunc_ln210_9_fu_1062_p1}};

assign xor_ln210_fu_466_p2 = (bit_sel3_fu_458_p3 ^ 1'd1);

assign xor_ln210_s_fu_1134_p3 = {{xor_ln210_24_fu_1124_p2}, {trunc_ln210_10_fu_1130_p1}};

assign xor_ln_fu_407_p3 = {{xor_ln210_15_fu_397_p2}, {trunc_ln210_fu_403_p1}};

assign zext_ln211_10_fu_1150_p1 = idx_25_fu_1142_p3;

assign zext_ln211_11_fu_1218_p1 = idx_26_fu_1210_p3;

assign zext_ln211_12_fu_1286_p1 = idx_27_fu_1278_p3;

assign zext_ln211_13_fu_1354_p1 = idx_28_fu_1346_p3;

assign zext_ln211_14_fu_1422_p1 = idx_29_fu_1414_p3;

assign zext_ln211_15_fu_1490_p1 = idx_15_reg_1885;

assign zext_ln211_1_fu_492_p1 = idx_16_fu_484_p3;

assign zext_ln211_2_fu_561_p1 = idx_17_fu_553_p3;

assign zext_ln211_3_fu_878_p1 = idx_18_fu_870_p3;

assign zext_ln211_4_fu_630_p1 = idx_19_fu_622_p3;

assign zext_ln211_5_fu_699_p1 = idx_20_fu_691_p3;

assign zext_ln211_6_fu_768_p1 = idx_21_fu_760_p3;

assign zext_ln211_7_fu_946_p1 = idx_22_fu_938_p3;

assign zext_ln211_8_fu_1014_p1 = idx_23_fu_1006_p3;

assign zext_ln211_9_fu_1082_p1 = idx_24_fu_1074_p3;

assign zext_ln211_fu_423_p1 = idx_fu_415_p3;

assign zext_ln213_10_fu_1554_p1 = add_ln213_4_fu_1548_p2;

assign zext_ln213_11_fu_1568_p1 = EXP_LUT_q6;

assign zext_ln213_12_fu_1572_p1 = EXP_LUT_q5;

assign zext_ln213_13_fu_1576_p1 = EXP_LUT_q4;

assign zext_ln213_14_fu_1580_p1 = EXP_LUT_q3;

assign zext_ln213_15_fu_1584_p1 = EXP_LUT_q2;

assign zext_ln213_16_fu_1588_p1 = EXP_LUT_q1;

assign zext_ln213_17_fu_1592_p1 = EXP_LUT_q0;

assign zext_ln213_18_fu_1640_p1 = add_ln213_7_reg_1945;

assign zext_ln213_19_fu_1614_p1 = add_ln213_9_fu_1608_p2;

assign zext_ln213_1_fu_1497_p1 = exp_val_15_reg_1810;

assign zext_ln213_20_fu_1630_p1 = add_ln213_11_fu_1624_p2;

assign zext_ln213_21_fu_1648_p1 = add_ln213_12_reg_1950;

assign zext_ln213_2_fu_1500_p1 = exp_val_16_reg_1816;

assign zext_ln213_3_fu_1503_p1 = EXP_LUT_q8;

assign zext_ln213_4_fu_1519_p1 = add_ln213_1_fu_1513_p2;

assign zext_ln213_5_fu_1523_p1 = exp_val_18_reg_1827;

assign zext_ln213_6_fu_1526_p1 = exp_val_19_reg_1833;

assign zext_ln213_7_fu_1529_p1 = exp_val_20_reg_1839;

assign zext_ln213_8_fu_1532_p1 = EXP_LUT_q7;

assign zext_ln213_9_fu_1564_p1 = add_ln213_5_fu_1558_p2;

assign zext_ln213_fu_1494_p1 = exp_val_reg_1804;

endmodule //transformer_top_stateful_softmax
