// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_188_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_gemm1_out_dout,
        s_gemm1_out_empty_n,
        s_gemm1_out_read,
        s_gemm1_out_num_data_valid,
        s_gemm1_out_fifo_cap,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        p_out10,
        p_out10_ap_vld,
        p_out11,
        p_out11_ap_vld,
        p_out12,
        p_out12_ap_vld,
        p_out13,
        p_out13_ap_vld,
        p_out14,
        p_out14_ap_vld,
        p_out15,
        p_out15_ap_vld,
        max_val_out,
        max_val_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] s_gemm1_out_dout;
input   s_gemm1_out_empty_n;
output   s_gemm1_out_read;
input  [2:0] s_gemm1_out_num_data_valid;
input  [2:0] s_gemm1_out_fifo_cap;
output  [7:0] p_out;
output   p_out_ap_vld;
output  [7:0] p_out1;
output   p_out1_ap_vld;
output  [7:0] p_out2;
output   p_out2_ap_vld;
output  [7:0] p_out3;
output   p_out3_ap_vld;
output  [7:0] p_out4;
output   p_out4_ap_vld;
output  [7:0] p_out5;
output   p_out5_ap_vld;
output  [7:0] p_out6;
output   p_out6_ap_vld;
output  [7:0] p_out7;
output   p_out7_ap_vld;
output  [7:0] p_out8;
output   p_out8_ap_vld;
output  [7:0] p_out9;
output   p_out9_ap_vld;
output  [7:0] p_out10;
output   p_out10_ap_vld;
output  [7:0] p_out11;
output   p_out11_ap_vld;
output  [7:0] p_out12;
output   p_out12_ap_vld;
output  [7:0] p_out13;
output   p_out13_ap_vld;
output  [7:0] p_out14;
output   p_out14_ap_vld;
output  [7:0] p_out15;
output   p_out15_ap_vld;
output  [7:0] max_val_out;
output   max_val_out_ap_vld;

reg ap_idle;
reg s_gemm1_out_read;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg p_out10_ap_vld;
reg p_out11_ap_vld;
reg p_out12_ap_vld;
reg p_out13_ap_vld;
reg p_out14_ap_vld;
reg p_out15_ap_vld;
reg max_val_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln188_fu_300_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_gemm1_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [0:0] icmp_ln188_reg_644;
reg    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln188_fu_312_p1;
reg   [2:0] trunc_ln188_reg_648;
wire   [7:0] elems_fu_339_p1;
reg   [7:0] elems_reg_652;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [7:0] elems_4_reg_658;
reg   [7:0] max_val_fu_90;
wire   [7:0] max_val_3_fu_453_p3;
wire    ap_block_pp0_stage0_grp0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [3:0] i_fu_94;
wire   [3:0] add_ln188_fu_306_p2;
reg   [3:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage0;
reg   [7:0] empty_fu_98;
reg   [7:0] empty_46_fu_102;
reg   [7:0] empty_47_fu_106;
reg   [7:0] empty_48_fu_110;
reg   [7:0] empty_49_fu_114;
reg   [7:0] empty_50_fu_118;
reg   [7:0] empty_51_fu_122;
reg   [7:0] empty_52_fu_126;
reg   [7:0] empty_53_fu_130;
reg   [7:0] empty_54_fu_134;
reg   [7:0] empty_55_fu_138;
reg   [7:0] empty_56_fu_142;
reg   [7:0] empty_57_fu_146;
reg   [7:0] empty_58_fu_150;
reg   [7:0] empty_59_fu_154;
reg   [7:0] empty_60_fu_158;
reg    ap_block_pp0_stage0_01001_grp1;
wire    ap_block_pp0_stage0_01001_grp0;
wire   [0:0] icmp_ln197_fu_436_p2;
wire   [7:0] max_val_2_fu_441_p3;
wire   [0:0] icmp_ln197_1_fu_448_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 max_val_fu_90 = 8'd0;
#0 i_fu_94 = 4'd0;
#0 empty_fu_98 = 8'd0;
#0 empty_46_fu_102 = 8'd0;
#0 empty_47_fu_106 = 8'd0;
#0 empty_48_fu_110 = 8'd0;
#0 empty_49_fu_114 = 8'd0;
#0 empty_50_fu_118 = 8'd0;
#0 empty_51_fu_122 = 8'd0;
#0 empty_52_fu_126 = 8'd0;
#0 empty_53_fu_130 = 8'd0;
#0 empty_54_fu_134 = 8'd0;
#0 empty_55_fu_138 = 8'd0;
#0 empty_56_fu_142 = 8'd0;
#0 empty_57_fu_146 = 8'd0;
#0 empty_58_fu_150 = 8'd0;
#0 empty_59_fu_154 = 8'd0;
#0 empty_60_fu_158 = 8'd0;
#0 ap_done_reg = 1'b0;
end

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln188_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_94 <= add_ln188_fu_306_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_94 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg))) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_val_fu_90 <= 8'd128;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_val_fu_90 <= max_val_3_fu_453_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln188_reg_644 <= icmp_ln188_fu_300_p2;
        trunc_ln188_reg_648 <= trunc_ln188_fu_312_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        elems_4_reg_658 <= {{s_gemm1_out_dout[15:8]}};
        elems_reg_652 <= elems_fu_339_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd0))) begin
        empty_46_fu_102 <= {{s_gemm1_out_dout[15:8]}};
        empty_fu_98 <= elems_fu_339_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd1))) begin
        empty_47_fu_106 <= elems_fu_339_p1;
        empty_48_fu_110 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd2))) begin
        empty_49_fu_114 <= elems_fu_339_p1;
        empty_50_fu_118 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd3))) begin
        empty_51_fu_122 <= elems_fu_339_p1;
        empty_52_fu_126 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd4))) begin
        empty_53_fu_130 <= elems_fu_339_p1;
        empty_54_fu_134 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd5))) begin
        empty_55_fu_138 <= elems_fu_339_p1;
        empty_56_fu_142 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd6))) begin
        empty_57_fu_146 <= elems_fu_339_p1;
        empty_58_fu_150 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln188_reg_648 == 3'd7))) begin
        empty_59_fu_154 <= elems_fu_339_p1;
        empty_60_fu_158 <= {{s_gemm1_out_dout[15:8]}};
    end
end

always @ (*) begin
    if (((icmp_ln188_fu_300_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        max_val_out_ap_vld = 1'b1;
    end else begin
        max_val_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out11_ap_vld = 1'b1;
    end else begin
        p_out11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out12_ap_vld = 1'b1;
    end else begin
        p_out12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out13_ap_vld = 1'b1;
    end else begin
        p_out13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out14_ap_vld = 1'b1;
    end else begin
        p_out14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out15_ap_vld = 1'b1;
    end else begin
        p_out15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln188_reg_644 == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_gemm1_out_blk_n = s_gemm1_out_empty_n;
    end else begin
        s_gemm1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_gemm1_out_read = 1'b1;
    end else begin
        s_gemm1_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln188_fu_306_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((s_gemm1_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((s_gemm1_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((s_gemm1_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((s_gemm1_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign elems_fu_339_p1 = s_gemm1_out_dout[7:0];

assign icmp_ln188_fu_300_p2 = ((ap_sig_allocacmp_i_2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln197_1_fu_448_p2 = (($signed(elems_4_reg_658) > $signed(max_val_2_fu_441_p3)) ? 1'b1 : 1'b0);

assign icmp_ln197_fu_436_p2 = (($signed(elems_reg_652) > $signed(max_val_fu_90)) ? 1'b1 : 1'b0);

assign max_val_2_fu_441_p3 = ((icmp_ln197_fu_436_p2[0:0] == 1'b1) ? elems_reg_652 : max_val_fu_90);

assign max_val_3_fu_453_p3 = ((icmp_ln197_1_fu_448_p2[0:0] == 1'b1) ? elems_4_reg_658 : max_val_2_fu_441_p3);

assign max_val_out = max_val_fu_90;

assign p_out = empty_60_fu_158;

assign p_out1 = empty_59_fu_154;

assign p_out10 = empty_50_fu_118;

assign p_out11 = empty_49_fu_114;

assign p_out12 = empty_48_fu_110;

assign p_out13 = empty_47_fu_106;

assign p_out14 = empty_46_fu_102;

assign p_out15 = empty_fu_98;

assign p_out2 = empty_58_fu_150;

assign p_out3 = empty_57_fu_146;

assign p_out4 = empty_56_fu_142;

assign p_out5 = empty_55_fu_138;

assign p_out6 = empty_54_fu_134;

assign p_out7 = empty_53_fu_130;

assign p_out8 = empty_52_fu_126;

assign p_out9 = empty_51_fu_122;

assign trunc_ln188_fu_312_p1 = ap_sig_allocacmp_i_2[2:0];

endmodule //transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_188_1
