-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity transformer_top_stateful_norm_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_norm1_in_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    s_norm1_in_empty_n : IN STD_LOGIC;
    s_norm1_in_read : OUT STD_LOGIC;
    s_norm1_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    s_norm1_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    s_norm1_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    s_norm1_out_full_n : IN STD_LOGIC;
    s_norm1_out_write : OUT STD_LOGIC;
    s_norm1_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    s_norm1_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of transformer_top_stateful_norm_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln_reg_394 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_idle : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_ready : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_s_norm1_in_read : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_16_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_16_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_15_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_15_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_14_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_14_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_13_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_13_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_12_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_12_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_11_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_10_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_10_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_9_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_9_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_8_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_8_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_7_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_7_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_6_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_6_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_5_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_5_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_4_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_3_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_2_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_sum_x_out : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_sum_x_out_ap_vld : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_idle : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_ready : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_write : STD_LOGIC;
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call19 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_85_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_norm1_in_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        s_norm1_in_empty_n : IN STD_LOGIC;
        s_norm1_in_read : OUT STD_LOGIC;
        s_norm1_in_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s_norm1_in_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        buf_16_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_16_out_ap_vld : OUT STD_LOGIC;
        buf_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_15_out_ap_vld : OUT STD_LOGIC;
        buf_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_14_out_ap_vld : OUT STD_LOGIC;
        buf_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_13_out_ap_vld : OUT STD_LOGIC;
        buf_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_12_out_ap_vld : OUT STD_LOGIC;
        buf_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_11_out_ap_vld : OUT STD_LOGIC;
        buf_10_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_10_out_ap_vld : OUT STD_LOGIC;
        buf_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_9_out_ap_vld : OUT STD_LOGIC;
        buf_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_8_out_ap_vld : OUT STD_LOGIC;
        buf_7_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_7_out_ap_vld : OUT STD_LOGIC;
        buf_6_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_6_out_ap_vld : OUT STD_LOGIC;
        buf_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_5_out_ap_vld : OUT STD_LOGIC;
        buf_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_4_out_ap_vld : OUT STD_LOGIC;
        buf_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_3_out_ap_vld : OUT STD_LOGIC;
        buf_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_2_out_ap_vld : OUT STD_LOGIC;
        buf_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_out_ap_vld : OUT STD_LOGIC;
        sum_x_out : OUT STD_LOGIC_VECTOR (11 downto 0);
        sum_x_out_ap_vld : OUT STD_LOGIC );
    end component;


    component transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_109_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_norm1_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        s_norm1_out_full_n : IN STD_LOGIC;
        s_norm1_out_write : OUT STD_LOGIC;
        s_norm1_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        s_norm1_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        buf_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_3_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_5_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_7_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_9_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_11_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_13_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_15_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln100 : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_2_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_4_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_6_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_8_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_10_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_12_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_14_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_16_reload : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96 : component transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_85_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start,
        ap_done => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done,
        ap_idle => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_idle,
        ap_ready => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_ready,
        s_norm1_in_dout => s_norm1_in_dout,
        s_norm1_in_empty_n => s_norm1_in_empty_n,
        s_norm1_in_read => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_s_norm1_in_read,
        s_norm1_in_num_data_valid => ap_const_lv3_0,
        s_norm1_in_fifo_cap => ap_const_lv3_0,
        buf_16_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_16_out,
        buf_16_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_16_out_ap_vld,
        buf_15_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_15_out,
        buf_15_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_15_out_ap_vld,
        buf_14_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_14_out,
        buf_14_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_14_out_ap_vld,
        buf_13_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_13_out,
        buf_13_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_13_out_ap_vld,
        buf_12_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_12_out,
        buf_12_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_12_out_ap_vld,
        buf_11_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_11_out,
        buf_11_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_11_out_ap_vld,
        buf_10_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_10_out,
        buf_10_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_10_out_ap_vld,
        buf_9_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_9_out,
        buf_9_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_9_out_ap_vld,
        buf_8_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_8_out,
        buf_8_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_8_out_ap_vld,
        buf_7_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_7_out,
        buf_7_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_7_out_ap_vld,
        buf_6_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_6_out,
        buf_6_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_6_out_ap_vld,
        buf_5_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_5_out,
        buf_5_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_5_out_ap_vld,
        buf_4_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_4_out,
        buf_4_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_4_out_ap_vld,
        buf_3_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_3_out,
        buf_3_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_3_out_ap_vld,
        buf_2_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_2_out,
        buf_2_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_2_out_ap_vld,
        buf_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_out,
        buf_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_out_ap_vld,
        sum_x_out => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_sum_x_out,
        sum_x_out_ap_vld => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_sum_x_out_ap_vld);

    grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119 : component transformer_top_stateful_norm_2_Pipeline_VITIS_LOOP_109_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start,
        ap_done => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done,
        ap_idle => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_idle,
        ap_ready => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_ready,
        s_norm1_out_din => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_din,
        s_norm1_out_full_n => s_norm1_out_full_n,
        s_norm1_out_write => grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_write,
        s_norm1_out_num_data_valid => s_norm1_out_num_data_valid,
        s_norm1_out_fifo_cap => s_norm1_out_fifo_cap,
        buf_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_out,
        buf_3_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_3_out,
        buf_5_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_5_out,
        buf_7_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_7_out,
        buf_9_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_9_out,
        buf_11_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_11_out,
        buf_13_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_13_out,
        buf_15_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_15_out,
        sext_ln100 => trunc_ln_reg_394,
        buf_2_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_2_out,
        buf_4_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_4_out,
        buf_6_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_6_out,
        buf_8_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_8_out,
        buf_10_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_10_out,
        buf_12_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_12_out,
        buf_14_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_14_out,
        buf_16_reload => grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_buf_16_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_ready = ap_const_logic_1)) then 
                    grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call19))) then 
                    grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_ready = ap_const_logic_1)) then 
                    grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln_reg_394 <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_sum_x_out(11 downto 4);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done, grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done)
    begin
        if ((grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done)
    begin
        if ((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call19_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call19 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_ap_start_reg;
    grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_ap_start_reg;
    s_norm1_in_read <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_85_1_fu_96_s_norm1_in_read;
    s_norm1_out_din <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_din;
    s_norm1_out_write <= grp_stateful_norm_2_Pipeline_VITIS_LOOP_109_3_fu_119_s_norm1_out_write;
end behav;
