"""CLI to generate a stitched PyRTL subgraph from a JSON spec.

Usage:
    python scripts/generate_subgraph.py --spec ffn.json --out build/ffn.py
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
from pathlib import Path


def _add_src_to_path() -> None:
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    src_dir = project_root / "src"
    if str(src_dir) not in sys.path:
        sys.path.insert(0, str(src_dir))


_add_src_to_path()

from solver import TilingSolver


_IP_IMPORTS = {
    "GEMM": ("ip_cores.gemm", "GEMMCore"),
    "Softmax": ("ip_cores.softmax", "SoftmaxCore"),
    "Norm": ("ip_cores.norm", "NormCore"),
    "Activation": ("ip_cores.activation", "ActivationCore"),
    "ALU": ("ip_cores.alu", "ALUCore"),
    "MemRouter": ("ip_cores.mem_router", "MemRouterCore"),
}

_IP_EXTRA_DEFAULTS = {
    "Norm": {"is_rmsnorm": False, "gamma": 1, "beta": 0},
    "Activation": {"activation_type": "relu"},
}

_IPS_WITH_BLOCK_PARAM = {"GEMM", "Softmax", "MemRouter"}


def _generate_code(spec: dict, config: dict, name: str) -> str:
    ips = spec["ips"]
    edges = spec.get("edges", [])

    imports = set()
    for ip in ips:
        module, cls = _IP_IMPORTS[ip["type"]]
        imports.add((module, cls))
    imports.add(("stitcher", "Stitcher"))

    import_lines = []
    for module, cls in sorted(imports):
        import_lines.append(f"from {module} import {cls}")
    import_lines.insert(0, "import pyrtl")

    config_lines = ["CONFIG = {"]
    for ip_name, params in sorted(config.items()):
        param_str = ", ".join(f'"{k}": {v}' for k, v in sorted(params.items()))
        config_lines.append(f'    "{ip_name}": {{{param_str}}},')
    config_lines.append("}")

    build_lines = []
    build_lines.append(f"def build_{name}():")
    build_lines.append("    shared_block = pyrtl.Block()")
    build_lines.append("    original_Block = pyrtl.Block")
    build_lines.append("    pyrtl.Block = lambda: shared_block")
    build_lines.append("    try:")

    for ip in ips:
        ip_type = ip["type"]
        ip_name = ip["name"]
        ip_config = config.get(ip_name, {})
        params = []
        for p in ip["params"]:
            params.append(f"{p}={ip_config.get(p, 1)}")
        params.append(f'name="{ip_name}"')
        if ip_type in _IPS_WITH_BLOCK_PARAM:
            params.append("block=shared_block")
        extra = _IP_EXTRA_DEFAULTS.get(ip_type, {})
        for k, v in extra.items():
            if isinstance(v, str):
                params.append(f'{k}="{v}"')
            else:
                params.append(f"{k}={v}")
        cls = _IP_IMPORTS[ip_type][1]
        build_lines.append(f"        {ip_name} = {cls}({', '.join(params)})")

    build_lines.append("    finally:")
    build_lines.append("        pyrtl.Block = original_Block")
    build_lines.append("")
    build_lines.append("    stitcher = Stitcher(block=shared_block)")
    for ip in ips:
        build_lines.append(f"    stitcher.add_ip({ip['name']})")
    for src, dst in edges:
        build_lines.append(f'    stitcher.connect("{src}", "{dst}")')
    build_lines.append("    block, drivers = stitcher.build()")
    build_lines.append("    return block, drivers")

    config_comment_lines = []
    config_comment_lines.append("# Optimal tiling configuration:")
    for ip_name, params in sorted(config.items()):
        parts = [f"{k}={v}" for k, v in sorted(params.items())]
        config_comment_lines.append(f"#   {ip_name}: {', '.join(parts)}")

    lines = [
        "# Auto-generated by generate_subgraph.py",
        "",
        *config_comment_lines,
        "",
        *config_lines,
        "",
        *import_lines,
        "",
        *build_lines,
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a stitched PyRTL subgraph")
    parser.add_argument("--spec", required=True, help="Path to JSON graph spec")
    parser.add_argument("--out", help="Path to output Python file (default: stdout)")
    parser.add_argument(
        "--max-path-depth",
        type=int,
        default=20,
        help="Timing constraint for TilingSolver",
    )
    args = parser.parse_args()

    spec_path = Path(args.spec)
    with spec_path.open("r", encoding="utf-8") as f:
        spec = json.load(f)

    solver = TilingSolver(max_path_depth=args.max_path_depth)
    config = solver.solve(spec)

    name = spec.get("name", "subgraph")
    code = _generate_code(spec, config, name)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as f:
            f.write(code)
    else:
        print(code)


if __name__ == "__main__":
    main()
