// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_217_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_softmax_out_din,
        s_softmax_out_full_n,
        s_softmax_out_write,
        s_softmax_out_num_data_valid,
        s_softmax_out_fifo_cap,
        exp_val_18,
        exp_val_20,
        exp_val_22,
        exp_val_24,
        exp_val_26,
        exp_val_28,
        exp_val_30,
        exp_val_32,
        zext_ln217,
        zext_ln213_17,
        exp_val_19,
        exp_val_21,
        exp_val_23,
        exp_val_25,
        exp_val_27,
        exp_val_29,
        exp_val_31,
        exp_val_33
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] s_softmax_out_din;
input   s_softmax_out_full_n;
output   s_softmax_out_write;
input  [31:0] s_softmax_out_num_data_valid;
input  [31:0] s_softmax_out_fifo_cap;
input  [8:0] exp_val_18;
input  [8:0] exp_val_20;
input  [8:0] exp_val_22;
input  [8:0] exp_val_24;
input  [8:0] exp_val_26;
input  [8:0] exp_val_28;
input  [8:0] exp_val_30;
input  [8:0] exp_val_32;
input  [11:0] zext_ln217;
input  [8:0] zext_ln213_17;
input  [8:0] exp_val_19;
input  [8:0] exp_val_21;
input  [8:0] exp_val_23;
input  [8:0] exp_val_25;
input  [8:0] exp_val_27;
input  [8:0] exp_val_29;
input  [8:0] exp_val_31;
input  [8:0] exp_val_33;

reg ap_idle;
reg s_softmax_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
reg    ap_block_state21_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln217_fu_243_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_softmax_out_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [16:0] zext_ln223_fu_313_p1;
reg   [3:0] i_fu_108;
wire   [3:0] add_ln217_fu_249_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] exp_val_fu_259_p17;
wire   [2:0] trunc_ln217_fu_255_p1;
wire   [8:0] exp_val_fu_259_p19;
wire   [12:0] zext_ln217_cast_fu_231_p1;
wire   [12:0] zext_ln213_17_cast_fu_227_p1;
wire   [12:0] add_ln223_fu_307_p2;
wire   [16:0] grp_fu_317_p0;
wire   [12:0] grp_fu_317_p1;
wire   [8:0] exp_val_1_fu_323_p17;
wire   [8:0] exp_val_1_fu_323_p19;
wire   [16:0] grp_fu_371_p0;
wire   [12:0] grp_fu_371_p1;
wire   [16:0] grp_fu_317_p2;
wire   [1:0] tmp_fu_382_p4;
wire   [0:0] icmp_ln224_fu_392_p2;
wire   [6:0] trunc_ln225_fu_398_p1;
wire   [6:0] elems_fu_402_p3;
wire   [16:0] grp_fu_371_p2;
wire   [1:0] tmp_1_fu_414_p4;
wire   [0:0] icmp_ln224_1_fu_424_p2;
wire   [6:0] trunc_ln225_1_fu_430_p1;
wire   [6:0] elems_2_fu_434_p3;
wire   [7:0] zext_ln219_fu_410_p1;
wire   [14:0] b_fu_442_p3;
reg    grp_fu_317_ce;
reg    grp_fu_371_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] exp_val_fu_259_p1;
wire   [2:0] exp_val_fu_259_p3;
wire   [2:0] exp_val_fu_259_p5;
wire   [2:0] exp_val_fu_259_p7;
wire  signed [2:0] exp_val_fu_259_p9;
wire  signed [2:0] exp_val_fu_259_p11;
wire  signed [2:0] exp_val_fu_259_p13;
wire  signed [2:0] exp_val_fu_259_p15;
wire   [2:0] exp_val_1_fu_323_p1;
wire   [2:0] exp_val_1_fu_323_p3;
wire   [2:0] exp_val_1_fu_323_p5;
wire   [2:0] exp_val_1_fu_323_p7;
wire  signed [2:0] exp_val_1_fu_323_p9;
wire  signed [2:0] exp_val_1_fu_323_p11;
wire  signed [2:0] exp_val_1_fu_323_p13;
wire  signed [2:0] exp_val_1_fu_323_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 i_fu_108 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 9 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 9 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 9 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 9 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 9 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 9 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 9 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 9 ),
    .def_WIDTH( 9 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 9 ))
sparsemux_17_3_9_1_1_U428(
    .din0(exp_val_18),
    .din1(exp_val_20),
    .din2(exp_val_22),
    .din3(exp_val_24),
    .din4(exp_val_26),
    .din5(exp_val_28),
    .din6(exp_val_30),
    .din7(exp_val_32),
    .def(exp_val_fu_259_p17),
    .sel(trunc_ln217_fu_255_p1),
    .dout(exp_val_fu_259_p19)
);

transformer_top_udiv_17ns_13ns_17_21_1 #(
    .ID( 1 ),
    .NUM_STAGE( 21 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 17 ))
udiv_17ns_13ns_17_21_1_U429(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_317_p0),
    .din1(grp_fu_317_p1),
    .ce(grp_fu_317_ce),
    .dout(grp_fu_317_p2)
);

(* dissolve_hierarchy = "yes" *) transformer_top_sparsemux_17_3_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 9 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 9 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 9 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 9 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 9 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 9 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 9 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 9 ),
    .def_WIDTH( 9 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 9 ))
sparsemux_17_3_9_1_1_U430(
    .din0(exp_val_19),
    .din1(exp_val_21),
    .din2(exp_val_23),
    .din3(exp_val_25),
    .din4(exp_val_27),
    .din5(exp_val_29),
    .din6(exp_val_31),
    .din7(exp_val_33),
    .def(exp_val_1_fu_323_p17),
    .sel(trunc_ln217_fu_255_p1),
    .dout(exp_val_1_fu_323_p19)
);

transformer_top_udiv_17ns_13ns_17_21_1 #(
    .ID( 1 ),
    .NUM_STAGE( 21 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 17 ))
udiv_17ns_13ns_17_21_1_U431(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_371_p0),
    .din1(grp_fu_371_p1),
    .ce(grp_fu_371_ce),
    .dout(grp_fu_371_p2)
);

transformer_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln217_fu_243_p2 == 1'd0))) begin
            i_fu_108 <= add_ln217_fu_249_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_108 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln217_fu_243_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_317_ce = 1'b1;
    end else begin
        grp_fu_317_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_371_ce = 1'b1;
    end else begin
        grp_fu_371_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter20 == 1'b1))) begin
        s_softmax_out_blk_n = s_softmax_out_full_n;
    end else begin
        s_softmax_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter20 == 1'b1))) begin
        s_softmax_out_write = 1'b1;
    end else begin
        s_softmax_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln217_fu_249_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign add_ln223_fu_307_p2 = (zext_ln217_cast_fu_231_p1 + zext_ln213_17_cast_fu_227_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage0_iter20));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage0_iter20));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_block_state21_pp0_stage0_iter20));
end

always @ (*) begin
    ap_block_state21_pp0_stage0_iter20 = (s_softmax_out_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_fu_442_p3 = {{elems_2_fu_434_p3}, {zext_ln219_fu_410_p1}};

assign elems_2_fu_434_p3 = ((icmp_ln224_1_fu_424_p2[0:0] == 1'b1) ? 7'd127 : trunc_ln225_1_fu_430_p1);

assign elems_fu_402_p3 = ((icmp_ln224_fu_392_p2[0:0] == 1'b1) ? 7'd127 : trunc_ln225_fu_398_p1);

assign exp_val_1_fu_323_p17 = 'bx;

assign exp_val_fu_259_p17 = 'bx;

assign grp_fu_317_p0 = {{exp_val_fu_259_p19}, {8'd0}};

assign grp_fu_317_p1 = zext_ln223_fu_313_p1;

assign grp_fu_371_p0 = {{exp_val_1_fu_323_p19}, {8'd0}};

assign grp_fu_371_p1 = zext_ln223_fu_313_p1;

assign icmp_ln217_fu_243_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln224_1_fu_424_p2 = ((tmp_1_fu_414_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_392_p2 = ((tmp_fu_382_p4 == 2'd1) ? 1'b1 : 1'b0);

assign s_softmax_out_din = b_fu_442_p3;

assign tmp_1_fu_414_p4 = {{grp_fu_371_p2[8:7]}};

assign tmp_fu_382_p4 = {{grp_fu_317_p2[8:7]}};

assign trunc_ln217_fu_255_p1 = ap_sig_allocacmp_i_1[2:0];

assign trunc_ln225_1_fu_430_p1 = grp_fu_371_p2[6:0];

assign trunc_ln225_fu_398_p1 = grp_fu_317_p2[6:0];

assign zext_ln213_17_cast_fu_227_p1 = zext_ln213_17;

assign zext_ln217_cast_fu_231_p1 = zext_ln217;

assign zext_ln219_fu_410_p1 = elems_fu_402_p3;

assign zext_ln223_fu_313_p1 = add_ln223_fu_307_p2;

endmodule //transformer_top_stateful_softmax_Pipeline_VITIS_LOOP_217_4
